### ISSUE TITLE
缺少 unofficial-mongoose ，请指教

### ISSUE THREAD

**Issue by culturenet** [ttttupup/wxhelper#1]
你好，对c++不是很熟悉，编译卡在了unofficial-mongoose 这个地方，网上也搜不到，还请指教指教，不胜感激

**Comment by ttttupup** [comment]
我本地使用的是vcpkg安装的mongoose。对应的版本是mongoose:x86-windows    7.6。  安装命令   vcpkg install  mongoose

**Comment by ttttupup** [comment]
你也可以不用cmake，自己构建mongoose，mongoose特别适合嵌入

**Comment by culturenet** [comment]
收到，已经完美解决，非常感谢
