### ISSUE TITLE
想请教下 3.9.2.23-V4 怎么获取别人发图片？

### ISSUE THREAD

**Issue by langodhul** [ttttupup/wxhelper#100]
hook图片。接口请求不成功
获取解密图片。本地目录没有完整图片，只有缩略图

**Comment by ttttupup** [comment]
用type=56 接口下载消息附件，就会有完整图片。

**Comment by ttttupup** [comment]
hook图片的接口不推荐使用了，大图片都是被动下载的，后面会废弃掉。

**Comment by langodhul** [comment]
> 用type=56 接口下载消息附件，就会有完整图片。

这个接口之前试了下用msg['msgId']作为参数请求，返回状态200，但是code为0，msg['path']目录下没有图片。。

**Comment by zxbin2000** [comment]
> 用type=56 接口下载消息附件，就会有完整图片。

接口响应：{"code":-2,"result":"OK"}

错误信息：MSG db handle is null

@ttttupup 麻烦问下这种问题遇到了，有什么好的解决方案呢？谢谢~

**Comment by ttttupup** [comment]
> > 用type=56 接口下载消息附件，就会有完整图片。
> 
> @ttttupup 这个接口之前试了下用msg['msgId']作为参数请求，返回0， ok ，但是msg['path']目录下没有图片。。

在微信目录下的wxheper目录里

**Comment by ttttupup** [comment]
> 



> > 用type=56 接口下载消息附件，就会有完整图片。
> 
> 接口响应：{"code":-2,"result":"OK"}
> 
> 错误信息：MSG db handle is null
> 
> @ttttupup 麻烦问下这种问题遇到了，有什么好的解决方案呢？谢谢~

先调用一下34接口，看下数据库句柄能正常返回吗？这个是没查到句柄

**Comment by 254896769** [comment]
3.9.2.23-V4 同一张图片重复接收，用type=56 接口下载消息附件， 接口响应：{"code":-2,"result":"OK"}

**Comment by 254896769** [comment]
不同照片也出现过同样的情况，一样的错误提示 微信目录下的wxhelper也没找到对应的msgId的图片

**Comment by langodhul** [comment]
> 用type=56 接口下载消息附件，就会有完整图片。

这个试了好像虽然

> > > 用type=56 接口下载消息附件，就会有完整图片。
> > 
> > 
> > @ttttupup 这个接口之前试了下用msg['msgId']作为参数请求，返回0， ok ，但是msg['path']目录下没有图片。。
> 
> 在微信目录下的wxheper目录里

@langodhul 

> > > 用type=56 接口下载消息附件，就会有完整图片。
> > 
> > 
> > @ttttupup 这个接口之前试了下用msg['msgId']作为参数请求，返回0， ok ，但是msg['path']目录下没有图片。。
> 
> 在微信目录下的wxheper目录里

@ttttupup  可以了，谢谢

**Comment by ttttupup** [comment]
> 3.9.2.23-V4 同一张图片重复接收，用type=56 接口下载消息附件， 接口响应：{"code":-2,"result":"OK"}

-2 是没查到这条消息

**Comment by zxbin2000** [comment]
> 



> > 
> 
> > > 用type=56 接口下载消息附件，就会有完整图片。
> > 
> > 
> > 接口响应：{"code":-2,"result":"OK"}
> > 错误信息：MSG db handle is null
> > @ttttupup 麻烦问下这种问题遇到了，有什么好的解决方案呢？谢谢~
> 
> 先调用一下34接口，看下数据库句柄能正常返回吗？这个是没查到句柄

还是没有成功，描述下我的测试过程：
1. 在文件传输助手，收到的源消息为：
`{"content":"<?xml version=\"1.0\"?>\n<msg>\n\t<img aeskey=\"1c5dc2891e03655c4c1741eb16809f9c\" encryver=\"0\" ...."fromGroup":"filehelper","fromUser":"filehelper","isSendByPhone":1,"isSendMsg":1,"msgId":5521804890086222000,"path":"qqxxxxxx\\FileStorage\\MsgAttach\\9e20f478899dc29eb19741386f9343c8\\Image\\2023-04\\e2514ae4d7d2aeb9abd60a3920ab8e21.dat","pid":11800,"sign":"6043c4026edf196f696ee6e47c0abbb3","signature":"<msgsource>\n\t<sec_msg_node>\n\t\t<uuid>58f7597bb92e44508e42660b173ce7f8_</uuid>\n\t</sec_msg_node>\n\t<signature>v1_edi6QtdE</signature>\n\t<tmp_node>\n\t\t<publisher-id>&lt;![CDATA[]]&gt;</publisher-id>\n\t</tmp_node>\n</msgsource>\n","thumbPath":"qqxxxxxx\\FileStorage\\MsgAttach\\9e20f478899dc29eb19741386f9343c8\\Thumb\\2023-04\\dd59034c874cb1d2d722da55f34d745d_t.dat","time":"2023-04-15 16:38:33","timestamp":1681547913,"type":3}`

2. 使用 32 接口，查询操作句柄，获取结果里包含 MSG0.db 和 MSG1.db ，handle 分别为 164580672、164581680；
3. 使用 34 接口，查询刚才的图片消息，参数：{ "dbHandle": 164581680, "sql": "select localId from MSG where MsgSvrID=5521804890086222000" } 返回结果为：{"code":1,"data":[],"result":"OK"}
4. 使用 56 接口，参数：{ "msgId": 5521804890086222000 }   msgId 使用的是和 1 中相同的，返回结果为：{"code":-2,"result":"OK"}  

@ttttupup @langodhul 请教两位看看，后续我可以往哪方面来排查这个问题呢？谢谢哈~

**Comment by ttttupup** [comment]
第三步就没查到数据，这个消息id是number类型的，注意一些语言，比如js就会被转义，导致id不正确。建议还是看下控制台打印的内容或者直接用数据库客户端查看一些。

**Comment by zxbin2000** [comment]
> 

果然是 id 的问题，我用的 nodejs 新写了服务，是 id 不正确，直接 Buffer.toString() 重新输出 id 后，调用成功。

感谢感谢，这个提示对我帮助很大， @ttttupup 可以开下赞助哈，好项目，不希望白用你的建议，我这里以个人名义赞助优秀开源作者~

**Comment by HyperClockUp** [comment]
> > 
> 
> 果然是 id 的问题，我用的 nodejs 新写了服务，是 id 不正确，直接 Buffer.toString() 重新输出 id 后，调用成功。
> 
> 感谢感谢，这个提示对我帮助很大， @ttttupup 可以开下赞助哈，好项目，不希望白用你的建议，我这里以个人名义赞助优秀开源作者~

@zxbin2000 你好，我现在也遇到这个问题了，请问nodejs的Buffer.toString()具体指的是什么呢？我使用net模块创建了一个tcp服务后接收到消息
```typescript
const server = net.createServer((socket) => {
  let buffer = ''
  socket.on('data', (data) => {
    buffer += data.toString();
  });

  socket.on('end', () => {
    handleMessage(JSON.parse(buffer))
  });
});
```
在这里获取到的msgId进行图片下载是报错的，请问你是具体怎么解决的呢，希望不吝指教，感谢！

**Comment by HyperClockUp** [comment]
> > 
> 
> 果然是 id 的问题，我用的 nodejs 新写了服务，是 id 不正确，直接 Buffer.toString() 重新输出 id 后，调用成功。
> 
> 感谢感谢，这个提示对我帮助很大， @ttttupup 可以开下赞助哈，好项目，不希望白用你的建议，我这里以个人名义赞助优秀开源作者~

我找到问题了，原因是：
在socket中获取到字符串类型的msgId是
> "msgId":749113148472435283
但如果直接按照
```typescript
const server = net.createServer((socket) => {
  let buffer = ''
  socket.on('data', (data) => {
    buffer += data.toString();
  });

  socket.on('end', () => {
    console.log(buffer);
    handleMessage(JSON.parse(buffer))
  });
});
```
msgId就会因为Node的数字精度问题(-2^53 + 1 到 2^53 - 1)丢失最后两位，即变成
> "msgId":749113148472435200

因此msgId查不到对应的消息

后面如果有人遇到这个问题可以参考这个回答，同时感谢项目的开发者和贡献者们！
