### ISSUE TITLE
希望增加几个功能

### ISSUE THREAD

**Issue by 254896769** [ttttupup/wxhelper#101]
我看已经有确认收款功能，可否另外增加取消收款功能
已经有发文件，视频，图片的功能，可否另外增加发送语音功能
已经有获取朋友圈的功能，可否能否增加点赞 评论 发表功能
关注很久了，继续期待ING~

**Comment by ttttupup** [comment]
语音这个pc版就没有的功能，实现不了

**Comment by 254896769** [comment]
我之前好像看到有人用PC接口实现了 挺奇怪的 传入的是十六进制（silk文件的文件格式数据）

**Comment by ttttupup** [comment]
以前pc版有个转发语音的功能，现在砍掉了。能实现也不奇怪

**Comment by degangliu** [comment]
> 以前pc版有个转发语音的功能，现在砍掉了。能实现也不奇怪

能实现就爽了

**Comment by wangxingsheng** [comment]
能获取好友备注就更好了

**Comment by toolvip** [comment]
能加上发送小程序和获取小程序code就更秒了。
