### ISSUE TITLE
通过好友申请的API 如果好友过多的情况下 不会自动通过

### ISSUE THREAD

**Issue by 254896769** [ttttupup/wxhelper#105]
正常的能自动通过好友申请。但是如果超过5000个微信好友，手动通过好友申请会弹出以下选项，不会自动通过

![微信好友太多 无法自动加](https://user-images.githubusercontent.com/46452924/233003355-be347c80-d4ab-4d11-81a4-0fd0fe008a40.png)

**Comment by ttttupup** [comment]
应该是触发风控了，改下入参应该就可以了，不过这个我没法复现。

**Comment by ttttupup** [comment]
正常通过的时候这个也可以手动选，有时间了测试一下。

**Comment by 254896769** [comment]
还有HOOK消息功能，“自己发出去消息”，好像只能HOOK到手机端，不能HOOK到PC端

**Comment by 254896769** [comment]
还有接收带有emoji表情的文本消息时，接受到的emoji表情会自动转为问号，这个要怎么转义呢？
还有emoji表情怎么发送出去？

**Comment by 254896769** [comment]
获取消息附件 有时候会下载不了图片 而且微信会崩溃

**Comment by lanlandexiaolan** [comment]
> 还有HOOK消息功能，自己发出去消息中，好像只能HOOK到手机端自己发出去的消息，不能HOOK到PC端自己发出去的消息

这个我好像也是的

**Comment by 254896769** [comment]
如果对方"通过名片分享"添加我为好友，也不会自动通过

**Comment by ttttupup** [comment]
> > 还有HOOK消息功能，自己发出去消息中，好像只能HOOK到手机端自己发出去的消息，不能HOOK到PC端自己发出去的消息
> 
> 这个我好像也是的

这个只是hook 同步接收的消息。

**Comment by DevilStarMod** [comment]
> 如果对方"通过名片分享"添加我为好友，虽然通过好友申请的API返回 {"code":1,"result":"OK"}，但是也没有自动通过
@ttttupup 大佬，下个版本会修复这个吗

**Comment by ttttupup** [comment]
![image](https://user-images.githubusercontent.com/31303661/235092470-e2335844-3f08-44be-a404-68187a2d1659.png)
把这个esi的值 换成MOV        ESI,0x8  试一下。

**Comment by 254896769** [comment]
> ![image](https://user-images.githubusercontent.com/31303661/235092470-e2335844-3f08-44be-a404-68187a2d1659.png) 把这个esi的值 换成MOV ESI,0x8 试一下。

解决了我此贴提问的联系人较多无法自动通过的问题，还有一个问题是如果对方"通过名片分享"添加我为好友，无法自动通过

**Comment by DevilStarMod** [comment]
"通过名片"申请添加好友的，permission传多少？我试了8是不会通过

**Comment by ttttupup** [comment]
名片不是这个功能

**Comment by DevilStarMod** [comment]
> 名片不是这个功能

对方通过名片添加我为好友，我想要自动通过验证，目前还没有这个api是吗？

**Comment by ttttupup** [comment]
不能用那就是没有

**Comment by DevilStarMod** [comment]
好的

**Comment by ttttupup** [comment]
名片添加好友没测试过，这个接口只测试了正常的加好友

**Comment by DevilStarMod** [comment]
![1683797693505](https://github.com/ttttupup/wxhelper/assets/6915929/01407e7d-6c22-45ca-9d60-6f456bd0ffc1)
EDI 传入好友请求参数里面的scene（通过名片添加是0x11），解决了名片添加好友的问题

**Comment by ttttupup** [comment]
这个值就是权限，可以都测试一遍，把这个可以开放给用户自己传值。

**Comment by DevilStarMod** [comment]
权限不是flag吗，permission参数那个

**Comment by ttttupup** [comment]
忘了，已经开放出来了
