### ISSUE TITLE
http://localhost:19088/api/?type=9：json.exception.type_error.305

### ISSUE THREAD

**Issue by lwwing** [ttttupup/wxhelper#108]
http://localhost:19088/api/?type=9 
这个接口调用会出现{"msg":"[json.exception.type_error.305] cannot use operator[] with a string argument with discarded","result":"ERROR"}

http://localhost:19088/api/?type=1
是正常能获取到用户身份。

**Comment by terry-tt** [comment]
看doc目录下的接口文档，type=9接口增加字段了
