### ISSUE TITLE
能否增加接受转账、领取红包功能呢？

### ISSUE THREAD

**Issue by luochaolun** [ttttupup/wxhelper#11]
要是能通过hook接受转账、或者领取红包就太好了，就可以多加群自动抢红包了[坏笑]

**Comment by ttttupup** [comment]
这个功能不会考虑的，做了只会被删库。

**Comment by luochaolun** [comment]
增加个接收转账的应该可以吧，刚看了那个3.7的版本里，已经有接受转账的功能了，ljw得哪个c#版的！
