### ISSUE TITLE
49接口 文字识别总是返回空文本 用PC右键可以识别到内容

### ISSUE THREAD

**Issue by 502647092** [ttttupup/wxhelper#110]
微信版本:
DLL版本: 3.9.2.23-v5 release 编译

请求
```
POST http://127.0.0.1:19088/api/?type=49
Content-Type: application/json

{
    "imagePath": "C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_xxxxxxxxxxxxx\\wxhelper\\image\\5845865159623874039.png"
}
```

返回
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 0000000035

{
  "code": 0,
  "result": "OK",
  "text": ""
}
```

此图片用微信客户端右键提取文本是有内容的

麻烦问下哪里有问题

**Comment by ttttupup** [comment]
图片需要微信的.dat格式

**Comment by 502647092** [comment]
尝试了 消息体内的两个dat文件 还是返回了空的

C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_xxxxxxxxxxxxx\\FileStorage\\MsgAttach\\f2067bb6bcd1bc673c7e16bdc6f3b9b2\\Image\\2023-04\\8fc8f540f9d9c135fcba5334ed3f0f28.dat

C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_xxxxxxxxxxxxx\\FileStorage\\MsgAttach\\f2067bb6bcd1bc673c7e16bdc6f3b9b2\\Thumb\\2023-04\\a8ce7f3502279a015b6e51e94f75515e_t.dat

**Comment by ttttupup** [comment]
发张图片给自己，然后hook消息有路径，用那里的文件。_t.dat文件应该是个临时文件。如果还不行的话，那就可能有bug了，ocr功能不是刚刚爆出个ocr引擎的问题嘛，打开图片就闪退。

**Comment by 502647092** [comment]
这两个路径就是hook消息里面的 path 和 thumbPath

**Comment by guanzi008** [comment]
我测试正常好像是V4版本能用
