### ISSUE TITLE
微信好友列表的数量获取

### ISSUE THREAD

**Issue by weihua-git** [ttttupup/wxhelper#118]
大佬有没有能获取到微信好友列表的数量的接口，
这个列表，包含了很多，就算判断这个好友类型，但是好像没有固定的规则，type 五花八门
![image](https://user-images.githubusercontent.com/59214326/235070434-bf14466c-9472-4fe6-bd36-d4e2538dcc00.png)

**Comment by weihua-git** [comment]
和微信上显示的不一样 统计出来

**Comment by ttttupup** [comment]
这个是和通讯录管理上的一致，不一致的话自己看下如何筛选到一致。
