### ISSUE TITLE
版本更新拉.3.9.2.26

### ISSUE THREAD

**Issue by pandyer** [ttttupup/wxhelper#120]
版本更新拉.3.9.2.26

**Comment by lanlandexiaolan** [comment]
我去，效率好高啊大佬

**Comment by pandyer** [comment]
> 我去，效率好高啊大佬

看清楚哈, 我在催更

**Comment by pandyer** [comment]
[ComWeChatRobot](https://github.com/ljc545w/ComWeChatRobot) 这个怎么 版本就停留在 3.7 了.

**Comment by lanlandexiaolan** [comment]
> > 我去，效率好高啊大佬
> 
> 看清楚哈, 我在催更

你俩头像一样，看错了hhhhh

**Comment by guanzi008** [comment]
坐等3.9.2.26
