### ISSUE TITLE
使用xenos注入时出现0xC0000135,使用其他的所有注入程序时都有问题

### ISSUE THREAD

**Issue by chuilishi** [ttttupup/wxhelper#122]
用微软的那个Process Monitor看了一下,当用其他注入程序注入时会建立一个进程然后立刻退出,像这样
![image](https://user-images.githubusercontent.com/108377487/235464421-04a8a7f5-8d56-4444-8e7d-ae2d0325b61b.png)
用xenos时就是
![image](https://user-images.githubusercontent.com/108377487/235464493-0a7ddcf8-5c67-47b2-9166-2a2275b0ecd9.png)

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/discussions/65
