### ISSUE TITLE
群成员头像图片地址获取？

### ISSUE THREAD

**Issue by degangliu** [ttttupup/wxhelper#123]
似乎没有提供刷新群成员头像地址的方法呢？ 只有主动查看过群成员资料的人才能拿到 wx.qlogo.cn的链接地址，这个查看动作怎么触发？

**Comment by ttttupup** [comment]
查询群成员就应该会刷新，具体忘了

**Comment by ttttupup** [comment]
有个获取群/群成员信息的接口，如果没有就是没提交。
