### ISSUE TITLE
微信3.9.2.23  出现崩溃

### ISSUE THREAD

**Issue by weihua-git** [ttttupup/wxhelper#124]
麻烦大佬看看
![898cad73287c86efaaf433778c1d3c1](https://user-images.githubusercontent.com/59214326/236395158-2b812ec9-3781-49f8-89e3-0ba739096f2a.jpg)
报错日志
[WeChat146c726.txt](https://github.com/ttttupup/wxhelper/files/11403976/WeChat146c726.txt)
[WeChat146c726FMD5.txt](https://github.com/ttttupup/wxhelper/files/11403977/WeChat146c726FMD5.txt)

**Comment by ttttupup** [comment]
这调用的不是wxhelper的dll

**Comment by ttttupup** [comment]
可以使用新版本，旧版本精力有限不维护了。
