### ISSUE TITLE
接收到的消息乱码问题

### ISSUE THREAD

**Issue by wakswaks** [ttttupup/wxhelper#126]
使用的3.9.2.23版本,
HookMsg后,用Socket接收到的消息转换后有时乱码.
有的汉字能正常显示，有的汉字直接提示错误:No mapping for the Unicode character exists in the target multi-byte code page。
请问发送传过来的消息是GBK字符集吗？
能否说明下,谢谢。

**Comment by ttttupup** [comment]
utf8
