### ISSUE TITLE
崩溃详情

### ISSUE THREAD

**Issue by 10531515** [ttttupup/wxhelper#127]
测试了几天，好像终于抓到一次比较明显的崩溃点。
好像是这个函数里边调用的LOG(INFO)引起的。
void SendSocketMessage(InnerMessageStruct *msg)
崩溃断点断在easylogging++.cc文件中的第2243行，如下函数中：
void DefaultLogDispatchCallback::dispatch(base::type::string_t&& logLine) 
奇怪的是，这个easylogging++应该是个成熟的库，不应该会崩吧？压缩包里边崩溃的内存dump文件，以及pdb文件等。

**Comment by 10531515** [comment]
[wxhelper_bug.zip](https://github.com/ttttupup/wxhelper/files/11426788/wxhelper_bug.zip)

**Comment by 10531515** [comment]
有没有可能，是OnRecvMsg()函数引起的，函数本身没问题，但因为没有加互斥，当有两条消息同时到达的时候，会造成OnRecvMsg函数内部因为调用的一些全局的变量。一个正在读，一个正在写。导致数据冲突？随后在SendSocketMessage中，彻底把堆栈搞乱，直接就在写日志文件的时候崩了？如果是这样的话，在OnRecvMsg()里边加个互斥会不会好点呢？

**Comment by 10531515** [comment]
或是干脆用try把onrecvmsg()包起来得了。或许也行。

**Comment by ttttupup** [comment]
堆栈信息里是这个LOG引起的，具体是什么原因，最近比较忙，没时间排查了。把这些日志输出的注释掉就行了。刚开始的3.9.2.26版本已经替换成spdlog了，正好也不用折腾这个easylogging++了

**Comment by ttttupup** [comment]
可以使用新版本，旧版本精力有限不维护了。
