### ISSUE TITLE
能否支持获取微信号？

### ISSUE THREAD

**Issue by zhiying8710** [ttttupup/wxhelper#129]
微信号应该是能获取的吧， 如果用户设置了的话
包括好友和群成员的微信号
目前我在用的一个dll支持获取好友和群成员的详情， 包括昵称头像微信号等等
如果有必要我给提供源码

**Comment by ttttupup** [comment]
Contact表里啥都有

**Comment by zhiying8710** [comment]
Contact表里没有群成员的微信号, 我目前用的dll是支持3.0.0.57版本的微信, 在点击群成员头像的时候, 微信会查询群成员的详情, 包括头像微信号等等, dll对这个操作做了封装
