### ISSUE TITLE
HOOK 消息 能否增加一个 转发到 HTTP API

### ISSUE THREAD

**Issue by 502647092** [ttttupup/wxhelper#132]
现在的消息发送是直接发送消息内容
无法用 HTTP API 接受
还需要一个中转才行
希望可以加一个参数
直接请求 HTTP API

**Comment by 502647092** [comment]
不知道c++请求https和http是否一样 最好都能支持

**Comment by ttttupup** [comment]
暂时没考虑使用http 和https
