### ISSUE TITLE
使用代码启动微信 再注入 无法根据config.ini文件指定端口

### ISSUE THREAD

**Issue by Xxm-YX** [ttttupup/wxhelper#134]
使用最新版的3.9.2.23-V7版本，鼠标点击启动微信是可以根据config.ini 指定端口号，用python和java代码启动 再注入则无法指定，只能使用默认端口 19088

**Comment by ttttupup** [comment]
配置文件要放到WeChate.exe 的目录下，你用代码启动的话，看一下应用的目录。

**Comment by Xxm-YX** [comment]
感谢大佬回复，我这边是将Config.ini放在了WeChat.exe目录下，早上做了几轮测试，唯一不同点就是 通过代码 和 通过鼠标点击启动微信，注入的命令都是相同的，只是pid不相同，大佬有时间可以试一下，确实是没有指定端口号
![image](https://github.com/ttttupup/wxhelper/assets/61789235/1345339c-4579-4766-a528-8529821ced16)

**Comment by Xxm-YX** [comment]
python代码如下 
```
import subprocess
import os

# 获取微信可执行文件路径
wechat_path = "F:\wx\WeChat\WeChat.exe"

# 启动微信
subprocess.Popen([wechat_path])
```

**Comment by ttttupup** [comment]
直接系统目录，简单粗暴

**Comment by Xxm-YX** [comment]
还是不行，我已经在C:\Windows C:\Windows\System32 都放了config.ini，测了几遍，大佬如果有时间的话 要不试试看

**Comment by Xxm-YX** [comment]
已解决，将Config.ini放到调用注入的目录下即可
