### ISSUE TITLE
请求接口后整个微信卡住

### ISSUE THREAD

**Issue by zhiying8710** [ttttupup/wxhelper#135]
我测试过程中发现, 刚启动微信, 还没有完全登录(微信有些进程还没启动), 此时注入, 然后去请求接口, 微信进程就会整个卡住
dll使用的3.9.2.23-V7
等了几分钟, 也没崩溃日志, 进程也没反应, 现在在我机器上必现
前天本来一切正常, 请求hook消息日志也出现了同样情况

**Comment by zhiying8710** [comment]
现在通过微信pid来获取它的三个子进程(WeChatOCR.exe, WeChatPlayer.exe, WeChatUtility.exe)是否启动来判断微信是否已登录, 登录后再注入

**Comment by ttttupup** [comment]
文档已经说过，需要登录后再注入，未登录的话有很多接口是不能用的

**Comment by zhiying8710** [comment]
好的, 谢谢, 是我不认真看文档
