### ISSUE TITLE
常用设备登录 能否加一下方法 用来点击登录按钮

### ISSUE THREAD

**Issue by 502647092** [ttttupup/wxhelper#137]
在常用设备 可以直接点击登录按钮登录 不需要再次扫码
当进程崩溃时 可以实现自动恢复

**Comment by 502647092** [comment]
> 这种要恢复只能靠另一个进程了，注入dll实现不了

是的 但是我把微信和dll打包到docker了 可以自动注入 进程退出也会拉起来再次注入
大改就是 两个接口 一个判断状态
1. 需要二维码
2. 可以直接登录
如果直接登录就调用另一个接口 点击登录

**Comment by thinker007** [comment]
> 502647092

我也在寻找docker中打包运行的方案，可否分享一二呢？

**Comment by sayue2019** [comment]
> > 502647092
> 
> 我也在寻找docker中打包运行的方案，可否分享一二呢？

https://github.com/sayue2019/wechat-service-allin
