### ISSUE TITLE
微信3.9.2.23  -v7版本 通过好友请求不成功

### ISSUE THREAD

**Issue by sglmsn** [ttttupup/wxhelper#139]
win10环境
调用接口报:
{"msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}

原始请求为
http://127.0.0.1:19088/api/?type=23

{"v3":"v3_020b3826fd030100000000009fd5196d2b7f14000000501ea9a3dba12f95f6b60a0536a1adb6222623e1e7bc2246f8247bfc11cf3782df013caece773e96e9b39159c944356a6b6f5a1eed71f349337abd60ec5ff3f4b3f95c0ede21f9d04e9d0d20@stranger","v4":"v4_000b708f0b04000001000000000071fee8369d36bdf41ef650b66e641000000050ded0b020927e3c97896a09d47e6e9e399d1f44b91255e4f4597ab1a0986724f0c8dc080e26543afb4a0d4750d5d38050308be272dd4bb725838e61267c9c1a751d3748ff5ed5d71ab3293e5b41d65a9830780e7ca2632c50b7726e6cf3dc35b1d4a0fabf02c5870c063c33a388d1d941dbbf1af6ba4748@stranger"}

**Comment by hsmustard** [comment]
兄弟，少了个type
![image](https://github.com/ttttupup/wxhelper/assets/40329444/4bf27548-380f-406b-b0e9-8c0725d92075)

**Comment by sglmsn** [comment]
> 兄弟，少了一个类型 ![图像](https://user-images.githubusercontent.com/40329444/240776801-4bf27548-380f-406b-b0e9-8c0725d92075.png)

谢谢, 我是参照最新版文档来的,没注意到这个type...

**Comment by sglmsn** [comment]
> 兄弟，少了个type ![image](https://user-images.githubusercontent.com/40329444/240776801-4bf27548-380f-406b-b0e9-8c0725d92075.png)

...我刚刚试了下, 仍然报错,
请求参数为:
http://127.0.0.1:19088/api/?type=23
{
    
    "v3":"v3_020b3826fd030100000000009fd5196d2b7f14000000501ea9a3dba12f95f6b60a0536a1adb6222623e1e7bc2246f8247bfc11cf3782df013caece773e96e9b39159c944356a6b6f5a1eed71f349337abd60ec5ff3f4b3f95c0ede21f9d04e9d0d20@stranger",
    "v4":"v4_000b708f0b04000001000000000071fee8369d36bdf41ef650b66e641000000050ded0b020927e3c97896a09d47e6e9e399d1f44b91255e4f4597ab1a0986724f0c8dc080e26543afb4a0d4750d5d38050308be272dd4bb725838e61267c9c1a751d3748ff5ed5d71ab3293e5b41d65a9830780e7ca2632c50b7726e6cf3dc35b1d4a0fabf02c5870c063c33a388d1d941dbbf1af6ba4748@stranger",
    "type":"8"
}

{
    "msg": "[json.exception.type_error.302] type must be string, but is null",
    "result": "ERROR"
}

**Comment by 502647092** [comment]
这个错误 都是请求结构的 JSON 有问题
通过好友接口没问题的 我一直在用

**Comment by 502647092** [comment]
emmm 新版本的参数 应该是 "permission"
```
POST /api/?type=23

{
    "v3": "v3@stranger",
    "v4": "v4@stranger",
    "permission": 0
}
```

**Comment by sglmsn** [comment]
> emmm 新版本的参数 应该是 "permission"
> 
> ```
> POST /api/?type=23
> 
> {
>     "v3": "v3@stranger",
>     "v4": "v4@stranger",
>     "permission": 0
> }
> ```

这个可以了, 谢谢 ,我刚刚看了下v3的源码, 但是也没找到这个参数==.

**Comment by 502647092** [comment]
分支 dev-3.9.2.23
https://github.com/ttttupup/wxhelper/blob/83d779c07246e93e1b4a114bf50c22ca95ab640a/src/http_handler.cc#L252-L260
