### ISSUE TITLE
增加向好友发送群聊邀请确认

### ISSUE THREAD

**Issue by Don5211314** [ttttupup/wxhelper#143]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Don5211314** [comment]
希望能对于人数较多的群聊实现增加群成员的功能，场景为人数较多的群聊邀请好友会触发确认，点击确认会向好友发送群聊邀请通知。还有一种情况是群聊人数已满，希望能对应解决一下这个需求

**Comment by ttttupup** [comment]
个人暂时没有这种群，没法调试。

**Comment by ttttupup** [comment]
40人的话，还是有的，有时间了看一下

**Comment by Don5211314** [comment]
> 40人的话，还是有的，有时间了看一下

好的 感谢 这个如果可能的情况下能优先处理一下吗？  我个人比较急，之前这个功能我是用类似于按键精灵的方式来实现但是出了问题。。。

**Comment by ttttupup** [comment]
开源的，就是看个人时间安排。如果比较急用，也有类似实现的开源库，你可以搜搜。python版的

**Comment by lanlandexiaolan** [comment]
同求这个，老方便啦
