### ISSUE TITLE
3.9.2.23版本运行崩溃

### ISSUE THREAD

**Issue by Xxm-YX** [ttttupup/wxhelper#144]
version: 3.9.2.23-V7

[WeChat24cc864.txt](https://github.com/ttttupup/wxhelper/files/11574302/WeChat24cc864.txt)
[WeChat24cc864FMD5.txt](https://github.com/ttttupup/wxhelper/files/11574306/WeChat24cc864FMD5.txt)
dmp文件无法上传，不知道大佬是否需要

期间做的操作：HOOK消息，接收了几条消息，过了几个小时突然就会崩溃掉

**Comment by ttttupup** [comment]
可能是日志，试试2.26的

**Comment by Xxm-YX** [comment]
好的

**Comment by Xxm-YX** [comment]
> 可能是日志，试试2.26的

想请教一下，2.26的版本 哪有下载的阿，我看官方都是2.23的版本

**Comment by ttttupup** [comment]
不知道，是2.23版本提示更新，就升级了。也有可能是灰度上线的版本

**Comment by 502647092** [comment]
有一种情况 就是 HTTP接收端 没有关闭连接 然后会一直占用 然后Boom 我之前用Golang转发遇到过 收完消息就关闭连接 应该不会出现了
