### ISSUE TITLE
请问能拿到入群消息事件吗，有入群提示语和欢迎语需求。

### ISSUE THREAD

**Issue by acornlive** [ttttupup/wxhelper#147]
能拿到入群事件的话设置入群欢迎语和发送消息提示之类的。

**Comment by ttttupup** [comment]
hook 消息里可以根据消息类型区分，具体是什么值没仔细看过。

**Comment by 502647092** [comment]
看了一下 wechaty 的逻辑 他是判断系统消息的
1. 先记录群wxids
2. 检测到入群信息
3. 再次获取群wxids
4. 对比差异 获取入群的wxids

第二步可以通过 type == 10000 的消息 用正则匹配content
```
const YOU_INVITE_OTHER_REGEX_LIST = [
  /^你邀请"(.+)"加入了群聊 {2}/,
  /^You invited (.+) to the group chat/,
]
const OTHER_INVITE_YOU_REGEX_LIST = [
  /^"([^"]+?)"邀请你加入了群聊，群聊参与人还有：(.+)/,
  /^(.+) invited you to a group chat with (.+)/,
]
const OTHER_INVITE_YOU_AND_OTHER_REGEX_LIST = [
  /^"([^"]+?)"邀请你和"(.+?)"加入了群聊/,
  /^(.+?) invited you and (.+?) to (the|a) group chat/,
]
const OTHER_INVITE_OTHER_REGEX_LIST = [
  /^"(.+)"邀请"(.+)"加入了群聊/,
  /^(.+?) invited (.+?) to (the|a) group chat/,
]
const OTHER_JOIN_VIA_YOUR_QRCODE_REGEX_LIST = [
  /^" ?(.+)"通过扫描你分享的二维码加入群聊/,
  /^" ?(.+)" joined group chat via the QR code you shared/,
]
const OTHER_JOIN_VIA_OTHER_QRCODE_REGEX_LIST = [
  /^" (.+)"通过扫描"(.+)"分享的二维码加入群聊/,
  /^"(.+)" joined the group chat via the QR Code shared by "(.+)"/,
]
```

**Comment by ttttupup** [comment]
> 看了一下 wechaty 的逻辑 他是判断系统消息的
> 
> 1. 先记录群wxids
> 2. 检测到入群信息
> 3. 再次获取群wxids
> 4. 对比差异 获取入群的wxids
> 
> 第二步可以通过 type == 10000 的消息 用正则匹配content
> 
> ```
> const YOU_INVITE_OTHER_REGEX_LIST = [
>   /^你邀请"(.+)"加入了群聊 {2}/,
>   /^You invited (.+) to the group chat/,
> ]
> const OTHER_INVITE_YOU_REGEX_LIST = [
>   /^"([^"]+?)"邀请你加入了群聊，群聊参与人还有：(.+)/,
>   /^(.+) invited you to a group chat with (.+)/,
> ]
> const OTHER_INVITE_YOU_AND_OTHER_REGEX_LIST = [
>   /^"([^"]+?)"邀请你和"(.+?)"加入了群聊/,
>   /^(.+?) invited you and (.+?) to (the|a) group chat/,
> ]
> const OTHER_INVITE_OTHER_REGEX_LIST = [
>   /^"(.+)"邀请"(.+)"加入了群聊/,
>   /^(.+?) invited (.+?) to (the|a) group chat/,
> ]
> const OTHER_JOIN_VIA_YOUR_QRCODE_REGEX_LIST = [
>   /^" ?(.+)"通过扫描你分享的二维码加入群聊/,
>   /^" ?(.+)" joined group chat via the QR code you shared/,
> ]
> const OTHER_JOIN_VIA_OTHER_QRCODE_REGEX_LIST = [
>   /^" (.+)"通过扫描"(.+)"分享的二维码加入群聊/,
>   /^"(.+)" joined the group chat via the QR Code shared by "(.+)"/,
> ]
> ```

这个客户端就可以做，收到消息后调用群成员接口，与之前的群成员比对就知道，新增和减少的成员了
