### ISSUE TITLE
通过wxid添加好友接口失效(严谨测试确定过了)@@!!!

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#148]
大神应该是微信号不多,直接借鉴以前的接口,现在失效了,只能添加您以前添加过然后删除的好友!
我估计测试的时候也是把好友删除了又重新添加的,或者直接就是添加本来就是好友的wxid.
但是我测试很多次,完全陌生人以前没有添加过的,发送请求后对方就完全收不到请求!

**Comment by qwe159357890** [comment]
使用的是:[3.9.2.23-V7]

**Comment by ttttupup** [comment]
那这个没法复现了

**Comment by qwe159357890** [comment]
随便添加个您没加过的就可以啊,可以加我wxid_qsd86tee7kj022

**Comment by qwe159357890** [comment]
这个功能真心好用,盼大佬有空更新!
