### ISSUE TITLE
希望可以更新一下 3.9.2.23 的 dll 因为3.9.2.26没有直装的安装包

### ISSUE THREAD

**Issue by 502647092** [ttttupup/wxhelper#151]
从官网下载的 目前只有 3.9.2.23
目测 3.9.2.26 是补丁更新上去的

自己尝试了一下 太菜了 没办法把26的迁移到23

**Comment by ttttupup** [comment]
[WeChatWin.zip](https://github.com/ttttupup/wxhelper/files/11597833/WeChatWin.zip)

**Comment by degangliu** [comment]
> [WeChatWin.zip](https://github.com/ttttupup/wxhelper/files/11597833/WeChatWin.zip)

这个直接复制到安装目录 报微信环境异常  启动不了微信

**Comment by degangliu** [comment]
> [WeChatWin.zip](https://github.com/ttttupup/wxhelper/files/11597833/WeChatWin.zip)

强烈建议 在3.9.2.23上稳定推进新功能哈。 3.9.2.26查了半天没找到。。。

**Comment by ttttupup** [comment]
关键是我要是降版本了就回不来了

**Comment by degangliu** [comment]
> 来了
要不您帮忙把c盘微信所有安装文件打包发一下我们看看能用不大佬

**Comment by qwe159357890** [comment]
链接:https://caiyun.139.com/m/i?0A5Cte3EuQCJe
提取码:KfgR
复制内容打开移动云盘PC客户端，操作更方便哦

**Comment by degangliu** [comment]
> 链接:https://caiyun.139.com/m/i?0A5Cte3EuQCJe 提取码:KfgR 复制内容打开移动云盘PC客户端，操作更方便哦

感谢 能用

**Comment by ruocaoqing** [comment]
> > 链接:https://caiyun.139.com/m/i?0A5Cte3EuQCJe 提取码:KfgR 复制内容打开移动云盘PC客户端，操作更方便哦
> 
> 感谢 能用

能给我一份吗？给个百度网盘链接

**Comment by 254896769** [comment]
> 链接:https://caiyun.139.com/m/i?0A5Cte3EuQCJe 提取码:KfgR 复制内容打开移动云盘PC客户端，操作更方便哦

链接失效了，能给个百度网盘的链接吗？

**Comment by SymlonCheung** [comment]
> > 链接：[https](https://caiyun.139.com/m/i?0A5Cte3EuQCJe) ://caiyun.139.com/m/i ?0A5Cte3EuQCJe 提取码:KfgR 复制内容打开移动云盘PC客户端，操作更方便哦
> 
> 链接失效了，能给一个百度网盘的链接吗？

+1

**Comment by qwe159357890** [comment]
我又发了一遍,可以关闭了链接:https://caiyun.139.com/m/i?0A5Ctd9aQlbpi
提取码:04gh
复制内容打开移动云盘PC客户端，操作更方便哦

**Comment by a812086325** [comment]
> 我又发了一遍,可以关闭了链接: [https://caiyun.139.com/m/i?0A5Ctd9aQlbpi ](https://caiyun.139.com/m/i?0A5Ctd9aQlbpi) 提取码:04gh 复制内容打开移动云盘PC客户端，操作更方便哦

链接失效了，能在发一次么，感谢
