### ISSUE TITLE
dev-3.9.2.26 分支中的tool/ConsoleInject.exe 无法多开

### ISSUE THREAD

**Issue by Xxm-YX** [ttttupup/wxhelper#152]
![image](https://github.com/ttttupup/wxhelper/assets/61789235/80ab6eb9-dac0-407e-883a-707f98ab2371)
大佬抽空看看

**Comment by ttttupup** [comment]
这个就是命令解析异常了，仔细检查输入的是不是正确的参数。这个有源码，自己debug一下就知道了。
