### ISSUE TITLE
无法注入

### ISSUE THREAD

**Issue by ruocaoqing** [ttttupup/wxhelper#156]
![image](https://github.com/ttttupup/wxhelper/assets/30763770/c76c8d20-c96f-49ef-abfc-6ecc74d9bbf1)
我这样操作后，发现啥反应都没有。127.0.0.1:19088 也调不通

**Comment by ttttupup** [comment]
自己编译一下

**Comment by degangliu** [comment]
> 自己编译一下

spdlog::daily_logger_mt("daily_logger", "daily.txt", 23, 59);

我也注入失败，发现是spdlog这里异常，具体原因不明；

它也安装了 不知道为啥就是这里抛异常

**Comment by ttttupup** [comment]
检查一下权限

**Comment by ruocaoqing** [comment]
> 自己编译一下

我没有编译环境。大佬能否编译一下，更新一下dll

**Comment by ttttupup** [comment]
> > 自己编译一下
> 
> 我没有编译环境。大佬能否编译一下，更新一下dll

3.9.2.26  /tool 目录下有编译好的

**Comment by qiaosou** [comment]
我2.26也是注入不成功，19088端口一直没有

**Comment by qiaosou** [comment]
![微信图片_20230601100944](https://github.com/ttttupup/wxhelper/assets/16679993/0e1f7113-75c8-4a96-ba56-ec6217f3c181)

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/discussions/65

**Comment by qiaosou** [comment]
> #65

尝试了，报错

D:\4K>tasklist | findstr WeChat.exe
WeChat.exe                    8668 Console                    1    248,468 K

D:\4K>ConsoleInject.exe -I 8668 -p d:/4K/wxhelper.dll
Unknown option character `\x49'.

D:\4K>ConsoleInject.exe -I 8668 -p d:\4K\wxhelper.dll
Unknown option character `\x49'.

公司这边没有编译环境，原来用的0.28

**Comment by degangliu** [comment]
> 检查一下权限

他这个日志 默认是写在注入程序的执行目录，还是微信的根目录 还是某个目录？

调试有点麻烦  不知道怎么输出结果到终端

**Comment by ttttupup** [comment]
> > 检查一下权限
> 
> 他这个日志 默认是写在注入程序的执行目录，还是微信的根目录 还是某个目录？
> 
> 调试有点麻烦 不知道怎么输出结果到终端

wechat的安装目录

**Comment by ttttupup** [comment]
> D:\4K>ConsoleInject.exe -I 8668 -p d:\4K\wxhelper.dll

这个是命令输入的有问题

**Comment by qiaosou** [comment]
> 
找到问题了，我这里直接启动微信2.26目录下的wechat.exe就可以注入，拷贝到外一层启动还是2.26就没法注入，不知道什么原因，因为不是正规升级上来的，呵呵，感谢作者

**Comment by degangliu** [comment]
> > 
> 
> 找到问题了，我这里直接启动微信2.26目录下的wechat.exe就可以注入，拷贝到外一层启动还是2.26就没法注入，不知道什么原因，因为不是正规升级上来的，呵呵，感谢作者

我回去也试试 居然还有这个坑

**Comment by ruocaoqing** [comment]
我还没注入成功，也不知道是微信版本的问题，还是注入程序版本有问题，也不知道去哪儿看日志

**Comment by degangliu** [comment]
> 我还没注入成功，也不知道是微信版本的问题，还是注入程序版本有问题，也不知道去哪儿看日志

用管理员身份运行微信和注入程序  

微信也得管理员身份运行 不然那个日志写不进去我靠

**Comment by ruocaoqing** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/30763770/da8e6517-92be-4c8d-b487-057a61c0662a)
这提示不是注入成功了吗，为啥接口调不通呢？

**Comment by ttttupup** [comment]
> ![image](https://user-images.githubusercontent.com/30763770/242610005-da8e6517-92be-4c8d-b487-057a61c0662a.png) 这提示不是注入成功了吗，为啥接口调不通呢？

微信版本要对应

**Comment by ruocaoqing** [comment]
> 

哪里去找3.9.2.26版本的微信呢？我这更新到最新的也才3.9.2.23

**Comment by ttttupup** [comment]
有人发过 ，在issue里找找

**Comment by lifeofwind** [comment]
> ![image](https://user-images.githubusercontent.com/30763770/242369491-c76c8d20-c96f-49ef-abfc-6ecc74d9bbf1.png) 我这样操作后，发现啥反应都没有。127.0.0.1:19088 也调不通

1.管理员命令运行CMD
2.注入dll是wxhelper.dll 不是injector.dll 此DLL是注入器自己的
3.注入器小BUG，需要全路径，不能识别和自行拼接命令行当前路径

// 注入并指定http端口，该命令需要搭配带有specify-port 后缀的dll使用。
ConsoleInject.exe -i demo.exe -p E:\yourDllFullPath.dll -P 18888

注意这行：yourDllFullPath 需要全路径，不能 ./xxx.dll  , xxx.dll 需要 E:\XXX\xx.dll 带磁盘的全路径
上述不一定正确，本人仅按此法排查后能成功开启访问端口。

**Comment by ruocaoqing** [comment]
> > ![image](https://user-images.githubusercontent.com/30763770/242369491-c76c8d20-c96f-49ef-abfc-6ecc74d9bbf1.png) 我这样操作后，发现啥反应都没有。127.0.0.1:19088 也调不通
> 
> 1.管理员命令运行CMD 2.注入dll是wxhelper.dll 不是injector.dll 此DLL是注入器自己的 3.注入器小BUG，需要全路径，不能识别和自行拼接命令行当前路径
> 
> // 注入并指定http端口，该命令需要搭配带有specify-port 后缀的dll使用。 ConsoleInject.exe -i demo.exe -p E:\yourDllFullPath.dll -P 18888
> 
> 注意这行：yourDllFullPath 需要全路径，不能 ./xxx.dll , xxx.dll 需要 E:\XXX\xx.dll 带磁盘的全路径 上述不一定正确，本人仅按此法排查后能成功开启访问端口。

你用的微信是哪个版本的？我这边没有环境，无法自己编译。能否把你编译好的 dll 发我一份？给我百度网盘链接？

**Comment by lifeofwind** [comment]
> > > ![image](https://user-images.githubusercontent.com/30763770/242369491-c76c8d20-c96f-49ef-abfc-6ecc74d9bbf1.png) 我这样操作后，发现啥反应都没有。127.0.0.1:19088 也调不通
> > 
> > 
> > 1.管理员命令运行CMD 2.注入dll是wxhelper.dll 不是injector.dll 此DLL是注入器自己的 3.注入器小BUG，需要全路径，不能识别和自行拼接命令行当前路径
> > // 注入并指定http端口，该命令需要搭配带有specify-port 后缀的dll使用。 ConsoleInject.exe -i demo.exe -p E:\yourDllFullPath.dll -P 18888
> > 注意这行：yourDllFullPath 需要全路径，不能 ./xxx.dll , xxx.dll 需要 E:\XXX\xx.dll 带磁盘的全路径 上述不一定正确，本人仅按此法排查后能成功开启访问端口。
> 
> 你用的微信是哪个版本的？我这边没有环境，无法自己编译。能否把你编译好的 dll 发我一份？给我百度网盘链接？

java 目录下自己带有dll，不需要编译，版本是最新版微信，3.9.2.23

C:\Users\Administrator>netstat -an | findstr "190"
  TCP    0.0.0.0:19088          0.0.0.0:0              LISTENING
