### ISSUE TITLE
请问解密数据库decrypt.py文件的password如何获取?

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#159]
因为接口 32.获取数据库句柄 得到的句柄只有一部分数据库的,比如FTSContact.db这个数据库句柄就没有.
所以如果想解密其他数据库应该如何做?

**Comment by ttttupup** [comment]
接口1返回

**Comment by qwe159357890** [comment]
谢谢大佬@ 是不是这东西不能弄群? 有个群大佬们就可以方便指点了
