### ISSUE TITLE
发送小程序，能否实现呢？

### ISSUE THREAD

**Issue by luochaolun** [ttttupup/wxhelper#16]
发送小程序能否实现呢，哪个com开头的项目里，发送小程序里不能设置标题、链接、图片，感觉作用不大，能否增加发送小程序的功能？

**Comment by luochaolun** [comment]
com项目发出来的小程序是下边这样的
![Uploading Screenshot_20230207_135159.jpg…]()
正常的是下边这样的
![Uploading Screenshot_20230207_135129.jpg…]()

**Comment by ttttupup** [comment]
这个有时间了可以实现一下

**Comment by luochaolun** [comment]
厉害，无所不能的大佬，赞👍
