### ISSUE TITLE
WECHAT_GET_MEMBER_PROFILE这个接口获取群成员取不到头像信息

### ISSUE THREAD

**Issue by degangliu** [ttttupup/wxhelper#161]
第一次获取取不到头像信息
在微信里面点击一下头像查看之后 第二次获取才能渠道头像信息

**Comment by degangliu** [comment]
> 到。

他那个刷新点击一下用户头像能查到
能把刷新头像这个动作hook一把不？

**Comment by ttttupup** [comment]
这个接口就是

**Comment by degangliu** [comment]
> 这个接口就是

那很奇怪。。。
正常在微信里面手动刷新一下头像   用这个接口获取能显示头像图片

直接用这个接口显示不了

**Comment by ttttupup** [comment]
这个接口应该是少了网络下载头像的功能，懒的看了

**Comment by degangliu** [comment]
> 这个接口应该是少了网络下载头像的功能，懒的看了

兄弟研究研究呗

**Comment by degangliu** [comment]
看到有查询下载头像的接口了 我试试

**Comment by qwe159357890** [comment]
请问大佬们 实现模拟手动更新头像了吗?这个接口很有用,模仿微信界面需要显示头像,但是很多以前老朋友没联系过的,头像地址就失效

**Comment by degangliu** [comment]
> 请问大佬们 实现模拟手动更新头像了吗?这个接口很有用,模仿微信界面需要显示头像,但是很多以前老朋友没联系过的,头像地址就失效

似乎没有实现呢

**Comment by ttttupup** [comment]
头像本地数据库查就行了，原始数据，不会存在失效的情况
