### ISSUE TITLE
按 手机号 搜索用户时[SearchContact], 当 用户不存在 , 需要 返回 微信搜索界面显示的 无法找到该用户,请检查你的输入 .

### ISSUE THREAD

**Issue by okeywh** [ttttupup/wxhelper#163]
**Describe the bug**
按 手机号 搜索用户时[SearchContact], 当 用户不存在 , 需要 返回 微信搜索界面显示的 无法找到该用户,请检查你的输入 .
目前的 版本 errcode 返回了1 ,errtext 没有错误信息, 但是返回的 用户信息 为空.
**To Reproduce**
1\点击通讯录,
2\点击 添加朋友 按钮
3\输入 手机号 点击搜索
4\ 手机号不存在时,界面显示 无法找到该用户,请检查你的输入.

**Expected behavior**
 errcode 返回了-1 ,errtext  返回  无法找到该用户,请检查你的输入 .

**Comment by ttttupup** [comment]
这个感觉没那个必要。

**Comment by okeywh** [comment]
搜索用户属于产品的基础功能，这种bug 不应存在
