### ISSUE TITLE
跪请大佬:增加一个hook发送消息接口!

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#166]
现在的hook消息,只能hook收到的消息和手机端发出的消息,电脑端发出的都没有,
跪请大佬增加个hook电脑端发送消息接口!再次感谢!

**Comment by ttttupup** [comment]
肝不动了

**Comment by qwe159357890** [comment]
嗯嗯  先报个到,等大佬有空给实现下

**Comment by ruocaoqing** [comment]
是的，我之前用另外一个wx hook库，也是没有电脑端的消息

**Comment by qwe159357890** [comment]
发送消息也很有用,只是不知道大佬有没有空实现

**Comment by DevilStarMod** [comment]
想用一下撤回消息，发现没有hook发送的消息，怎么获取消息id呢/(ㄒoㄒ)/~~

**Comment by qwe159357890** [comment]
手机端发送的消息是有的,希望大佬有空增加个电脑端发送消息
