### ISSUE TITLE
希望增加对小程序hook的支持

### ISSUE THREAD

**Issue by m2kar** [ttttupup/wxhelper#167]
希望能深入在小程序逆向方面的支持，比如能对小程序提供类似chrome控制台类似的调试窗口

**Comment by ttttupup** [comment]
这个搞不了

**Comment by m2kar** [comment]
> 这个搞不了

那其他对小程序的支持大佬有兴趣研究吗？ 比如快速的逆向、hook之类的。

**Comment by ttttupup** [comment]
小程序解完包就和普通的前端项目没什么区别了。工具什么的太多了。
