### ISSUE TITLE
注入DLL有2个不知道算不算BUG的地方~

### ISSUE THREAD

**Issue by lifeofwind** [ttttupup/wxhelper#170]
1.DLL建立主动调用TCP链接，会一直维持多个链接，不释放，占用系统端口资源。

  TCP    0.0.0.0:19088          0.0.0.0:0              LISTENING       9208
  TCP    0.0.0.0:19099          0.0.0.0:0              LISTENING       7812
  TCP    192.168.31.241:19099   192.168.31.241:55378   ESTABLISHED     7812
  TCP    192.168.31.241:19099   192.168.31.241:55379   ESTABLISHED     7812
  TCP    192.168.31.241:55378   192.168.31.241:19099   ESTABLISHED     9208
  TCP    192.168.31.241:55379   192.168.31.241:19099   ESTABLISHED     9208

2.DLL 不能识别 127.0.0.1 或者 localhost 本地环回端口访问，如果这样写，通过api提交给DLL调用，DLL会调用不到，Netty服务的不会有任何输出，只有写成独立内网IP才可以调用得到，不知道是不是个案。

另：不知道楼主 3.9.2.26 的PC端wx在哪下下载，全网都是 3.9.2.23 版本的

**Comment by sglmsn** [comment]
127 是支持的, localhost 貌似不行,

**Comment by ttttupup** [comment]
http 服务端是不会主动断开连接，客户端断开会自动断开。tcp的客户端会主动断开连接。另外不支持dns。
