### ISSUE TITLE
解密动态表情

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#174]
https://blog.csdn.net/qq_43572067/article/details/100062493

**Comment by qwe159357890** [comment]
看到一个很久前文章,详细讲解了2.6版微信解密动态表情的,大佬有空看下不知道现在还可以不可以实现,辛苦了!

**Comment by ttttupup** [comment]
你这是要发送表情，还是要解密存储表情

**Comment by qwe159357890** [comment]
您好大佬,是期望收到动态表情就解密成动图或者哪怕截取一张静态图片也可以.现在收到动态表情type=47是下面这种 格式:

**Comment by qwe159357890** [comment]
{
    'content': '<msg><emoji fromusername = "h525307431" tousername = "wxid_xlgr7yfymdio22" type="2" idbuffer="media:0_0" md5="ad32701e09158dd527799a75679604cf" len = "938936" productid="" androidmd5="ad32701e09158dd527799a75679604cf" androidlen="938936" s60v3md5 = "ad32701e09158dd527799a75679604cf" s60v3len="938936" s60v5md5 = "ad32701e09158dd527799a75679604cf" s60v5len="938936" cdnurl = "http://vweixinf.tc.qq.com/110/20401/stodownload?m=ad32701e09158dd527799a75679604cf&amp;filekey=30440201010430302e02016e040253480420616433323730316530393135386464353237373939613735363739363034636602030e53b8040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303031663038393436613930363739323836366234306230303030303036653031303034666231&amp;ef=1&amp;bizid=1022" designerid = "" thumburl = "" encrypturl = "http://vweixinf.tc.qq.com/110/20402/stodownload?m=e6d6f62aea1168d55ddf21cf8900933e&amp;filekey=30440201010430302e02016e040253480420653664366636326165613131363864353564646632316366383930303933336502030e53c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303036326435663436613930363739323836366234306230303030303036653032303034666232&amp;ef=2&amp;bizid=1022" aeskey= "345871b7893a4b4ba7a7ddd1f6991ca3" externurl = "http://vweixinf.tc.qq.com/110/20403/stodownload?m=3c2973bf0fe07dd4e9c65e5878208676&amp;filekey=30440201010430302e02016e040253480420336332393733626630666530376464346539633635653538373832303836373602030368c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303039663932303436613930363739323836366234306230303030303036653033303034666233&amp;ef=3&amp;bizid=1022" externmd5 = "3cada50f5be65e8f13ef3106593d2fa9" width= "240" height= "240" tpurl= "" tpauthkey= "" attachedtext= "" attachedtextcolor= "" lensid= "" emojiattr= "" linkid= "" desc= "" ></emoji> </msg>',
    'fromGroup': '', 'fromUser': '', 'isSendMsg': 0, 'msgId': 8109868769130662147,
    'path': 'AD32701E09158DD527799A75679604CF', 'pid': 12876, 'time': '2023-06-07 07:37:51', 'timestamp': 1686094671,
    'type': 47}

**Comment by qwe159357890** [comment]
{
    'content': '<msg><emoji fromusername = "h525307431" tousername = "wxid_xlgr7yfymdio22" type="2" idbuffer="media:0_0" md5="ad32701e09158dd527799a75679604cf" len = "938936" productid="" androidmd5="ad32701e09158dd527799a75679604cf" androidlen="938936" s60v3md5 = "ad32701e09158dd527799a75679604cf" s60v3len="938936" s60v5md5 = "ad32701e09158dd527799a75679604cf" s60v5len="938936" cdnurl = "http://vweixinf.tc.qq.com/110/20401/stodownload?m=ad32701e09158dd527799a75679604cf&amp;filekey=30440201010430302e02016e040253480420616433323730316530393135386464353237373939613735363739363034636602030e53b8040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303031663038393436613930363739323836366234306230303030303036653031303034666231&amp;ef=1&amp;bizid=1022" designerid = "" thumburl = "" encrypturl = "http://vweixinf.tc.qq.com/110/20402/stodownload?m=e6d6f62aea1168d55ddf21cf8900933e&amp;filekey=30440201010430302e02016e040253480420653664366636326165613131363864353564646632316366383930303933336502030e53c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303036326435663436613930363739323836366234306230303030303036653032303034666232&amp;ef=2&amp;bizid=1022" aeskey= "345871b7893a4b4ba7a7ddd1f6991ca3" externurl = "http://vweixinf.tc.qq.com/110/20403/stodownload?m=3c2973bf0fe07dd4e9c65e5878208676&amp;filekey=30440201010430302e02016e040253480420336332393733626630666530376464346539633635653538373832303836373602030368c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303039663932303436613930363739323836366234306230303030303036653033303034666233&amp;ef=3&amp;bizid=1022" externmd5 = "3cada50f5be65e8f13ef3106593d2fa9" width= "240" height= "240" tpurl= "" tpauthkey= "" attachedtext= "" attachedtextcolor= "" lensid= "" emojiattr= "" linkid= "" desc= "" ></emoji> </msg>',
    'fromGroup': '', 'fromUser': '', 'isSendMsg': 0, 'msgId': 8109868769130662147,
    'path': 'AD32701E09158DD527799A75679604CF', 'pid': 12876, 'time': '2023-06-07 07:37:51', 'timestamp': 1686094671,
    'type': 47}

**Comment by qwe159357890** [comment]
<msg><emoji fromusername = "" tousername = "" type="2" idbuffer="media:0_0" md5="ad32701e09158dd527799a75679604cf" len = "938936" productid="" androidmd5="ad32701e09158dd527799a75679604cf" androidlen="938936" s60v3md5 = "ad32701e09158dd527799a75679604cf" s60v3len="938936" s60v5md5 = "ad32701e09158dd527799a75679604cf" s60v5len="938936" cdnurl = "http://vweixinf.tc.qq.com/110/20401/stodownload?m=ad32701e09158dd527799a75679604cf&amp;filekey=30440201010430302e02016e040253480420616433323730316530393135386464353237373939613735363739363034636602030e53b8040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303031663038393436613930363739323836366234306230303030303036653031303034666231&amp;ef=1&amp;bizid=1022" designerid = "" thumburl = "" encrypturl = "http://vweixinf.tc.qq.com/110/20402/stodownload?m=e6d6f62aea1168d55ddf21cf8900933e&amp;filekey=30440201010430302e02016e040253480420653664366636326165613131363864353564646632316366383930303933336502030e53c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303036326435663436613930363739323836366234306230303030303036653032303034666232&amp;ef=2&amp;bizid=1022" aeskey= "345871b7893a4b4ba7a7ddd1f6991ca3" externurl = "http://vweixinf.tc.qq.com/110/20403/stodownload?m=3c2973bf0fe07dd4e9c65e5878208676&amp;filekey=30440201010430302e02016e040253480420336332393733626630666530376464346539633635653538373832303836373602030368c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303039663932303436613930363739323836366234306230303030303036653033303034666233&amp;ef=3&amp;bizid=1022" externmd5 = "3cada50f5be65e8f13ef3106593d2fa9" width= "240" height= "240" tpurl= "" tpauthkey= "" attachedtext= "" attachedtextcolor= "" lensid= "" emojiattr= "" linkid= "" desc= "" ></emoji> </msg>

**Comment by qwe159357890** [comment]
<msg><emoji fromusername = "" tousername = "" type="2" idbuffer="media:0_0" md5="ad32701e09158dd527799a75679604cf" len = "938936" productid="" androidmd5="ad32701e09158dd527799a75679604cf" androidlen="938936" s60v3md5 = "ad32701e09158dd527799a75679604cf" s60v3len="938936" s60v5md5 = "ad32701e09158dd527799a75679604cf" s60v5len="938936" cdnurl = "http://vweixinf.tc.qq.com/110/20401/stodownload?m=ad32701e09158dd527799a75679604cf&amp;filekey=30440201010430302e02016e040253480420616433323730316530393135386464353237373939613735363739363034636602030e53b8040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303031663038393436613930363739323836366234306230303030303036653031303034666231&amp;ef=1&amp;bizid=1022" designerid = "" thumburl = "" encrypturl = "http://vweixinf.tc.qq.com/110/20402/stodownload?m=e6d6f62aea1168d55ddf21cf8900933e&amp;filekey=30440201010430302e02016e040253480420653664366636326165613131363864353564646632316366383930303933336502030e53c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303036326435663436613930363739323836366234306230303030303036653032303034666232&amp;ef=2&amp;bizid=1022" aeskey= "345871b7893a4b4ba7a7ddd1f6991ca3" externurl = "http://vweixinf.tc.qq.com/110/20403/stodownload?m=3c2973bf0fe07dd4e9c65e5878208676&amp;filekey=30440201010430302e02016e040253480420336332393733626630666530376464346539633635653538373832303836373602030368c0040d00000004627466730000000131&amp;hy=SH&amp;storeid=323032313130303732333338343330303039663932303436613930363739323836366234306230303030303036653033303034666233&amp;ef=3&amp;bizid=1022" externmd5 = "3cada50f5be65e8f13ef3106593d2fa9" width= "240" height= "240" tpurl= "" tpauthkey= "" attachedtext= "" attachedtextcolor= "" lensid= "" emojiattr= "" linkid= "" desc= "" ></emoji> </msg>

**Comment by qwe159357890** [comment]
[新建文本文档 (2).txt](https://github.com/ttttupup/wxhelper/files/11671139/2.txt)

**Comment by ttttupup** [comment]
`
cdnurl 就是原文件，还解密什么

http://vweixinf.tc.qq.com/110/20401/stodownload?m=ad32701e09158dd527799a75679604cf&filekey=30440201010430302e02016e040253480420616433323730316530393135386464353237373939613735363739363034636602030e53b8040d00000004627466730000000131&hy=SH&storeid=323032313130303732333338343330303031663038393436613930363739323836366234306230303030303036653031303034666231&ef=1&bizid=1022
`

**Comment by ttttupup** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/31303661/86b6861b-1276-4faa-b39a-9196982ab35c)

**Comment by qwe159357890** [comment]
谢谢大佬,是我眼神不好,amp;符号都直接复制近浏览器了,再次感谢!
