### ISSUE TITLE
通过sql查询msg表，表里面的 StrTalker是微信群号，没有发送人的微信号

### ISSUE THREAD

**Issue by ruocaoqing** [ttttupup/wxhelper#182]
通过sql查询msg表，表里面的 StrTalker是微信群号，并没有发送人的微信号。想问一下怎么才能知道这个消息是哪个人发送的？需要通过哪个字段，关联查询哪张表？

**Comment by ttttupup** [comment]
bytesextra 里看看

**Comment by ruocaoqing** [comment]
> bytesextra 里看看

里面是加密的内容，这个怎么解密啊？

**Comment by ruocaoqing** [comment]
> bytesextra 里看看

解密后，确实有，谢谢

**Comment by ruocaoqing** [comment]
> bytesextra 里看看

解码之后，为啥有乱码？号
![image](https://github.com/ttttupup/wxhelper/assets/30763770/633a941c-1f57-45b6-8e5c-1d8ce388f30f)
这个怎么解决？

**Comment by Ostaer** [comment]
> > > bytesextra 里看看
> > 
> > 
> > 解码之后，为啥有乱码？号 ![image](https://private-user-images.githubusercontent.com/30763770/244935981-633a941c-1f57-45b6-8e5c-1d8ce388f30f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjYyMTksIm5iZiI6MTcwMTc2NTkxOSwicGF0aCI6Ii8zMDc2Mzc3MC8yNDQ5MzU5ODEtNjMzYTk0MWMtMWY1Ny00NWI2LThlNWMtMWQ4Y2UzODhmMzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA4NDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjkwYjNiZjkxNGViN2IxMzUwZjE5OTg5NDc1ZGZjZDFjYjI2MzU0M2I1NmU0MDVlMTY1YmI2YzJlYTFkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j3072Z1mHgrM7m_vFmTGjPgFcSUyTohHV4h61PvoP0w) 这个怎么解决？
> > @ruocaoqing 我也遇到这个问题，怎么解决乱码？

+1我也有这个问题

**Comment by WongJingGitt** [comment]
用这个脚本可以解析出来群聊消息发言人的微信号
https://github.com/LC044/WeChatMsg/blob/master/app/util/protocbuf/msg_pb2.py
使用方式：
`
def get_sender_form_room_msg(bytes_extra: str) -> str:
    """
    从bytesExtra中解析消息发送人
    :param bytes_extra: 数据库中bytesExtra
    :return: 发言人的wxid
    """
    bytes_string = b64decode(bytes_extra)
    msg_bytes_extra = MessageBytesExtra()
    msg_bytes_extra.ParseFromString(bytes_string)
    for item in msg_bytes_extra.message2:
        if item.field1 == 1:
            return item.field2
    return ""
`

**Comment by WongJingGitt** [comment]
用这个脚本可以解析出来群聊消息发言人的微信号
https://github.com/LC044/WeChatMsg/blob/master/app/util/protocbuf/msg_pb2.py
使用方式参考：

```
from utils.msg_pb2 import MessageBytesExtra


def get_sender_form_room_msg(bytes_extra: str) -> str:
    """
    从bytesExtra中解析消息发送人
    :param bytes_extra: 数据库中bytesExtra
    :return: 发言人的wxid
    """
    bytes_string = b64decode(bytes_extra)
    msg_bytes_extra = MessageBytesExtra()
    msg_bytes_extra.ParseFromString(bytes_string)
    for item in msg_bytes_extra.message2:
        if item.field1 == 1:
            return item.field2
    return ""
```
