### ISSUE TITLE
3.9.2.26-V9,关于type=46获取联系人接口 delFlag 删除标志

### ISSUE THREAD

**Issue by Xxm-YX** [ttttupup/wxhelper#183]
普通微信A  和  hook微信B

微信A将微信B删除后，通过接口tpye=46 获取微信B的所有联系人，发现delFlag 标志还是0，没有变化
![image](https://github.com/ttttupup/wxhelper/assets/61789235/3fb887bb-f896-418d-b540-e4f597ba94ef)

想知道这个地方是bug 还是 正常现象，麻烦大佬抽空看看，万分感谢

**Comment by ttttupup** [comment]
这个简单测试的，以实际为准，这里也可能不准
