### ISSUE TITLE
3.9.2.23-v8 和 v9  注入成功  提示注入结果: 1   但是端口并未监听，实际端口是未被占用

### ISSUE THREAD

**Issue by Don5211314** [ttttupup/wxhelper#185]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sglmsn** [comment]
https://github.com/ttttupup/wxhelper/releases/tag/3.9.2.23-V6
用的是这个版本的注入器

**Comment by Don5211314** [comment]
很刺激  这个方式我试过了 
我解决的方法是用管理员身份去启动微信  0.0  
现在我的远程一直闪退
