### ISSUE TITLE
消息时间戳问题

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#186]
现在接收消息的时间戳是秒级,
但是如果同一个秒内接收多条消息(比如有时候转发多条消息) 就会分不清楚消息的先后顺序
MSG数据库里面倒是有毫秒级的但是每条消息都查询一次数据库太浪费时间
所以:请问大佬可不可以修改为毫秒级时间戳

**Comment by ttttupup** [comment]
这些都是wechat自己的数据。

**Comment by qwe159357890** [comment]
哦 谢谢 我判断下 只查同一秒内的消息吧

**Comment by ttttupup** [comment]
消息里有排序   seq，可以研究一下 MsgSeq
