### ISSUE TITLE
3.8.1..26的asm是不是有问题呀，我注入会出错

### ISSUE THREAD

**Issue by qiuyu123456** [ttttupup/wxhelper#188]
PUSH       0x0
        PUSH       0x0
        PUSH       0x1
        PUSH       0x0
        MOV        EDI, msg_pptr
        PUSH       EDI
        LEA        EDX, to_user
        LEA        ECX, chat_msg
        CALL       send_text_msg_addr
        ADD        ESP, 0x14
        MOV        success, EAX
        LEA        ECX, chat_msg
        CALL       free_msg_addr

**Comment by qiuyu123456** [comment]
这是我用大佬你的代码改的，但是注入会报错
#include "pch.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <TlHelp32.h>
#include "wechat_data.h"
#define WX_SEND_TEXT_OFFSET 0xb6a930
#define WX_SEND_MESSAGE_MGR_OFFSET 0x65b2a0
#define WX_FREE_CHAT_MSG_OFFSET 0x649ac0
struct wxStr
{
    wchar_t* pStr;
    int strLen;
    int strLen2;
};
DWORD getWechatadd();
VOID SendText(wchar_t* wxid, wchar_t* msg);
struct wxMyUserInfo
{
    wchar_t* wxBindPhone;

};
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    {
        MessageBox(0, L"1！", L"1", NULL);
        wchar_t wxid[] = L"filehelper";
        wchar_t msg[] = L"aaaaa";
        SendText(wxid, msg);
    }
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

DWORD getWechatadd() {
    HMODULE winAdd = LoadLibrary(L"WeChat.dll");
    return (DWORD)winAdd;
}


VOID SendText(wchar_t* wxid, wchar_t* msg) {
    int success = 0;
    WeChatString to_user(wxid);
    WeChatString text_msg(msg);
    wchar_t** msg_pptr = &text_msg.ptr;
    char chat_msg[0x2A8] = { 0 };
    DWORD base = getWechatadd();
    DWORD send_message_mgr_addr = base + WX_SEND_MESSAGE_MGR_OFFSET;
    DWORD send_text_msg_addr = base + WX_SEND_TEXT_OFFSET;
    DWORD free_msg_addr = base + WX_FREE_CHAT_MSG_OFFSET;
    MessageBox(0, wxid, msg, NULL);

    //push dword ptr ds : [esi + 4]
    //lea eax, dword ptr ds : [esi + 38]
    //push 0
    //push 1
    //push eax
    //push edi &L"sssssssssss"
    //lea edx, dword ptr ss : [ebp - 64] L"filehelper"
    //lea ecx, dword ptr ss : [ebp - 3B0] 
    //call wechatwin.635CA930 
    __asm {
        PUSH       0x0
        PUSH       0x0
        PUSH       0x1
        PUSH       0x0
        MOV        EDI, msg_pptr
        PUSH       EDI
        LEA        EDX, to_user
        LEA        ECX, chat_msg
        CALL       send_text_msg_addr
        ADD        ESP, 0x14
        MOV        success, EAX
        LEA        ECX, chat_msg
        CALL       free_msg_addr
    }

}

**Comment by ttttupup** [comment]
先保存堆栈信息再调用

**Comment by qiuyu123456** [comment]
大佬还是老样子，一调用这个call就崩溃，麻烦能帮我看看吗？

**Comment by ttttupup** [comment]
__asm{
pushad
pushfd
xxxx
popfd
popad


}

**Comment by qiuyu123456** [comment]
大佬可以教我我一下吗？一调用发生消息的call就报错闪退。能加一下微信吗，拜托了，可以知识付费

**Comment by ttttupup** [comment]
你把代码发一下

**Comment by ttttupup** [comment]
有讨论组，可以讨论组了发

**Comment by qiuyu123456** [comment]
`// dllmain.cpp : 定义 DLL 应用程序的入口点。
#include "pch.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <TlHelp32.h>
#include <string>
#include <Windows.h>
#include "resource.h"


//个人信息偏移
#define WX_SELF_NAME_OFFSET 0x2C426E8
#define WX_SELF_MOBILE_OFFSET 0x2C42658
#define WX_SELF_CITY_OFFSET 0x2C426B8
#define WX_SELF_PROVINCE_OFFSET 0x2C426A0
#define WX_SELF_COUNTRY_OFFSET 0x2C42688
#define WX_SELF_ACCOUNT_OFFSET 0x2C42640
#define WX_SELF_ID_OFFSET 0x2C42A38
#define WX_SELF_SMALL_IMG_OFFSET 0x2C4289C
#define WX_SELF_BIG_IMG_OFFSET 0x2C428B4
#define WX_LOGIN_STATUS_OFFSET 0x2c42a10
#define WX_APP_DATA_ROOT_PATH_OFFSET 0x2c84ae0
#define WX_APP_DATA_SAVE_PATH_OFFSET 0x2c65728
#define WX_CURRENT_DATA_PATH_OFFSET 0x2c636fc

// 发生消息call偏移
#define WX_SEND_TEXT_OFFSET 0xb6a930
#define WX_SEND_MESSAGE_MGR_OFFSET 0x65b2a0
#define WX_FREE_CHAT_MSG_OFFSET 0x649ac0

DWORD getWechatadd();
DWORD ThreadProc(HMODULE hModule);
VOID SendText(wchar_t* wxid, wchar_t* msg);
INT_PTR CALLBACK Dlgproc(
    HWND hwndDlg,
    UINT uMsg,
    WPARAM wParam,
    LPARAM lParam
);

struct WeChatString {
    wchar_t* ptr;
    DWORD length;
    DWORD max_length;
    DWORD c_ptr = 0;
    DWORD c_len = 0;
    WeChatString() { WeChatString(NULL); }

    WeChatString(std::wstring& s) {
        ptr = (wchar_t*)(s.c_str());
        length = s.length();
        max_length = s.length() * 2;
    }
    WeChatString(const wchar_t* pStr) { WeChatString((wchar_t*)pStr); }
    WeChatString(int tmp) {
        ptr = NULL;
        length = 0x0;
        max_length = 0x0;
    }
    WeChatString(wchar_t* pStr) {
        ptr = pStr;
        length = wcslen(pStr);
        max_length = wcslen(pStr) * 2;
    }
    void set_value(const wchar_t* pStr) {
        ptr = (wchar_t*)pStr;
        length = wcslen(pStr);
        max_length = wcslen(pStr) * 2;
    }
};

struct SelfInfoInner {
    std::string name;
    std::string city;
    std::string province;
    std::string country;
    std::string account;
    std::string wxid;
    std::string mobile;
    std::string  small_img;
    std::string big_img;
    std::string data_root_path;
    std::string data_save_path;
    std::string current_data_path;
};

struct wxMyUserInfo
{
    wchar_t* wxBindPhone;

};
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:

        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)ThreadProc, hModule,0,NULL);
        /**/
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
DWORD ThreadProc(HMODULE hModule) {
    return DialogBox(hModule, MAKEINTRESOURCE(MAIN), NULL, &Dlgproc, 0);
}

INT_PTR CALLBACK Dlgproc(
    HWND hwndDlg,
    UINT uMsg,
    WPARAM wParam,
    LPARAM lParam
) {
    switch (uMsg)
    {
    case WM_INITDIALOG:
        break;
    case WM_COMMAND:
        if (wParam == GET)
        {
            wchar_t wxid[] = L"filehelper";
            wchar_t msg[] = L"aaaaa";
            SendText(wxid, msg);
        }
        break;
    case WM_CLOSE:
        EndDialog(hwndDlg, 0);
        break;
    default:
        break;
    }
    return false;
}

DWORD getWechatadd() {
    HMODULE winAdd = LoadLibrary(L"WeChat.dll");
    return (DWORD)winAdd;
}


VOID SendText(wchar_t* wxid, wchar_t* msg) {
    int success = 0;
    WeChatString to_user(wxid);
    WeChatString text_msg(msg);
    wchar_t** msg_pptr = &text_msg.ptr;
    char chat_msg[0x2A8] = { 0 };
    DWORD base = getWechatadd();
    DWORD send_message_mgr_addr = base + WX_SEND_MESSAGE_MGR_OFFSET;
    DWORD send_text_msg_addr = base + WX_SEND_TEXT_OFFSET;
    DWORD free_msg_addr = base + WX_FREE_CHAT_MSG_OFFSET;
    /*MessageBox(0, wxid, msg, NULL);*/

    //push dword ptr ds : [esi + 4]
    //lea eax, dword ptr ds : [esi + 38]
    //push 0
    //push 1
    //push eax
    //push edi &L"sssssssssss"
    //lea edx, dword ptr ss : [ebp - 64] L"filehelper"
    //lea ecx, dword ptr ss : [ebp - 3B0] 
    //call wechatwin.635CA930 
    __asm {
        PUSHAD
        PUSHFD
        PUSH       0x0
        PUSH       0x0
        PUSH       0x1
        PUSH       0x0
        MOV        EDI, msg_pptr
        PUSH       EDI
        LEA        EDX, to_user
        LEA        ECX, chat_msg
        CALL       send_text_msg_addr
        ADD        ESP, 0x14
        //MOV        success, EAX
        //LEA        ECX, chat_msg
        //CALL       free_msg_addr
        POPFD
        POPAD
    }
     
}



`
这是代码，我是把大佬你的代码复制一下来然后自己改了改

**Comment by ttttupup** [comment]
报的什么错误，错误信息

**Comment by ttttupup** [comment]
您可以在send_text_msg_addr 这个地方打个断点，对比一下正常发送和主动调用的参数是否一致。

**Comment by qiuyu123456** [comment]
好的我试试

**Comment by qiuyu123456** [comment]
> 报的什么错误，错误信息

我注入了之后，调用这个call直接崩溃了

**Comment by ttttupup** [comment]
要么参数不对，要么就是栈不平，直接崩溃应该是参数不对

**Comment by qiuyu123456** [comment]
这是正常发送
![正常发送](https://github.com/ttttupup/wxhelper/assets/67193565/195e458c-ed39-4f72-aa8a-fa0f82401377)
![image](https://github.com/ttttupup/wxhelper/assets/67193565/e73e05a7-ee46-4666-bd62-5a2615be9e34)
这是调用call发送
![调用call发送](https://github.com/ttttupup/wxhelper/assets/67193565/f45ec193-a512-44b7-a92a-1bc9d7d96cea)
![image](https://github.com/ttttupup/wxhelper/assets/67193565/853be67a-0d51-4ef4-80f6-2e316d769c0e)
是因为这个发送id吗

**Comment by ttttupup** [comment]
两个都断到这里  
![image](https://github.com/ttttupup/wxhelper/assets/31303661/a183a13f-d021-4043-9ca0-7f9843a3ee12)
 r然后栈顶截下图

**Comment by ttttupup** [comment]
readme有tg的讨论组

**Comment by qiuyu123456** [comment]
好的我加一下
