### ISSUE TITLE
wxhelper-3.9.2.23-v9的 type=9 修改成什么了？

### ISSUE THREAD

**Issue by 157276303** [ttttupup/wxhelper#190]
感谢作者，这东西不错，也一直使用着wxhelper-3.9.2.23-v6。但是 登录上后，有时候（时间长短不一）会崩溃，也不知道什么问题原因造成，几台电脑 都试过也会出现 。现想换v9看看，会不会也出现。发现 type=9 跟之前不一样了。翻看README.md，也没有找到说明。请问这个接口修改了什么？谢谢！！

**Comment by Xiaeer** [comment]
添加了http消息回调，需要加个字段enableHttp，为0表示禁用http服务，走tcp服务，为1表示开启新的http服务，消息走http服务

**Comment by Xiaeer** [comment]
v9, v8都有bug，消息会有延迟，不是丢消息，而是消息接受一段时间，pc端微信已经收到消息，自己写的接受消息服务要等几分钟才收到消息

**Comment by 157276303** [comment]
几分钟，会不会太久了！那还是用回v6吧！

**Comment by 157276303** [comment]
感谢回答！

**Comment by Xiaeer** [comment]
> 几分钟，会不会太久了！那还是用回v6吧！

是啊，太久了，我用回v7了

**Comment by Xiaeer** [comment]
> 感谢回答！

不客气，问下兄弟，你v6版本有没有崩溃，我这边运行10几个小时就会微信崩溃

**Comment by 157276303** [comment]
> > 感谢回答！
> 
> 不客气，问下兄弟，你v6版本有没有崩溃，我这边运行10几个小时就会微信崩溃

有时候不到1小时，有时候3-5小时遇崩溃。但有时候2天不关机也没有遇到。

**Comment by Xiaeer** [comment]
> > > 感谢回答！
> > 
> > 
> > 不客气，问下兄弟，你v6版本有没有崩溃，我这边运行10几个小时就会微信崩溃
> 
> 有时候不到1小时，有时候3-5小时遇崩溃。但有时候2天不关机也没有遇到。

好的，谢谢兄弟
