### ISSUE TITLE
陌生好友用wxid无法添加好友

### ISSUE THREAD

**Issue by a812086325** [ttttupup/wxhelper#191]
之前是好友，删除了后是可以通过wxid添加的，陌生的人添加，显示成功，无法收到添加好友请求。

版本：3.9.0.28，用3.9.2.23添加好友，微信会崩溃，所以换到了这个版本

**Comment by ttttupup** [comment]
3.9.2.26 版本修复了

**Comment by a812086325** [comment]
> 3.9.2.26 版本修复了

3.9.2.26-v9版本，还是陌生好友提示成功，没收到添加好友信息
type=20返回信息
{
	"code": 1,
	"result": "OK"
}

**Comment by ttttupup** [comment]
> > 3.9.2.26 版本修复了
> 
> 3.9.2.26-v9版本，还是陌生好友提示成功，没收到添加好友信息 type=20返回信息 { "code": 1, "result": "OK" }

这个测试过没问题，如果还有问题，也有可能是账号风控之类的了。

**Comment by a812086325** [comment]
> > > 3.9.2.26 版本修复了
> > 
> > 
> > 3.9.2.26-v9版本，还是陌生好友提示成功，没收到添加好友信息 type=20返回信息 { "code": 1, "result": "OK" }
> 
> 这个测试过没问题，如果还有问题，也有可能是账号风控之类的了。

换了几个微信号，添加陌生好友都没用，收不到添加信息

**Comment by qwe159357890** [comment]
为什么用v9?

**Comment by a812086325** [comment]
> 为什么用v9?

因为V10添加好友，微信直接崩溃，V9就不会
