### ISSUE TITLE
3.9.2.26-v10 无论调用哪一个接口微信都崩溃

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#193]
其他v1-v9都没有问题,完全一模一样的操作,注入也显示成功.也可以看到注入端口,但是无论调用哪一个接口,微信都崩溃!
请问各位大佬有遇到过这情况吗?还是只有我自己这样

**Comment by xkungxfu** [comment]
我也是。有QQ或微信吗，互加一下一块研究。

adin2017

**Comment by a812086325** [comment]
我这是V10添加微信好友就会崩溃
