### ISSUE TITLE
3.9.2.23-v9 截图图片无法解密，发送文件图片可以解密

### ISSUE THREAD

**Issue by tongchou** [ttttupup/wxhelper#194]
3.9.2.23-v9 和V7都测试过，发送截图图片无法解密，哪位朋友遇到过吗?

**Comment by redracker** [comment]
我现在遇到了，windowns发送一个截图的图片(qq截图、微信截图)，通过56接口下载下来的png文件，再通过解密接口去解密，仍然无法正确打开(非图片格式文件，不支持打开)

**Comment by redracker** [comment]
> 3.9.2.23-v9 和V7都测试过，发送截图图片无法解密，哪位朋友遇到过吗?

你好，请问你是怎么解决的呢
