### ISSUE TITLE
很好很强大!

### ISSUE THREAD

**Issue by qwe159357890** [ttttupup/wxhelper#197]
几天没看,大佬又在肝3.9.5.81了!
先赞一个,最近看到很多人反馈hook被警告,我使用咱们这个挂十多个号一个也没收到警告!超赞!
唯一就是在github上面看更新不太方便,不知道为什么不弄个组织(难道 官方不让?) 我私自贴出个企鹅码,如果不合适请给删除就可以!
![wxhelper群聊二维码](https://github.com/ttttupup/wxhelper/assets/97860760/b9d7c019-419c-4882-a19d-68da4779683f)

**Comment by ttttupup** [comment]
仅用于学习研究，请勿用于非法用途和商业用途！请不要抱有侥幸心理。

**Comment by qwe159357890** [comment]
没有商业,没非法,最多用到一个自动同意添加好友,其他就是只接收信息,
