### ISSUE TITLE
如何打包到docker中？ 或者有大神推荐docker么？

### ISSUE THREAD

**Issue by thinker007** [ttttupup/wxhelper#198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

打包到docker中，部署更加方便 成本更低。

**Comment by LeanFly** [comment]
是要在docker里运行微信？

**Comment by hxrbunny** [comment]
https://github.com/hxrbunny/wxhelper-docker

**Comment by thinker007** [comment]
> https://github.com/hxrbunny/wxhelper-docker

感谢感谢~

**Comment by sayue2019** [comment]
https://github.com/sayue2019/wechat-service-allin
