### ISSUE TITLE
找call的一些问题

### ISSUE THREAD

**Issue by iiwen** [ttttupup/wxhelper#2]
大佬好，我学了一些课程，勉强能找到call了，但感觉很费劲。请问大佬怎么学的找call或有什么技巧吗？
我小程序code的call没啥思路，找到了也是限制生成的，请问大佬研究过小程序code的寻找吗

**Comment by ttttupup** [comment]
个人喜欢静态分析+动态调试，没什么技巧，熟练了就可以了。小程序的相关call暂时没有研究过。

**Comment by iiwen** [comment]
> 个人喜欢静态分析+动态调试，没什么技巧，熟练了就可以了。小程序的相关call暂时没有研究过。

大佬，有什么资料吗？我一直卡在hook小程序的code上了，我想学习学习，谢谢~

**Comment by ttttupup** [comment]
《加密解密》《逆向工程揭秘》《逆向工程核心原理》《C++反汇编与逆向分析技术揭秘》等，win+linux+android 在看方向了解。

**Comment by iiwen** [comment]
> 个人喜欢静态分析+动态调试，没什么技巧，熟练了就可以了。小程序的相关call暂时没有研究过。

大佬，我一开始就关注这个项目了，也读了项目中的很多代码，但是还是没有hook小程序code的思路。
我们校园的小程序不用code还真登录不了，而且还是云函数（低版本调试的时候发现code的call和云函数的call在一起），想做个自动打卡的一直卡住不能推进，希望大佬能稍微点播一个方向(●'◡'●)，找call真的很头疼，好不容易找到了一个结果发现是很后面的call，用几次就不行了。大佬推荐的书我现在下了个电子版暑假的时候看了看，然后想在外面找人指导，动不动就收几千块，有点付不起~所以才来求大佬了

**Comment by iiwen** [comment]
> 《加密解密》《逆向工程揭秘》《逆向工程核心原理》《C++反汇编与逆向分析技术揭秘》等，win+linux+android 在看方向了解。

大佬，这几本书我现在在看第四本，现在暑假没事干刚好可以多看看，我会C++的基础知识和一些汇编的基础知识，能推荐一下先看哪本嘛~真的麻烦了！！

**Comment by ttttupup** [comment]
随便哪本都可以，可以跳着看，很多重复内容

**Comment by ttttupup** [comment]
网上随便找几个游戏逆向的视频看看，没啥难度的。
