### ISSUE TITLE
建议通过wechat 的版本使用对应的内存地址

### ISSUE THREAD

**Issue by estinfo** [ttttupup/wxhelper#20]
![image](https://user-images.githubusercontent.com/8905857/217979248-43ea9513-8f7f-426b-a59a-2cec276d34b6.png)

每次更新似乎就是内存地址不同，通过注入的版本号进行判断内存地址。
微信版本：	3.8.1.26
微信基址：	0x00260000
内存地址:	0x00B90000
成功注入:	wxhelper.dll

以后只需要维护支持的版本的内存地址变量就可以实现通用？

**Comment by ttttupup** [comment]
版本更新了对应的功能没变动可以，有一点变动都没法通用的。hook基本上很难通用

**Comment by estinfo** [comment]
目前这样也可以！~ 
需要重新写个注入工具，先启动wechat , 获取版本信息, 根据信息注入不同版本的dll .

**Comment by estinfo** [comment]
建议文档中的  ture 替换一下 true
