### ISSUE TITLE
各位大佬，为何ConsoleInject.exe在虚拟机中无法注入啊？

### ISSUE THREAD

**Issue by beyondchn** [ttttupup/wxhelper#204]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ttttupup** [comment]
应该是权限或者缺dll的问题

**Comment by beyondchn** [comment]
> 应该是权限或者缺dll的问题

大佬，缺dll，这个问题怎么解决啊？
