### ISSUE TITLE
3.9.5.81命令行注入后postman测试失败

### ISSUE THREAD

**Issue by along923928784** [ttttupup/wxhelper#206]
**ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll
dll inject successdll path : w dll path : 13948  注入结果：1**

![image](https://github.com/ttttupup/wxhelper/assets/31125971/470e54b5-a9c9-4a90-b87b-087b5a2ef177)
大佬可以帮忙解决一下吗

**Comment by JackMa777** [comment]
得用新版的api

**Comment by JackMa777** [comment]
我用的是release里面的wxhelper.dll
![image](https://github.com/ttttupup/wxhelper/assets/43034054/afbc63ff-3fca-488b-83d5-a1bbe1ed7752)

**Comment by along923928784** [comment]
> 我用的是release里面的wxhelper.dll ![image](https://user-images.githubusercontent.com/43034054/252295735-afbc63ff-3fca-488b-83d5-a1bbe1ed7752.png)

注入工具可以发给我一份吗  v：ycl_528  先谢谢大佬了

**Comment by along923928784** [comment]
> > 得用新版的api
> 
> ![image](https://user-images.githubusercontent.com/31125971/252294239-11c1f5bd-b4d8-4b36-9ab9-27b7ac43b86e.png) 还是不行 是不是我的dll文件不对

已解决 产生问题的原因是我开了代理 尴尬

**Comment by vjeson** [comment]
3.9.5.81版本我死活注入不成功，用的tool\injector下面的  `.\ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll`  输出也是显示成功 dll inject successdll path : w dll path : 45268  注入结果：1 ，但是实际，查看进程，没有注入的dll ,请求 接口 http://127.0.0.1:19088/api/userinfo 也没有反应，哪位高人指点一下

**Comment by caiyakang** [comment]
请问哪一个接口可以监听收到好友添加请求消息

**Comment by caiyakang** [comment]
不会C++,谁能提供一个编译好的wxhelper.dll

**Comment by caiyakang** [comment]
> > > 得用新版的api
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31125971/252294239-11c1f5bd-b4d8-4b36-9ab9-27b7ac43b86e.png) 还是不行 是不是我的dll文件不对
> 
> 已解决 产生问题的原因是我开了代理 尴尬

能否提供一下编译好的3.9.5.81 的wxhelper.dll

**Comment by caiyakang** [comment]
> http://127.0.0.1:19088/api/userinfo

请问你解决了没有呀,我的也不行!!到底什么原因呀.
