### ISSUE TITLE
w10 3.9.2.23 微信DLL注入器V1.0.3显示注入成功，python3.9运行tcpserver.py文件后没有任何消息打印

### ISSUE THREAD

**Issue by Yuri2** [ttttupup/wxhelper#210]
w10
微信3.9.2.23
微信DLL注入器V1.0.3显示注入成功，
python3.9运行tcpserver.py文件后没有任何消息打印，也没有报错
tcpserver.py代码内容：：
`import json
import threading
import socketserver

class ReceiveMsgSocketServer(socketserver.BaseRequestHandler):
def init(self, *args, **kwargs):
super().init(*args, **kwargs)

def handle(self):
    conn = self.request
    while True:
        try:
            ptr_data = b""
            while True:
                data = conn.recv(1024)
                ptr_data += data
                if len(data) == 0 or data[-1] == 0xA:
                    break

            msg = json.loads(ptr_data)
            ReceiveMsgSocketServer.msg_callback(msg)

        except OSError:
            print(12)
            break
        except json.JSONDecodeError:
            print(34)
            pass
        conn.sendall("200 OK".encode())
    conn.close()

@staticmethod
def msg_callback(msg):
    print(56)
    print(msg)
def start_socket_server(port: int = 19099,
request_handler=ReceiveMsgSocketServer,
main_thread: bool = True) -> int or None:
ip_port = ("127.0.0.1", port)
try:
s = socketserver.ThreadingTCPServer(ip_port, request_handler)
if main_thread:
s.serve_forever()
else:
socket_server = threading.Thread(target=s.serve_forever)
socket_server.setDaemon(True)
socket_server.start()
return socket_server.ident
except KeyboardInterrupt:
print(67)
pass
except Exception as e:
print(e)
return None

if name == 'main':
start_socket_server()
`
用client.py里的check_login方法测试，反回requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:19088/api/?type=0'
显示却注入成功，
![image](https://github.com/ttttupup/wxhelper/assets/18521198/815fae3d-9119-480d-b09e-2783303cadcc)

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/discussions/65
