### ISSUE TITLE
请教一下监听收到好友添加请求是哪个接口

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#212]
当有好友申请的时候,如果监听到这个消息,应该是用哪个接口呢?

**Comment by ttttupup** [comment]
hook 消息的那个接口

**Comment by caiyakang** [comment]
> hook 消息的那个接口

能否提提供一个3.9.5.81 的wxhelper.dll,不会C++,编译不了.

**Comment by caiyakang** [comment]
已经找到了 https://github.com/ttttupup/wxhelper/releases/tag/3.9.5.81-v1
