### ISSUE TITLE
3.9.5.81 无法控制台和注入器都无法使用问题.

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#213]
1.操作环境:win10 专业版
2.微信版本:3.9.5.81

一. 使用 ConsoleApplication.exe 注入报错:
ConsoleApplication  -i C:\Program Files (x86)\Tencent\WeChat\WeChat.exe -p D:\PROJECT\mtp\hook\WxHelper\wxhelper.dll

![9fa5c5b1b000ec0c4735b7161364f8e](https://github.com/ttttupup/wxhelper/assets/12150755/caaf4a0a-f95d-40fa-845b-6252282512c8)

![536d2e1128199787b83cf44e68eb437](https://github.com/ttttupup/wxhelper/assets/12150755/cd656829-0db2-44f5-9d1e-5c5cbc7189f5)

二. 微信DLL注入器V1.0.3.exe打开闪退
2.1 如果微信没启动是可以正常打开的
2.2 当启动微信之后,在打开微信DLL注入器V1.0.3.exe,自动变成无响应,过一会就闪退了.
![a018bd2bbdb6800fd5781916ead74cb](https://github.com/ttttupup/wxhelper/assets/12150755/99bb25eb-2250-4451-8494-2edf9dc97875)

**Comment by vjeson** [comment]
这是因为你用的ConsoleApplication.exe是debug版本，自己编译个release版本，不过我用release版本，显示注入成功，但实际没有注入 dll inject successdll path : C dll path : 8036  注入结果：1 不知道什么原因，需要作者，放个最新的dll和注入的exe

**Comment by ttttupup** [comment]
需要安装提示的dll

**Comment by qop1832** [comment]
我是用python的pymem库注入的 pymem.process.inject_dll(pm.process_handle, filename_path)  还挺好用

**Comment by vjeson** [comment]
> pymem.process.inject_dll

能否分享一下完整代码

**Comment by qop1832** [comment]
pip install pymem 安装pymem库   然后 import pymem   导入库   然后。。。def inject_dll(handle, filepath):
    """Inject a dll into opened process.

    Parameters
    ----------
    handle: int
        Handle to an open object
    filepath: bytes
        Dll to be injected filepath

    Returns
    -------
    DWORD
        The address of injected dll
    """

**Comment by vjeson** [comment]
> handle: int
>     Handle to an open object

handle: int
    Handle to an open object

怎么获得这个句柄？有没有直接通过进程名称WeChat.exe获取handle传入的方法，楼主用是的最新3.9.5.81版本x64位？作者发布的dll么？我用这个版本，显示注入成功，但是检查实际没有注入，之前的32位的旧版本可以

**Comment by qop1832** [comment]
pm = pymem.Pymem('WeChat.exe')
handle = pm.process_handle

> > handle: int
> > 打开对象的句柄
> 
> handle: int 打开对象的句柄
> 
> 怎么获取这个句柄？有没有直接通过进程名称WeChat.exe获取句柄设置的方法，楼主用的是最新的3.9.5.81版本x64位？作者发布的dll成功么？我用这个版本，显示注入，但是检查实际没有注入，之前的32位的旧版本可以

**Comment by vjeson** [comment]
> 

返回None注入不成功，也没有任何的错误？ 这个3.9.5.81 x64位的就没有注入成功过，不知道咋回事，之前的32位，很容易就注入成功了

**Comment by caiyakang** [comment]
> 是的 3.9.5.81 下面是完整的注入代码
> 
> 先安装pymem库 pip install pymem
> 
> ```
> import pymem
> 
> dll_path = b'D:\\3.9.5.81-v1.dll'
> 
> process_name = "WeChat.exe"
> 
> pm = pymem.Pymem(process_name)
> 
> pymem.process.inject_dll(pm.process_handle, dll_path)
> ```
> 
> > > handle: int
> > > 打开对象的句柄
> > 
> > 
> > handle: int 打开对象的句柄
> > 怎么获取这个句柄？有没有直接通过进程名称WeChat.exe获取句柄设置的方法，楼主用的是最新的3.9.5.81版本x64位？作者发布的dll成功么？我用这个版本，显示注入，但是检查实际没有注入，之前的32位的旧版本可以

很奇怪,会导注入会导致微信闪退,有办法解决吗??
