### ISSUE TITLE
3.9.2.23命令行注入后postman测试失败

### ISSUE THREAD

**Issue by Yuri2** [ttttupup/wxhelper#215]
ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
命令行注入，显示反回
dll inject successdll path : w dll path : 10784  注入结果：1

检查是否登录
https://127.0.0.1:19088/api/?type=8
没数据反回
工具注入显示
![image](https://github.com/ttttupup/wxhelper/assets/18521198/18a35827-51ee-41f3-8f94-0637ce148235)

**Comment by Yuri2** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/18521198/79d5c005-3745-4a3f-9dcb-502f9e63354c)

**Comment by ttttupup** [comment]
使用管理员权限注入

**Comment by Yuri2** [comment]
> 使用管理员权限注入

![image](https://github.com/ttttupup/wxhelper/assets/18521198/7dbaf6e5-0c7d-42d3-b6ed-8d17dfd44259)

**Comment by Yuri2** [comment]
显示注入了，但启动的那个tcpserver.py没反应

**Comment by Yuri2** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/18521198/fe2a2e8c-b20f-4642-bf57-be1a51423d9a)

**Comment by Yuri2** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/18521198/0e369938-ef53-4e11-b452-e092c1ae01f5)

**Comment by Yuri2** [comment]
> 使用管理员权限注入

还有那个飞机群也加不了，飞机权限什么都开了

**Comment by Yuri2** [comment]
> 管理员权限注入

微信版本
![image](https://github.com/ttttupup/wxhelper/assets/18521198/7096c204-a9aa-4c3d-9e9f-d4536e9b55f8)

**Comment by caiyakang** [comment]
> ConsoleInject.exe -i WeChat.exe -p wxhelper.dll 命令行注入，显示反回 dll inject successdll path : w dll path : 10784 注入结果：1
> 
> 检查是否登录 https://127.0.0.1:19088/api/?type=8 没数据反回 工具注入显示 ![image](https://user-images.githubusercontent.com/18521198/253724720-18a35827-51ee-41f3-8f94-0637ce148235.png)

请问你解决了没有,我的显示注入成功,http也访问不了.

**Comment by vincentlin7** [comment]
不用-i WeChat.exe 参数，用-I [WeChat.exe pid]就可以
