### ISSUE TITLE
请问这种DLL注入的方式被封号的概率高吗?

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#218]
1.一种是在pc端使用dll注入方式获取到微信pc端exe程序运行内存数据，然后进行相关操作，优点是可以实现的功能强大，缺点是容易封号，因为pc微信可以检测到dll注入操作。

2.还有一种也是利用pc端实现，利用hook操作内存中实时运行的微信数据来实现相关功能，优点是微信检测不到，缺点是难度较大，需要熟练的c、c++开发和汇编语言基础，可实现功能较少或者较难。

3.利用安卓端实现，利用xposed来hook微信相关函数，优点：可实现功能较多，缺点：要求高，手机需要root，新版微信也可以检测到hook操作，容易封号。

应该是第一种的实现方式吧

**Comment by ttttupup** [comment]
肯定有封号风险，请酌情使用。

**Comment by lngwu11** [comment]
还有一种是走ipad协议，只不过这种方式难度更大

**Comment by Xiaeer** [comment]
> 还有一种是走ipad协议，只不过这种方式难度更大

不是难度大，是没有ipad协议，人家ipad协议自己赚钱，根本不会出售流出
