### ISSUE TITLE
端口测试不通，No connection adapters were found

### ISSUE THREAD

**Issue by vincentlin7** [ttttupup/wxhelper#219]
dll显示已经注入成功，也能查到，但运行client.py，测试联通性时，报错    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '0.0.0.1:19088/api/?type=0'
![image](https://github.com/ttttupup/wxhelper/assets/5355964/40fb09ba-0161-4e0a-ae01-d709f8ad0c50)

**Comment by ttttupup** [comment]
127.0.0.1

**Comment by vincentlin7** [comment]
上面是我测试过程中地址改错了，恢复成127.0.0.1 或者0.0.0.0，结果也是一样。
![image](https://github.com/ttttupup/wxhelper/assets/5355964/2488b0de-2ed2-43de-a520-c869f37facdb)

**Comment by vincentlin7** [comment]
python的示例地址头部加上http://，可以联通，但是报另外一个错误{"code":200,"data":null,"msg":"not support url"}
