### ISSUE TITLE
3.9.5.81  提示注入成功,但是没有http无法访问,有可能是什么原因?

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#220]
运行环境:win10 企业版
微信版本:
![image](https://github.com/ttttupup/wxhelper/assets/12150755/49499f72-167b-4502-93bc-f493dc3df621)

1.执行注入
.\ConsoleApplication.exe  -i WeChat.exe -p wxhelper.dll

![cfa2cf313f1e0e6792ea971e6e20a36](https://github.com/ttttupup/wxhelper/assets/12150755/2d57f04c-c33d-4903-9c87-e9696a167c15)

2. http访问无效,查了监听端口也没有找到:
http://127.0.0.1:19088/api/userinfo
![image](https://github.com/ttttupup/wxhelper/assets/12150755/f83f710d-c5f9-49f3-9372-d4191a8f4a33)

**Comment by wangxy496** [comment]
请问怎么解决的，我现在也是这个情况，注入成功，但是无法访问
