### ISSUE TITLE
wxhelper-3.9.2.23-v9 提示注入成功,但是没有http无法访问,有可能是什么原因?

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#221]
![image](https://github.com/ttttupup/wxhelper/assets/12150755/b7f44af2-79fa-409d-abc3-851c8e0f52ba)

![image](https://github.com/ttttupup/wxhelper/assets/12150755/9b72e2cf-31ee-42d1-bbdf-9c95a2e2bb96)

**Comment by caiyakang** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/12150755/38ac647b-a767-4ab4-bf8b-fab27cc79faa)

**Comment by ttttupup** [comment]
缺少一些dll组件

**Comment by caiyakang** [comment]
> 缺少一些dll组件

因为没有报错,也不知道是需要安装什么,可能给个提示吗,比如需要安装什么包之类的.

**Comment by caiyakang** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/12150755/f5e0a3dc-aa0d-4227-9cad-ac362cbfdc45)
安装了这个也是一样不行呀

**Comment by ttttupup** [comment]
看一下wxhelper.dll的依赖，缺少了哪些  http://www.dependencywalker.com/ 这个工具或者vs自带的都可以

**Comment by hgkghjvkjgbio** [comment]
> 看一下wxhelper.dll的依赖，缺少了哪些 http://www.dependencywalker.com/ 这个工具或者vs自带的都可以

用这个工具查看了，确实是少很多dll，但是到哪下载，对应的哪个版本？？？，vc 运行库之类的全下载了安装也没用。。

**Comment by sdydscj1** [comment]
我也遇到了 这个问题，我照着b站的教程  自己写了个注入器，就可以成功注入并开启了http服务器消息回传。
用自带的 注入器 显示注入成功，实际没有成功

**Comment by clippers1** [comment]
@sdydscj1 可否借用一下
