### ISSUE TITLE
wxhelper-3.9.0.28-v13

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#222]
注入成功之后,同一个帐号在两台不同的win10上面进行获取用户信息,其中一台电脑没问题,一台电脑报这个错误:{"msg":"[json.exception.type_error.316] invalid UTF-8 byte at index 4: 0xC4","result":"ERROR"}   请问这个有可能是什么原因呢.

**Comment by ttttupup** [comment]
系统编码格式，chcp查看一下。

**Comment by caiyakang** [comment]
{"msg":"[json.exception.type_error.316] invalid UTF-8 byte at index 6: 0xC5","result":"ERROR"}   
@ttttupup 这个问题的场景找到了,就  更多>设置>文件管理的目录 ,如果这个目录包含中文并且不是默认目录就会有这个问题,请问这个应该怎么解决呢,是底层哪里引起的

**Comment by ttttupup** [comment]
不用中文或者把系统设置成默认utf8编码，需要重启
