### ISSUE TITLE
关于3.9.0.28版本挂号会出现登陆异常问题

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#224]
描述:
在注入DLL后,并调用 http://127.0.0.1:19088/api/?type=9 之后,只是输出消息,并未做其他的操作,在号放在那边几个小时之后就出现了异常登陆:
![0aab9337c83bd3270ea3bfffb7ae384](https://github.com/ttttupup/wxhelper/assets/12150755/e13d6b61-20d0-474f-a95d-abaa2968b66a)

请问这个问题是否有办法处理

**Comment by caiyakang** [comment]
win7这个版本无法注入成功,请问可否帮忙解决,有偿定制开发,给个联系方式

**Comment by ttttupup** [comment]
封号风险请自行承担，爱惜账号。
