### ISSUE TITLE
3.9.2.23V9 hook_msg() 报错

### ISSUE THREAD

**Issue by vincentlin7** [ttttupup/wxhelper#226]
其他功能正常，hook_msg()返回错误{"msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}

![image](https://github.com/ttttupup/wxhelper/assets/5355964/c6ceb22c-7d46-476d-a79a-555f7060d510)

**Comment by along923928784** [comment]
{
    "port": "19099"
    "ip":"127.0.0.1",
    "url":"http://localhost:8080",
    "timeout":"3000",
    "enableHttp":"0"
}

传入以上json

**Comment by vincentlin7** [comment]
可以了，谢谢。
