### ISSUE TITLE
3.9.5.81-v3  注入成功了，端口也开了，但是返回url not support 什么情况

### ISSUE THREAD

**Issue by hgkghjvkjgbio** [ttttupup/wxhelper#232]
3.9.5.81 管理员权限注入成功了，19088端口也开了，
post 到19088的时候提示：

'{"code":200,"data":null,"msg":"not support url"}\n'

url格式不对吗

**Comment by ttttupup** [comment]
字面意思，检查一下url是不是这个版本的

**Comment by Esword618** [comment]
@hgkghjvkjgbio 
可以分享一下你的注入过程吗，我首先管理员权限切换到wechat目录运行命令`tasklist | findstr "WeChat.exe"`获取pid，然后注入dll,命令`.\ConsoleInject.exe -I pid -p .\wxhelper .dll`，但是py运行报错，没有连接到
