### ISSUE TITLE
请教数据库句柄查询问题

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#235]
可以正常拿到数据库句柄,调用接口也可以正常响应
{
    "dbHandle": 326434624,
    "sql":"select * from MSG where MsgSvrID=8985035417589024392"
}

请问下如果我有这个dbHandle的值,想独立写个python通过dbhandle是否也可以查询得到?

**Comment by caiyakang** [comment]
我的意思是不通过调这个接口

**Comment by ttttupup** [comment]
进程隔离的，不是同一个进程拿了没用
