### ISSUE TITLE
双开问题

### ISSUE THREAD

**Issue by sdydscj1** [ttttupup/wxhelper#240]
各位大佬，想问下注入时的双开问题

因为看到文档写： // 注入并指定http端口
    ConsoleInject.exe  -i demo.exe -p E:\testInject.dll  -P  18888   
    // 注入指定pid并关闭多开限制
    ConsoleInject.exe  -I 15048 -p E:\testInject.dll  -m 15048  

可是dll 应该是自启动19088端口，并且想改变端口的话可以在微信目录下增加config.ini文件指定端口

那么假如想监听两个微信客户端，岂不是矛盾吗

我尝试了好久 都没有成功，有成功的大佬能分享下经验吗

**Comment by ttttupup** [comment]
命令行指定端口的版本只有一个，多开也只支持32位版本，其他的版本不行

**Comment by sdydscj1** [comment]
大佬，是哪个版本呀 @ttttupup
