### ISSUE TITLE
3.9.0.28-specify-port-V13 指定端口后无法注入成功

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#241]
ConsoleInject.exe -i WeChat.exe  -p wxhelper.dll -P 19089,指定自已的端口无法注入成功,
但是用3.9.0.28-V13 这个固定端口是可以注入成功的,有可能是什么原因导致呢?

**Comment by ttttupup** [comment]
命令行指定端口的版本只有一个版本支持，其他版本不支持

**Comment by caiyakang** [comment]
[3.9.0.28-specify-port-V13](https://github.com/ttttupup/wxhelper/releases/tag/3.9.0.28-specify-port-V13)
注入后不启动http，外部传入端口启动

这个是您在发布上的说明,请问具体哪个版本才是支持的呢.

**Comment by caiyakang** [comment]
3.9.0.28-V13 结果如下:
1.使用命令:ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
2.可以注入成功,HTTP端口固定为19088

3.9.0.28-specify-port-V13  结果如下:
1.使用命令:ConsoleInject.exe -i WeChat.exe -p wxhelper.dll -P 19089 注入失败
2.使用命令:ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll -P 19089 注入成功,但是http端口19089没有启动。

**Comment by ttttupup** [comment]
> 

-p 后面都是绝对路径，不是相对路径

**Comment by caiyakang** [comment]
我试了好多方式,好像是跟命名有关系,因为我同时在用多个版本,所以dll会改名，最终发现dll一旦改名就会不成功，请作者确认一下是否有关系。

1.  D:\\PROJECT\\mtp\\wxm\\ConsoleApplication.exe -i WeChat.exe  -p D:\\PROJECT\\mtp\\wxm\\wxhelper-sp-v13.dll -P 18888  注入成功,端口未启动

2.  D:\\PROJECT\\mtp\\wxm\\ConsoleApplication.exe -i WeChat.exe  -p D:\\PROJECT\\mtp\\wxm\\wxhelper.dll -P 18888  注入成功,端口也启动了
