### ISSUE TITLE
wxhelper-3.9.0.28-V13 注入成功，卸载微信卡死！！

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#242]
注入命令：
D:\\PROJECT\\mtp\\wxm\\ConsoleApplication.exe -i WeChat.exe  -p D:\\PROJECT\\mtp\\wxm\\wxhelper.dll -P 18888

卸载命令：
D:\\PROJECT\\mtp\\wxm\\ConsoleApplication.exe -u WeChat.exe -d wxhelper.dll  

我用的是Python的  os.popen(command_text) 来执行的

**Comment by ttttupup** [comment]
开启了hide dll功能的不能卸载

**Comment by caiyakang** [comment]
应该没有隐藏，我用listdlls可以看得到
![image](https://github.com/ttttupup/wxhelper/assets/12150755/a760e705-88c7-49b7-a274-fabfb8f228eb)

**Comment by ttttupup** [comment]
卸载之前要把http关了，所有的功能都要关掉

**Comment by caiyakang** [comment]
HOOK消息有关闭，HTTP关闭需要调用哪个呢，我在文档里面没有找到对应的方法

**Comment by ttttupup** [comment]
http_close
