### ISSUE TITLE
搜索手机号导致服务挂掉

### ISSUE THREAD

**Issue by litterGuy** [ttttupup/wxhelper#244]
版本号：3.9.2.23
问题描述：
当使用127.0.0.1:19088/api/?type=19接口去搜索手机号码时，如果该手机号存在、接口一切正常。

但是搜不到用户时，接口就会一直卡在请求中。然后所有接口都不可使用。最后服务会挂掉

请问 这个问题该怎么去修复？

**Comment by ttttupup** [comment]
是崩溃了，还是http挂掉了

**Comment by litterGuy** [comment]
微信还在 请求一直是sending request，http服务应该是没有挂掉。
![image](https://github.com/ttttupup/wxhelper/assets/2154539/1113d0ec-f0dd-41aa-b3b3-204ffc3daeef)

**Comment by ttttupup** [comment]
SearchContactNetScene 这个方法可以加个超时，这里hook实现的比较随意，可能出现死循环。

**Comment by litterGuy** [comment]
大佬 可以给帮忙打个包吗 不会c++😭

**Comment by ttttupup** [comment]
自己动手，丰衣足食。

**Comment by ttttupup** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/31303661/17eeb04a-db5d-4714-8276-a7611d177cd3)   加个次数，超过了跳出就行了

**Comment by litterGuy** [comment]
咨询下 在CLion cmake的时候，报错 
```
Problems were encountered while collecting compiler information:
	cc1plus.exe: fatal error: /D: No such file or directory
	cc1plus.exe: fatal error: '_UNICODE': No such file or directory
	cc1plus.exe: fatal error: 'UNICODE': No such file or directory
``
![image](https://github.com/ttttupup/wxhelper/assets/2154539/e3c3bd63-1ba4-45f3-83ce-1e9df916c3f1)

这样怎么解决？

**Comment by litterGuy** [comment]
编译的时候这个错误，该怎么处理

```
Problems were encountered while collecting compiler information:
	cc1plus.exe: fatal error: /D: No such file or directory
	cc1plus.exe: fatal error: '_UNICODE': No such file or directory
	cc1plus.exe: fatal error: 'UNICODE': No such file or directory
```

**Comment by litterGuy** [comment]
多谢大佬指导，一步步的总算编译过了

**Comment by irfjjjdk** [comment]
> 多谢大佬指导，一步的总算编译完成了

能上传个DLL吗，我搞了1天没搞懂怎么生成，老是提示错误！
