### ISSUE TITLE
关于用 wxid 加好友的问题

### ISSUE THREAD

**Issue by shwatty** [ttttupup/wxhelper#246]
我发现个问题，用wxid加好友的时候，如果这个wxid是自己曾经的好友，则可以发送成功，对方能收到好友申请的提示

如果是陌生人的wxid，发送以后，对方完全收不到，不知道你们有没有这种情况

百思不得其解，这个问题困扰我一天时间了，换了好几个版本的微信也一样

**Comment by ttttupup** [comment]
参考3.9.2.26里，需要设置一下好友权限，`  //    EDI,0xE  ESI,0   all
  //    EDI,0xE  ESI,8   only chat
  //    EDI,0xE  ESI,1   no let look 
  //    EDI,0xE  ESI,2   no look `

**Comment by shwatty** [comment]
把contact_mgr.cc 文件中的这部分代码注释去掉，重新编译一下，就正常了，是吧

`int ContactMgr::AddFriendByWxid(wchar_t *wxid,wchar_t* msg) {
  int success = -1;
  DWORD contact_mgr_addr = base_addr_ + WX_CONTACT_MGR_OFFSET;
  DWORD verify_msg_addr = base_addr_ + WX_VERIFY_MSG_OFFSET;
  DWORD set_value_addr = base_addr_ + WX_INIT_CHAT_MSG_OFFSET;
  DWORD do_verify_user_addr = base_addr_ + WX_DO_VERIFY_USER_OFFSET;
  DWORD fn1_addr = base_addr_ + 0x7591b0;
  WeChatString user_id(wxid);
  WeChatString w_msg(msg);
  DWORD instance =0;
  Unkown null_obj={0,0,0,0,0,0xF};
   //   EDI,0xE  ESI,0   all
   //   EDI,0xE  ESI,8   only chat
   //   EDI,0xE  ESI,1   no let look 
   //   EDI,0xE  ESI,2   no look 
 __asm{
        PUSHAD
        PUSHFD
        CALL       contact_mgr_addr     
        MOV        dword ptr [instance],EAX     
        MOV        EDI,0xE
        MOV        ESI,0x8
        MOV        EAX,0x2  
        SUB        ESP,0x18                                         
        MOV        EAX,ESP
        MOV        dword ptr ds:[EAX],0   
        MOV        dword ptr ds:[EAX+0x14],0xF
        MOV        dword ptr ds:[EAX+0x10],0 
        MOV        byte ptr ds:[EAX],0  
        SUB        ESP,0x18
        LEA        EAX,null_obj                              
        MOV        ECX,ESP
        PUSH       EAX                                               
        CALL       fn1_addr                                     
        PUSH       ESI
        PUSH       EDI
        MOV        EAX,w_msg       

        SUB        ESP,0x14
        MOV        ECX,ESP
        PUSH       -0x1
        PUSH       EAX
        CALL       verify_msg_addr                                     
        PUSH       0x2
        LEA        EAX,user_id

        SUB        ESP,0x14
        MOV        ECX,ESP
        PUSH       EAX
        CALL       set_value_addr                                 
        MOV        ECX,dword ptr [instance] 
        CALL       do_verify_user_addr    
        MOV        success,EAX          
        POPFD         
        POPAD
 }
  return success;
}`

**Comment by ttttupup** [comment]
是的，默认聊天基本上就不会有问题了

**Comment by shwatty** [comment]
我最终是买了别人的代码才解决，他的加好友是有来源参数可以选择的比如扫一扫，咱们这个项目要是能有来源参数我感觉也是可行的，希望大佬研究一下

**Comment by Adelsy** [comment]
咋解决的

**Comment by qwe159357890** [comment]
不知道新版本加好友问题解决了没有

**Comment by shwatty** [comment]
﻿还是没解决，按照作者提供的方法做了，依然不起作用在 2023年9月2日，08:31，qwe159357890 ***@***.***> 写道：﻿
不知道新版本加好友问题解决了没有

**Comment by shwatty** [comment]
还是没解决，按照作者提供的方法做了，依然不起作用在 2023年9月2日，08:31，qwe159357890 ***@***.***> 写道：﻿
不知道新版本加好友问题解决了没有

**Comment by Adelsy** [comment]
还是没加上，发送的好友请求对方根本收不到

**Comment by LHC12580** [comment]
> 我发现个问题，用wxid加好友的时候，如果这个wxid是自己曾经的好友，则可以发送成功，对方能收到好友申请的提示
> 
> 如果是陌生人的wxid，发送以后，对方完全收不到，不知道你们有没有这种情况
> 
> 百思不得其解，这个问题困扰我一天时间了，换了好几个版本的微信也一样

大佬怎么加

**Comment by LHC12580** [comment]
> 我最终是买了别人的代码才解决，他的加好友是有来源参数可以选择的比如扫一扫，咱们这个项目要是能有来源参数我感觉也是可行的，希望大佬研究一下
> 
> 
> ![322ba36e2832e75a3cd24b28a345e5cd](https://github.com/ttttupup/wxhelper/assets/49614107/df4f4fab-6099-45d0-a013-20c2ddf373ed)
> 
> 

淘宝的也是扫一扫

**Comment by taozi926494** [comment]
作者大大，还没解决吗这个问题？

**Comment by LHC12580** [comment]
😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月1日(周四) 中午11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ttttupup/wxhelper] 关于用 wxid 加好友的问题 (Issue #246)




 
作者大大，还没解决吗这个问题？

**Comment by taozi926494** [comment]
> 我最终是买了别人的代码才解决，他的加好友是有来源参数可以选择的比如扫一扫，咱们这个项目要是能有来源参数我感觉也是可行的，希望大佬研究一下
> 
> ![322ba36e2832e75a3cd24b28a345e5cd](https://private-user-images.githubusercontent.com/49614107/259698198-df4f4fab-6099-45d0-a013-20c2ddf373ed.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjY1NzgsIm5iZiI6MTcwNzIyNjI3OCwicGF0aCI6Ii80OTYxNDEwNy8yNTk2OTgxOTgtZGY0ZjRmYWItNjA5OS00NWQwLWEwMTMtMjBjMmRkZjM3M2VkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMzMxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTgzODYyYTY5Y2VmODEyM2U4MjRkMjU0ZTQ2OGJkYzYyM2RkYWY4NDhkNmFiMGI2NjYzMmM4NmE2ZDU0NDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B6ZqgD112LL8owyLj27n_sWLI6dl3uhcPpDT8QpDWxI)

请问找谁购买的呢，可以推荐下吗 谢谢

**Comment by LHC12580** [comment]
已经有人开发出来，但是不开源



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月6日(周二) 晚上9:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ttttupup/wxhelper] 关于用 wxid 加好友的问题 (Issue #246)




  
我最终是买了别人的代码才解决，他的加好友是有来源参数可以选择的比如扫一扫，咱们这个项目要是能有来源参数我感觉也是可行的，希望大佬研究一下
 

  
请问找谁购买的呢，可以推荐下吗 谢谢

**Comment by taozi926494** [comment]
> 已经有人开发出来，但是不开源
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月6日(周二) 晚上9:33 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ttttupup/wxhelper] 关于用 wxid 加好友的问题 (Issue #246) 我最终是买了别人的代码才解决，他的加好友是有来源参数可以选择的比如扫一扫，咱们这个项目要是能有来源参数我感觉也是可行的，希望大佬研究一下 请问找谁购买的呢，可以推荐下吗 谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以推荐给我吗，谢谢，继续这个功能
