### ISSUE TITLE
75d4709  编译有报错

### ISSUE THREAD

**Issue by estinfo** [ttttupup/wxhelper#25]
![image](https://user-images.githubusercontent.com/8905857/218351155-29feac3e-ce27-48cf-9f37-b1620383c50b.png)

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.4">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Helvetica}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px Helvetica; min-height: 11.0px}
table.t1 {border-style: solid; border-width: 0.5px 0.5px 0.5px 0.5px; border-color: #bfbfbf #bfbfbf #bfbfbf #bfbfbf; border-collapse: collapse}
td.td1 {border-style: solid; border-width: 0.5px 0.5px 0.5px 0.5px; border-color: #7f7f7f #7f7f7f #7f7f7f #7f7f7f; padding: 0.0px 5.0px 0.0px 5.0px}
</style>
</head>
<body>

严重性 | 代码 | 说明 | 项目 | 文件 | 行 | 禁止显示状态
-- | -- | -- | -- | -- | -- | --
错误(活动) | E0992 | 命令行错误: 宏定义无效: '0_UNICODE' | wxhelper.dll (lib\wxhelper.dll) - x86-Debug | D:\02Code\04GitHub\wxhelper\src\dllMain.cc | 1 |  

</body>
</html>

**Comment by ttttupup** [comment]
这个是_UNICODE 这个宏，0应该是没注意带上去的，在cmake里修改一下即可。
