### ISSUE TITLE
楼主是个纯粹的人

### ISSUE THREAD

**Issue by sdydscj1** [ttttupup/wxhelper#253]
本人从事的行业需要机器人，于是在网络上大量查找、发现价格成百上千。
余幼时家贫，怀着节俭的目的自学 汇编、逆向、
看了大量视频，也学会了找call， 实现了基本的收发消息，
奈何白天打螺丝、晚上学习，实在无精力一直研究
遂兜兜转转  发现 了楼主的开源项目

为什么要单独发此层消息？

我用过不下于4-5款 易语言开发的接口
不是bug频繁、就是造成wx客户端卡顿、还有两款接口藏着掖着、需要另外付费

特别感谢楼主，也希望楼主开通赞助渠道。
 家贫，然则力强。

我也发现好多用户注入的问题，我自己编写了一款注入器，自我认为在win7-win11 都可以运行
额，刚注册github不久， 怎么能把这款注入器传给大家用呢。

哈哈，不会用github， 我放在百度网盘了 
链接：https://pan.baidu.com/s/1srjgNx3gqc2wcdhkuS-UOQ?pwd=i90m 
提取码：i90m
使用方法： 把dll  和注入exe 放在同一文件夹即可（仅支持wxhelper）
傻瓜式注入，无视任何微信版本，无视任何版本wxhelper
个人一点点微薄的力量，希望能帮助到大家

**Comment by caiyakang** [comment]
TMD,这是个病毒,大家小心了,盗取别人的steam

**Comment by sdydscj1** [comment]
牛逼，说我的程序是病毒，你学过编译没    知道打包怎么样会 被识别成病毒吗，真无语了，要不是看很多人都在说注入问题，我也不会分享我自己写的注入器

**Comment by caiyakang** [comment]
你这个要是病毒你全家死光光,盗了老子steam的装备,你个社会败类.

**Comment by caiyakang** [comment]
那些装备就当给你全家买棺材用

**Comment by sdydscj1** [comment]
智障一样的东西， 我的云盘链接文件 一直没动，让大家沙盒软件检测不就知道了？    玩个游戏的废物，什么证据都拿不出来，搁这叫唤

**Comment by sdydscj1** [comment]
这是源代码，你个弱智，我编译的exe还是用pyinstaller的， 可以直接反编译。垃圾东西，什么都不会  鬼叫
![818e0dee7f22b7e033c3eed345424e5](https://github.com/ttttupup/wxhelper/assets/141328434/0abba0bb-613f-40c4-8999-c2abf73214d0)

**Comment by sdydscj1** [comment]
所以你他妈会编程吗？  除了狗叫，还会什么？

**Comment by sdydscj1** [comment]
累了，他妈你反编译看下 源代码  不就知道是不是病毒了吗。  唉，在网上和废物吵架 真累
