### ISSUE TITLE
ConsoleApplication.exe 一直注入不成功,肯请楼主帮帮忙

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#254]
1.wxhelper-3.9.0.28-V13 可以注入成功,使用的命令如下:
D:\project\mtp\hook\wxhelper-3.9.0.28-V13\ConsoleInject.exe  -i WeChat.exe -p D:\project\mtp\hook\wxhelper-3.9.0.28-V13\wxhelper.dll

2.wxhelper-3.9.0.28-specify-port-V13 无法注入成功,使用命令如下:

2.1 使用 ConsoleInject.exe 注入器
D:\project\mtp\hook\wxhelper-3.9.0.28-specify-port-V13\ConsoleInject.exe  -i WeChat.exe -p D:\project\mtp\hook\wxhelper-3.9.0.28-specify-port-V13\wxhelper.dll -P 18888

![image](https://github.com/ttttupup/wxhelper/assets/12150755/75d6aca8-f72e-4ae1-9703-48f294d72a70)

2.2 使用 ConsoleApplication.exe  注入器
D:\project\mtp\hook\wxhelper-3.9.0.28-specify-port-V13\ConsoleApplication.exe  -i WeChat.exe -p D:\project\mtp\hook\wxhelper-3.9.0.28-specify-port-V13\wxhelper.dll -P 18888

![a341ddf1d4c02ccd25c8e3218280d25](https://github.com/ttttupup/wxhelper/assets/12150755/86a67709-3424-4939-bc61-f945189bb11c)

![e53e63ba475fce6283f24e1e0ef5495](https://github.com/ttttupup/wxhelper/assets/12150755/56ad7e5b-4f9f-4bac-9550-6714e7d9e475)

![7b51436de47b470d9fd0f37af583491](https://github.com/ttttupup/wxhelper/assets/12150755/cfc2d3c2-624a-4b44-add7-afca254973a7)

经百度查询需要安装Visual C++ Redistributable,也已经安装了,但是依然还是不行.
安装的地址是:
https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe

总结:
不一样的是,分别用了ConsoleInject.exe,ConsoleApplication.exe 我不知道这两个的区别是什么,因为楼主这两个提供的版本的注入器不一样.我感觉还是因为ConsoleApplication.exe这个注入器无法注入导致

弄了好久了,实现找不到办法解决了,希望楼主帮忙看一看,或者ConsoleApplication.exe 这个源码能否看一下.

**Comment by caiyakang** [comment]
换了wxhelper-3.9.2.23-v9里面的注入器,可以使用,可能还有问题,我在看一看

**Comment by Circlefork** [comment]
环境问题 直接从可以的电脑上面扣一份出来

**Comment by Circlefork** [comment]
吧这几个dll文件和注入器放一起就ok了

**Comment by caiyakang** [comment]
> 吧这几个dll文件和注入器放一起就ok了

DLL太多了，不知道要用哪几个

**Comment by liuyuays** [comment]
> > 吧这几个dll文件和注入器放一起就ok了
> 
> DLL太多了，不知道要用哪几个

兄弟你解决了吗？我也是这个问题，不知道咋搞了，求指导

**Comment by wangliguokaka** [comment]
哪里有 weixin 3.9.2.23 版本的安装包
