### ISSUE TITLE
wxhelper-3.9.0.28-specify-port-V13 注入之后，无法卸载，请问如何解决.

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#256]
成功注入之后，
使用D:\project\mtp\hook\wxhelper-3.9.0.28-specify-port-V13\ConsoleInject.exe -u WeChat.exe -d wxhelper.dll 进行卸载，发现里面的dll还注存在里面
![image](https://github.com/ttttupup/wxhelper/assets/12150755/8ea26275-9116-45b8-a160-6e316ce2f8ad)
请问有什么办法可以完全卸载，主要是取消http的端口监听。

**Comment by caiyakang** [comment]
卸载失败很大可能原因是因为这个dll启动了HTTP监听，那怎么样可能停止这个HTTP监听了？

**Comment by caiyakang** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/12150755/8cadf061-d11d-4854-a189-df1afe8f9629)

**Comment by ttttupup** [comment]
仔细看文档，隐藏dll的就无法卸载
