### ISSUE TITLE
wxhelper-3.9.2.23-v9 注入器和源码不对应

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#258]
https://github.com/ttttupup/wxhelper/archive/refs/tags/3.9.2.23-v9.zip 

1.这个里面的注入器是，ConsoleInject.exe 但源码却是ConsoleApplication.cc，请问能否提供一个 ConsoleInject.exe对应的源码？
2.感觉有点乱了，有时候是ConsoleInject.exe ，有时候是ConsoleApplication.exe ,

**Comment by ttttupup** [comment]
同一个东西，改了名字而已
