### ISSUE TITLE
图片消息不存在

### ISSUE THREAD

**Issue by sdydscj1** [ttttupup/wxhelper#259]
楼主大佬，我用的是3.9.2.23  v8 

hook图片消息 中的path 路径 传给 48接口  解密下载图片。
可是我发现 接收到的消息虽然有xx.dat  但是这个.dat文件 在指定的Image文件夹下 并未生成，

如果想让.dat文件生成，只能在聊天窗口点击一下图片 才会生成（我开启了微信自动下载图片一样）

那这样 岂不是没有办法 自动下载图片了吗？  

求解

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/issues/43

**Comment by sdydscj1** [comment]
感谢大佬，原来是这样， 大佬开个赞赏呗，绵薄之力，还请笑纳。

**Comment by sdydscj1** [comment]
这图片搞的我越来越懵逼了，， 我从一开始就是调用下载消息附件的接口 下载图片。  可是发现下载的图片(png) 应该是加密的  打不开

于是用解码接口 ，果然就可以对加密的图片  解开成正确的图片(jpg)

然后我就 封装了 两个函数，1下载消息附件、2解码图片。

神奇的事情来了，， 我刚运行，1下载消息附件， 图片(png) 又是正常的了！！！ 不加密了

这是什么鬼，太难了[苦涩]........

**Comment by Esword618** [comment]
@ttttupup 大佬用的什么软件进行逆向分析的，我也想试试，加入进来
