### ISSUE TITLE
能否增加发xml消息、通过加好友请求、邀请好友进群呢？

### ISSUE THREAD

**Issue by luochaolun** [ttttupup/wxhelper#26]
能否增加发xml消息、通过加好友请求、邀请好友进群呢？

**Comment by ttttupup** [comment]
看个人时间

**Comment by lovezm** [comment]
插一嘴，能不能hook语音消息文件的，chatgpt出语音转文字了，想接入一下

**Comment by xisuo67** [comment]
插一嘴，能否增加分享好友的功能？或者加个projects，列一个开发计划，看看有什么能帮助到作者的

**Comment by ttttupup** [comment]
> 

直接提pr就行，没什么计划，你感兴趣的就行。

**Comment by Ulysses0817** [comment]
太强了，closed，大佬这是马上又要更新功能啦！🚀🚀🚀
