### ISSUE TITLE
ConsoleInject源码能提供吗

### ISSUE THREAD

**Issue by lcl101** [ttttupup/wxhelper#27]
ConsoleInject源码能提供吗

**Comment by lcl101** [comment]
另外我调用这个一直注入不成功呢，具体怎么用呢？

**Comment by ttttupup** [comment]
源码没了，就是常规的注入程序，可以用图形界面的试一下。injector.dll就是主要的注入程序。

**Comment by ttttupup** [comment]
你看下#8 可以直接逆向出来。

**Comment by lcl101** [comment]
> 你看下#8 可以直接逆向出来。

收到，感谢
