### ISSUE TITLE
跪求“语音转文字”功能

### ISSUE THREAD

**Issue by jamesliu668** [ttttupup/wxhelper#270]
目前可以成功获取语音文件，研究了很久如何实现收到语音以后直接调用“语音转文字”功能，失败无数次了。
请大佬帮忙，谢谢！

**Comment by jamesliu668** [comment]
有了解的兄弟能看看这个功能么？本人技术太菜，调试了好几个方向都不行。谢谢了

**Comment by ttttupup** [comment]
多试试就出来了

**Comment by qwe159357890** [comment]
自动自动语音转文字 然后在数据库里面就有

**Comment by jamesliu668** [comment]
> 多试试就出来了

谢谢大佬回复，我再试试。

**Comment by jamesliu668** [comment]
> 自动自动语音转文字 然后在数据库里面就有

嗯，目前我也用这个方法。我找几个人同时给一个微信发语音消息，发现有些语音没有自动文字。你遇到过这种情况么？

**Comment by ttttupup** [comment]
可以把silk文件导入到自己的模型里进行转换，不用受限于微信

**Comment by jamesliu668** [comment]
> 可以把silk文件导入到自己的模型里进行转换，不用受限于微信

谢谢大佬回复。目前看也只能通过把silk文件导出来然后使用其他模型转换。之前用了微信自动语音转文字，最大的问题是，只有当前界面里选中的好友语音才会转，其他好友发来的就不会自动转文字了。另外，高并发的情况，也不会自动转文字。

**Comment by ttttupup** [comment]
3.9.5.81的偏移0x1058840，转换语音的call

**Comment by kanadeblisst00** [comment]
> 3.9.5.81的偏移0x1058840，转换语音的call

找了一天，不如大佬给的一个偏移

**Comment by jamesliu668** [comment]
> 3.9.5.81的偏移0x1058840，转换语音的call

感谢大佬，调试了一个下午。分别看了3.8和3.9.5.81。以3.9.5.81为例，在x64dbg中看到这个call之前，没有非常明显的参数传进来。下图分别是rax和rbx的值，都不是语音相关参数。所以，我的理解是，要进入到0x1058840这个call里面在去构建参数和调用是么？
<img width="960" alt="rax" src="https://github.com/ttttupup/wxhelper/assets/4152618/33c728c2-635a-44c2-856e-aaeb566f53a7">
<img width="960" alt="rbx" src="https://github.com/ttttupup/wxhelper/assets/4152618/caa356a5-e7f2-47a8-8005-695add0c5580">

**Comment by ttttupup** [comment]
3.9.8.25增加了语音转换，自己参考吧

**Comment by jamesliu668** [comment]
> 3.9.8.25增加了语音转换，自己参考吧

谢谢
