### ISSUE TITLE
dll缺失疑问

### ISSUE THREAD

**Issue by clippers1** [ttttupup/wxhelper#273]
![图片](https://github.com/ttttupup/wxhelper/assets/23101116/a59f4db4-17a6-4b6d-91e1-a6d12ebcab51)
这个 **PDMUTILITIES.DLL** 搜不到

还有上面那些ext-xxx / api-xxx的dll缺失要不要管

**Comment by clippers1** [comment]
close

**Comment by clippers1** [comment]
🤦‍♂️

**Comment by skx12138** [comment]
兄弟请问解决了吗，我也有这个问题
