### ISSUE TITLE
3.9.5.81 的发送小程序功能看到接口已经有了，但是注入的ddl是不是没更新，能不能搞个最新的ddl

### ISSUE THREAD

**Issue by wangxy496** [ttttupup/wxhelper#275]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangxy496** [comment]
v10版本可以了

**Comment by yxl123458** [comment]
大佬请问下小程序转发接口的appletId是微信小程序的appid吗？
