### ISSUE TITLE
wxhelper.dll是如何得到的呢

### ISSUE THREAD

**Issue by 835588741** [ttttupup/wxhelper#276]
因为之前没有接触过，比较陌生，不知道这个wxhelper.dll是如何生成的，项目也中没有看到release文件夹

**Comment by clippers1** [comment]
![图片](https://github.com/ttttupup/wxhelper/assets/23101116/a9473ace-2bae-4253-a098-8e3744800d1f)

**Comment by 835588741** [comment]
Thanks

**Comment by clippers1** [comment]
我还卡在dll缺失，虽然注册成功，但是无http服务

**Comment by 835588741** [comment]
E:\wx\WeChat\[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll

我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问

**Comment by 835588741** [comment]
> 我还卡在dll缺失，虽然注册成功，但是无http服务

E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll

我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问

**Comment by clippers1** [comment]
> > 我还卡在dll缺失，虽然注册成功，但是无http服务
> 
> E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> 
> 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问

要启动wechat，

**Comment by 835588741** [comment]
> > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > 
> > 
> > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> 
> 要启动wechat，

微信启动着的

**Comment by clippers1** [comment]
> > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > 
> > > 
> > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > 
> > 
> > 要启动wechat，
> 
> 微信启动着的

估计和我一样 dll环境有问题

**Comment by 835588741** [comment]
> > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > 
> > > > 
> > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > 
> > > 
> > > 要启动wechat，
> > 
> > 
> > 微信启动着的
> 
> 估计和我一样 dll环境有问题
injector.dll 这个你们有用到吗，没有看到在哪用

**Comment by 835588741** [comment]
> > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > 
> > > > 
> > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > 
> > > 
> > > 要启动wechat，
> > 
> > 
> > 微信启动着的
> 
> 估计和我一样 dll环境有问题

3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796  注入结果：1

**Comment by clippers1** [comment]
> > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > 
> > > > > 
> > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > 
> > > > 
> > > > 要启动wechat，
> > > 
> > > 
> > > 微信启动着的
> > 
> > 
> > 估计和我一样 dll环境有问题
> 
> 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1

有http服务么

**Comment by 835588741** [comment]
> > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > 
> > > > > > 
> > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > 
> > > > > 
> > > > > 要启动wechat，
> > > > 
> > > > 
> > > > 微信启动着的
> > > 
> > > 
> > > 估计和我一样 dll环境有问题
> > 
> > 
> > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> 
> 有http服务么

很遗憾，没有，，，

**Comment by clippers1** [comment]
> > > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > > 
> > > > > > > 
> > > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > > 
> > > > > > 
> > > > > > 要启动wechat，
> > > > > 
> > > > > 
> > > > > 微信启动着的
> > > > 
> > > > 
> > > > 估计和我一样 dll环境有问题
> > > 
> > > 
> > > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> > 
> > 
> > 有http服务么
> 
> 很遗憾，没有，，，

还是环境问题

**Comment by 835588741** [comment]
> > > > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > > > 
> > > > > > > > 
> > > > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > > > 
> > > > > > > 
> > > > > > > 要启动wechat，
> > > > > > 
> > > > > > 
> > > > > > 微信启动着的
> > > > > 
> > > > > 
> > > > > 估计和我一样 dll环境有问题
> > > > 
> > > > 
> > > > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> > > 
> > > 
> > > 有http服务么
> > 
> > 
> > 很遗憾，没有，，，
> 
> 还是环境问题

搞不懂了，没头绪，兄弟你要是弄明白了，苟富贵勿相忘，记得@我哈哈

**Comment by clippers1** [comment]
> > > > > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 要启动wechat，
> > > > > > > 
> > > > > > > 
> > > > > > > 微信启动着的
> > > > > > 
> > > > > > 
> > > > > > 估计和我一样 dll环境有问题
> > > > > 
> > > > > 
> > > > > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> > > > 
> > > > 
> > > > 有http服务么
> > > 
> > > 
> > > 很遗憾，没有，，，
> > 
> > 
> > 还是环境问题
> 
> 搞不懂了，没头绪，兄弟你要是弄明白了，苟富贵勿相忘，记得@我哈哈


不是做c / c++开发的 本地少了很多dll文件。出了问题也不知道排查，只能仰仗有缘人了。

**Comment by 835588741** [comment]
> > > > > > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 要启动wechat，
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 微信启动着的
> > > > > > > 
> > > > > > > 
> > > > > > > 估计和我一样 dll环境有问题
> > > > > > 
> > > > > > 
> > > > > > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> > > > > 
> > > > > 
> > > > > 有http服务么
> > > > 
> > > > 
> > > > 很遗憾，没有，，，
> > > 
> > > 
> > > 还是环境问题
> > 
> > 
> > 搞不懂了，没头绪，兄弟你要是弄明白了，苟富贵勿相忘，记得@我哈哈
> 
> 不是做c / c++开发的 本地少了很多dll文件。出了问题也不知道排查，只能仰仗有缘人了。

3.9.0.28我成功一半了，http api可以用了，但是socket还是收不到监听的消息

**Comment by 835588741** [comment]
> > > > > > > > > > > > 我还卡在dll缺失，虽然注册成功，但是无http服务
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll
> > > > > > > > > > > 我的并不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 要启动wechat，
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 微信启动着的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 估计和我一样 dll环境有问题
> > > > > > > 
> > > > > > > 
> > > > > > > 3.9.2.23-v9，刚刚试了可以：dll inject successdll path : C dll path : 8796 注入结果：1
> > > > > > 
> > > > > > 
> > > > > > 有http服务么
> > > > > 
> > > > > 
> > > > > 很遗憾，没有，，，
> > > > 
> > > > 
> > > > 还是环境问题
> > > 
> > > 
> > > 搞不懂了，没头绪，兄弟你要是弄明白了，苟富贵勿相忘，记得@我哈哈
> > 
> > 
> > 不是做c / c++开发的 本地少了很多dll文件。出了问题也不知道排查，只能仰仗有缘人了。
> 
> 3.9.0.28我成功一半了，http api可以用了，但是socket还是收不到监听的消息

解决了，client里mian调用下hook_msg后tcp就可以接受到消息了

**Comment by clippers1** [comment]
我用3.9.5.81的注入器 注入3.9.2.23的版本。可用，有19088，但是没有socket接受消息

**Comment by qianqian1530** [comment]
有没有微信群, 或者qq群. 一起讨论一下..
