### ISSUE TITLE
3.9.5.81-v10 用过界面注入的exe启动微信，微信扫码登录或，exe就会闪退

### ISSUE THREAD

**Issue by 835588741** [ttttupup/wxhelper#277]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangxy496** [comment]
还是用命令行吧，用命令行就没那么多问题

**Comment by 835588741** [comment]
> 还是用命令行吧，用命令行就没那么多问题

E:\wx\WeChat[3.9.5.81]>ConsoleInject.exe -i WeChat.exe -p wxhelper.dll

是不会报错，但是没有反馈的响应，我看其他人都说会有 1或0的返回结果，但是我执行完后没有任何显示，19088也无法访问

**Comment by wangxy496** [comment]
你用全路径注册试下 ，v10版本我刚试的 可以正常注入，开启http服务，E:\wxhelper-3.9.5.81-v10\tool\injector\ConsoleApplication.exe -i WeChat.exe -p E:\wxhelper-3.9.5.81-v10\tool\injector\wxhelper.dll，注入完 看下端口有没有正常监听，netstat -ano | findstr '微信pid'

**Comment by 835588741** [comment]
> 你用全路径注册试下 ，v10版本我刚试的 可以正常注入，开启http服务，E:\wxhelper-3.9.5.81-v10\tool\injector\ConsoleApplication.exe -i WeChat.exe -p E:\wxhelper-3.9.5.81-v10\tool\injector\wxhelper.dll，注入完 看下端口有没有正常监听，netstat -ano | findstr '微信pid'
一样的效果，全路径也是没有任何反馈

**Comment by wangxy496** [comment]
微信登录了没

**Comment by 835588741** [comment]
> 微信登录了没

登陆着

**Comment by 835588741** [comment]
> 微信登录了没

injector.dll 这个你们有用到吗，没有看到在哪用

**Comment by wangxy496** [comment]
我没用 我用的那个wxhelper.ddl

**Comment by tlxfif** [comment]
是不是微信你下载成了64位版本的了，要32位才行吧

**Comment by plusls** [comment]
可能是没有权限，注入dll后会在微信目录的 logs/xxxx.log写入日志，如C:\Program Files (x86)\Tencent\WeChat\[3.9.5.81]\logs\daily_2023-09-13.txt
