### ISSUE TITLE
作者请问可以把发送小程序的jsonParam的具体参数再明确下吗？

### ISSUE THREAD

**Issue by wangxy496** [ttttupup/wxhelper#278]
"jsonParam": "{\"current_path\":\"\",\"current_title\":\"123\",\"image_url\":\"\",\"scene\":1001,\"scene_note\":\"\",\"sessionId\":\"123\"}"
这几个参数确实不清楚都有什么作用，发送完小程序，可以发送，就是小程序的名称和title不显示，这几个参数都试过了，不知道怎么定义小程序的名称和title，恳请明确下参数明细

**Comment by ttttupup** [comment]
这个最好本地先操作一下，保证本地已经有了小程序的信息。这个功能不是很完善，这些数据都是页面js操作回调回来的数据。找到这个查询call就方便了。

**Comment by wangxy496** [comment]
> 这个最好本地先操作一下，保证本地已经有了小程序的信息。这个功能不是很完善，这些数据都是页面js操作回调回来的数据。找到这个查询call就方便了。

本地操作过了，就是小程序的title和content无法进行设置，显示不出来，就只显示小程序三个字
![image](https://github.com/ttttupup/wxhelper/assets/58056894/dca8e3cd-ebbe-49a6-968b-74f83aafea5d)

**Comment by wangxy496** [comment]
@ttttupup 正常的应该是这样的，
![image](https://github.com/ttttupup/wxhelper/assets/58056894/22c44a97-ac24-4ad6-86dd-69fac6097869)

**Comment by HyperClockUp** [comment]
请问参数具体在哪获取呢？我在hookMsg拿到的xml中好像没有看到对应的参数
