### ISSUE TITLE
请教一下注入后源码是如何调用远程方法的.

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#283]
使用注入工具注入wxhelper.dll，是如何调用远程的HTTP启动方法的.
我在注入工具源码里面找到了http_start ，但是在wxhelper里面并没有找到http_start 这个方法，请教一下楼主是如何实现的。
![image](https://github.com/ttttupup/wxhelper/assets/12150755/d2f1c09a-ca29-4aa0-9e6f-9a7af6e6094d)

如果是通过这个实现的，那注入器里面的http_start是做什么用的呢
![image](https://github.com/ttttupup/wxhelper/assets/12150755/8ecfa2eb-2152-4656-89df-fbd7a1abb655)

**Comment by ttttupup** [comment]
x86的可以暴露http_start方法给外部直接调用。x64的直接注入后自己调用，不需要外部调用了。

**Comment by caiyakang** [comment]
> x86的可以暴露http_start方法给外部直接调用。x64的直接注入后自己调用，不需要外部调用了。

我在你的wxhelper源码里面没有找到http_start 这个方法呢

**Comment by ttttupup** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/31303661/0b934845-775e-46a3-9f1d-3bcc7fcb862a)
