### ISSUE TITLE
3.9.5.81-v10  hookSyncMsg 

### ISSUE THREAD

**Issue by zhupanonline** [ttttupup/wxhelper#286]
def hookSyncMsg():
    url = "http://127.0.0.1:19088/api/hookSyncMsg"
    print("modify ip port url ")
    # raise RuntimeError("modify ip port url then deleted me")
    payload = json.dumps({
        "port": "19099",
        "ip": "http://127.0.0.1",
        "url": "http://localhost:8888",
        "timeout": "3000",
        "enableHttp": "1"
    })
    headers = {
        'Content-Type': 'application/json'
    }
    response = requests.request("POST", url, headers=headers, data=payload)
    print(response.text)

其他都正常，可以获取信息，可以发送消息，但是一运行hookSyncMsg 就抛错，是个什么情况？

**Comment by zhupanonline** [comment]
微信直接闪退，程序报错。
 File "http_client.py", line 494, in <module>
    hookSyncMsg()
  File "http_client.py", line 80, in hookSyncMsg
    response = requests.request("POST", url, headers=headers, data=payload)
  File "C:\soft\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\soft\Python36\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\soft\Python36\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\soft\Python36\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by zhupanonline** [comment]
求大神帮忙，感谢

**Comment by ttttupup** [comment]
需要启动http服务端

**Comment by zhupanonline** [comment]
@ttttupup 大佬，我是启动了http服务的，而且单独调用http服务是可以请求通的。我怀疑是注入的时候有点问题，因为我使用，
C:\soft\Tencent\WeChat>ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll
dll inject successdll path : w dll path : 1468  注入结果：1

C:\soft\Tencent\WeChat>ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll
 注入结果：0

C:\soft\Tencent\WeChat>ConsoleApplication.exe -i WeChat.exe -p wxhelper.dll
dll inject successdll path : w dll path : 932  注入结果：1

C:\soft\Tencent\WeChat>ConsoleApplication.exe -u WeChat.exe -p wxhelper.dll
 卸载结果：1

C:\soft\Tencent\WeChat>netstat -ano | findstr 932
  TCP    0.0.0.0:19088          0.0.0.0:0              LISTENING       932
  TCP    0.0.0.0:49672          0.0.0.0:0              LISTENING       4932
  TCP    127.0.0.1:8680         0.0.0.0:0              LISTENING       932
  TCP    192.168.3.119:53161    120.233.22.42:80       ESTABLISHED     932
  TCP    [::]:49672             [::]:0                 LISTENING       4932
  卸载是不起作用的，使用：ConsoleApplication.exe -u WeChat.exe -d wxhelper.dll
 卸载结果：0
 发送消息，获取信息，hook日志，都没啥问题，唯独hookSyncMsg，就报错，然后微信闪退。使用其他版本的dll，曾经成功过一次。使用V8以上的dll，基本都是hookSyncMsg必挂。
 感谢大佬百忙中的解答。我会再次检查所有配置尝试。

**Comment by neugle** [comment]
payload = json.dumps({
"port": 19099,             //去掉双引号
"ip": "127.0.0.1",            // 不要加 http://
"url": "http://127.0.0.1:8000/api",       //写服务端真实地址(一定要启动demo中的服务端)，注意写对路径
"timeout": 3000,                //去掉双引号
"enableHttp": 1                //去掉双引号
})
