### ISSUE TITLE
求一个 3.9.5.81 32位版本的安装包

### ISSUE THREAD

**Issue by tlxfif** [ttttupup/wxhelper#287]
求一个 3.9.5.81 32位版本的安装包
感谢各位，我找半天没找到:)

**Comment by plusls** [comment]
https://dldir1.qq.com/weixin/Windows/WeChat_3.9.5_update81.zip

**Comment by tlxfif** [comment]
> https://dldir1.qq.com/weixin/Windows/WeChat_3.9.5_update81.zip

这是64位的吧，请问下32位的有吗？因为我hook闪退了，感谢：）

**Comment by tlxfif** [comment]
@ttttupup 大佬请问下您这个3.9.5.81版本的dll只针对32版本吗？

**Comment by ttttupup** [comment]
是的
