### ISSUE TITLE
学习源码中，遇到点问题请教一下。

### ISSUE THREAD

**Issue by caiyakang** [ttttupup/wxhelper#293]
注入器中有这一样段代码，但不道是做什么用的，指点一下：
![image](https://github.com/ttttupup/wxhelper/assets/12150755/ac14def9-6d42-4d2a-bf7f-73450b214d5f)

![image](https://github.com/ttttupup/wxhelper/assets/12150755/30aada8f-d13a-44c5-809f-5f3a99a03da2)

这段功能主要是实现什么目的

**Comment by ttttupup** [comment]
检查dll是否正常加载成功，判断函数是否可以调用
