### ISSUE TITLE
[3.9.5.81]如何让图片自动加载，不需要点击

### ISSUE THREAD

**Issue by SwaggyMacro** [ttttupup/wxhelper#296]
想实现监听消息自动转发，但是图片的话有以下问题：
1. 如果使用downloadAttach的话有时候图片是需要解码的有时候是不需要的，并且有时候会触发 问题3
2. 而且有时候图片解码会失败（重复发一次相同的图片就可以解码成功）
3. 有时候图片会转发失败，但返回还是success，看了客户端是一直卡在上传中
    
![image](https://user-images.githubusercontent.com/38845682/270224383-cb579d85-85a0-46b9-831d-df0376c516b3.png)

**但是如果在客户端中手动点击消息加载图片，然后再调用forwardMsg就可以成功转发图片，而且不会出现图片卡上传的情况。**

看到有相同提问的issue，但是似乎没有解决方案?

> 图片现在不会自动下载，后台有个空闲下载的任务，不点不会主动下载

_Originally posted by @ttttupup in https://github.com/ttttupup/wxhelper/issues/43#issuecomment-1451936860_

**Comment by ttttupup** [comment]
把文件正常下载下来就可以了

**Comment by SwaggyMacro** [comment]
先是调用的downloadAttach下载图片，然后等待图片下载完成后才去进行图片解码，最后再转发的图片，但有时候还是会漏一张或者下载以及解码均正常，但转发消息出来是.dat
![image](https://github.com/ttttupup/wxhelper/assets/38845682/d4f24238-b333-4a9d-94dd-50e688c161d5)

**Comment by SwaggyMacro** [comment]
如果不调用downloadAttach下载图片也不调用decodeImage而是采用手动点击下载的话就不会有这些问题 可以正常转发消息 @ttttupup

**Comment by ttttupup** [comment]
转发功能不需要解码图片，下载成功即可。转发失败就是因为本地没有下载成功。
