### ISSUE TITLE
Win10系统通过命令行代码注入之后提示1，但是微信闪退了，这是啥原因

### ISSUE THREAD

**Issue by cumtzhangtian** [ttttupup/wxhelper#298]
[3.9.5.81-v10](https://github.com/ttttupup/wxhelper/releases/tag/3.9.5.81-v10)
3.9.5.81－Ｖ１０版本
通过客户端注入的时候，如果微信登录着，客户端会直接闪退，求大佬指导！

**Comment by hgh741** [comment]
试下用管理员权限启动微信

**Comment by ttttupup** [comment]
版本和权限检查一下
