### ISSUE TITLE
删除好友一直pending

### ISSUE THREAD

**Issue by DuGuYifei** [ttttupup/wxhelper#301]
3.9.2.23版本微信，使用 `/?type=17` 进行删除好友，一直pending，删不了。尝试了3.9.2.23 `v9`和`v5`的 wxhelper.dll都不行。请问能看一看什么原因吗？

**Comment by ttttupup** [comment]
删除好友应该是有点问题的，只是本地删除了。这个功能没继续完善。

**Comment by DuGuYifei** [comment]
谢谢回复~，请问能完善一下吗？就在您最新的3.9.2.23上完善一下可以吗？它现在不止是本地不删，好像请求会一直不回复，hhh
