### ISSUE TITLE
/api/execSql 大部分表不能查询。

### ISSUE THREAD

**Issue by egotom** [ttttupup/wxhelper#304]
例如 select * from MSG; 
返回：
{
  "code": 0,
  "data": [],
  "msg": "no data"
}

select * from Contact; 能正常返回。

**Comment by egotom** [comment]
环境window 10 微信版本 3.9.5.81

**Comment by egotom** [comment]
http://localhost:19099/api/hookSyncMsg
这个接口运行几分钟之后就停掉了，不再转发消息。wxhelper.dll能输出出错日志就好了。

**Comment by ttttupup** [comment]
MSG表是MSGX（MSG0，MSG1...）库下面的表，确保传的句柄是正确的
