### ISSUE TITLE
3.9.5.81注入报 应用程序无法启动 0xc000007b

### ISSUE THREAD

**Issue by hanwei88** [ttttupup/wxhelper#306]
![image](https://github.com/ttttupup/wxhelper/assets/93665931/baeb3eb0-0295-4686-9e34-c6eaa78c1478)

执行命令:
ConsoleApplication.exe -i "D:\Program Files\Tencent\WeChat\[3.9.5.81]\WeChat.exe" -p "D:\wechat\wxhelper.dll"

使用微信注入器闪退
![image](https://github.com/ttttupup/wxhelper/assets/93665931/deca13a1-f60c-4dfc-bd87-caa4e8437e35)

**Comment by timersun** [comment]
换个注入器   
https://github.com/nefarius/Injector
这个可以注入

**Comment by hanwei88** [comment]
> 换个注入器 https://github.com/nefarius/Injector 这个可以注入
试了下还是b不行

![image](https://github.com/ttttupup/wxhelper/assets/93665931/0c22f8e0-ecb2-4189-9977-be7034cb0fd3)

**Comment by SnapdragonLee** [comment]
你这个是没找到进程，进程名字直接写 WeChat.exe 或者写入通过指令/任务管理器查找 WeChat.exe 的 PID 都是可以的

**Comment by hanwei88** [comment]
用injector注入成功微信就闪退
![image](https://github.com/ttttupup/wxhelper/assets/93665931/f5c8c124-5f0d-46aa-80eb-1945d4a841c5)

**Comment by SnapdragonLee** [comment]
用管理员启动微信
