### ISSUE TITLE
3.9.2.23 显示注入成功，端口已打开，访问所有接口 404 错误

### ISSUE THREAD

**Issue by godisboy0** [ttttupup/wxhelper#307]
> .\ConsoleInject.exe -i WeChat.exe -p .\injector.dll
dll inject successdll path : . dll path : 9792  注入结果：1
>  netstat -ano | findstr 'LISTENING'
 127.0.0.1:8680         0.0.0.0:0              LISTENING       9792

import requests

url = 'http://127.0.0.1:8680/api/?type=0'

res = requests.post(url)

print(res.status_code)  # 结果是404

**Comment by Thick-z** [comment]
> > .\ConsoleInject.exe -i WeChat.exe -p .\injector.dll
> > dll inject successdll path : . dll path : 9792  注入结果：1
> > netstat -ano | findstr 'LISTENING'
> > 127.0.0.1:8680         0.0.0.0:0              LISTENING       9792
> 
> import requests
> 
> url = 'http://127.0.0.1:8680/api/?type=0'
> 
> res = requests.post(url)
> 
> print(res.status_code) # 结果是404

换一个注入器：微信DLL注入器V1.0.3.exe
命令行工具似乎有bug反回的结果太准确

**Comment by godisboy0** [comment]
> > > .\ConsoleInject.exe -i WeChat.exe -p .\injector.dll
> > > dll inject successdll path : . dll path : 9792  注入结果：1
> > > netstat -ano | findstr 'LISTENING'
> > > 127.0.0.1:8680         0.0.0.0:0              LISTENING       9792
> > 
> > 
> > import requests
> > url = 'http://127.0.0.1:8680/api/?type=0'
> > res = requests.post(url)
> > print(res.status_code) # 结果是404
> 
> 换一个注入器：微信DLL注入器V1.0.3.exe 命令行工具似乎有bug反回的结果太准确

谢谢，我试试哈~

**Comment by godisboy0** [comment]
虽然还没成功，但至少发现8680端口是微信自己打开的一个接口，不是dll的端口，所以访问不上。所以我的症状是显示注入成功但实际上端口未启动……
