### ISSUE TITLE
能在getContactList里获得用户性别，备注，描述，标签之类的吗

### ISSUE THREAD

**Issue by DuGuYifei** [ttttupup/wxhelper#310]

**Comment by ttttupup** [comment]
这个接口返回的内容挺多的，没仔细研究具体有哪些。标签和备注也是有地方获取的，不常用没实现。

**Comment by DuGuYifei** [comment]
> 这个接口返回的内容挺多的，没仔细研究具体有哪些。标签和备注也是有地方获取的，不常用没实现。

标签备注可以用数据库去搜，返回内容里没得性别，城市和描述，hhhhh。感觉性别和描述还是挺常用的，请问能方便实现吗？
