### ISSUE TITLE
【求助】3.9.5.81-v10版本下载附件失败

### ISSUE THREAD

**Issue by drag0n-app** [ttttupup/wxhelper#317]
1、在群中发了一条图片消息，hook消息显示"msgId"为7559968399427434000
2、POST数据{"msgId":7559968399427434000}到接口/api/downloadAttach
3、返回{ code: -2, data: null, msg: "success" }

请问是什么原因？

**Comment by vincentlin7** [comment]
还没有下载完，间隔一段时间再post

**Comment by ttttupup** [comment]
这个msgid应该是错的，注意一下精度问题。

**Comment by ttttupup** [comment]
浮点数精度问题

**Comment by HyperClockUp** [comment]
参数使用字符串类型依然无法正常下载
`{
  "msgId": "4626693398161714176"
}
`

使用curl命令依旧失败，其他的都是正常的
`
curl -X POST -H "Content-Type: application/json" -d '{"msgId": 4626693398161714176}' http://192.168.31.222:19088/api/downloadAttach
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    70  100    40  100    30   5134   3850 --:--:-- --:--:-- --:--:-- 10000{"code":-2,"data":null,"msg":"success"}
`
