### ISSUE TITLE
引用消息定位

### ISSUE THREAD

**Issue by Esword618** [ttttupup/wxhelper#320]
<img width="148" alt="image" src="https://github.com/ttttupup/wxhelper/assets/73058062/cad7159d-0102-40d3-a9f1-e0b831355ad9">

如图，我上面发了一张图片，下面回复了ok，但是我怎么可以通过ok定位这个图片是哪个呢？

**Comment by liupeng176** [comment]
看看数据库里面的关系把  别发ok，发个特殊意义且不重复的值试试呢   比如hfgdfhfdhfddfdf

**Comment by Esword618** [comment]
这个查询怎么查，不太懂

**Comment by liupeng176** [comment]
通过http接口，执行sql语句  我看api有可以执行sql的api接口   6查询数据库信息，7执行数据库sql语句。

**Comment by Esword618** [comment]
好的，感谢
