### ISSUE TITLE
有懂逆向汇编的老哥吗

### ISSUE THREAD

**Issue by liupeng176** [ttttupup/wxhelper#321]
3.9.5.81V10,orc识别图片为文字,第一行会漏掉。有哪位老哥能帮着解决下。
我用一个4行文本的图片测试,这里的number是正确的4,里面的for循环输出i值为0,1,2 看上去少执行了一次，但是如果简单修改for循环的判断条件让程序继续执行 输出i值为0,1,2,3  ,i到3就会崩溃 有哪个老哥知道怎么回事吗 由于不懂逆向和汇编只能在这里求助了
附编译过程:https://github.com/ttttupup/wxhelper/issues/316

附ocr相关部分代码:
![image](https://github.com/ttttupup/wxhelper/assets/102396559/61300f87-fca7-4ef5-a685-6573a051fd3b)

**Comment by liupeng176** [comment]
@ttt602 @ttttupup @sglmsn

**Comment by ttttupup** [comment]
看一下list->start 是不是正确的起始位置，这个vector debug编译是4个指针，release是三个，检查一下就知道了，debug环境下会指向第list head。 这个功能当初测试的时候没有发现不正确的情况。现在没这个版本了，后续版本再更新吧。

**Comment by liupeng176** [comment]
我看了下,现在可以用的最新的版本就是这个V3.9.5.81-v10的版本了，下一个版本应该是3.9.7.29把 好像差的还挺多呢,没这个版本是没有这个版本的下载地址吗？附3.9.5.81下载链接(https://soft.3dmgame.com/down/258342.html) ，我测试时候也没发现问题，因为如果多行的话，只漏掉第一行不容易注意到，但是问题确实真实存在,我一开始以为manager.cc里面的代码问题，尝试修改自己编译dll,但是后面发现不是这么简单，可能还是跟取的地址或偏移有关， 大佬抽空帮忙处理下这个问题吧 这个功能真的挺重要的，留下你的加密货币地址，我可以给你打赏几杯咖啡喝。

**Comment by ttttupup** [comment]
这种ocr功能一大堆开源模型，稍微训练一下就能用了，没必要用微信的。

**Comment by liupeng176** [comment]
我用了几个开源的,效果不行之后才转到这里的，
1.不自己训练模型根本不能用,模型覆盖不全不能用,字库问题...太难了,而且效果不好
2.容错率太低了,有些字迹太模糊 识别出错率非常高。
用某x信这个他们适用了大多数场景,个人感觉是比商用的效果都还要好。  不然我也不会苦苦折腾这个玩意了

**Comment by liupeng176** [comment]
@ttttupup  烦请抽空帮忙解决下这个问题呀老哥  被难到了
