### ISSUE TITLE
获取登录二维码以及界面【进入微信】的hook点

### ISSUE THREAD

**Issue by atorber** [ttttupup/wxhelper#324]
在打开微信客户端之后即开始通过接口操作登录，首次登录时需获取二维码，之后登录时需调用界面的【进入微信】按钮直接登录

如果这两个hook点实现了，我们可以在开机自动启动微信客户端然后远程扫码或确认进行登录

**Comment by ttttupup** [comment]
二维码有实现，进入微信没有实现

**Comment by atorber** [comment]
> 二维码有实现，进入微信没有实现

1.  获取二维码是这个方法吗？
string AccountMgr::GetLoginUrl() {
  DWORD login_url_addr = base_addr_ + WX_LOGIN_URL_OFFSET;
  return "http://weixin.qq.com/x/" + std::string(reinterpret_cast<char*>(*(DWORD*)login_url_addr));
}
2. 进入微信可以考虑一下，实现了这两个hook点意味着可以构建自动化程序来启动和登录微信了，发生微信退出或机器重启时可以自动化登录，很酷
3. 另外安利一下我们的wehcaty-puppet-xp项目，使用frida实现的win版微信机器人，我正在尝试将wxhelper项目里功能移植到xp https://github.com/wechaty/puppet-xp

**Comment by ttttupup** [comment]
> > 二维码有实现，进入微信没有实现
> 
> 1. 获取二维码是这个方法吗？
>    string AccountMgr::GetLoginUrl() {
>    DWORD login_url_addr = base_addr_ + WX_LOGIN_URL_OFFSET;
>    return "http://weixin.qq.com/x/" + std::string(reinterpret_cast<char*>(_(DWORD_)login_url_addr));
>    }
> 2. 进入微信可以考虑一下，实现了这两个hook点意味着可以构建自动化程序来启动和登录微信了，发生微信退出或机器重启时可以自动化登录，很酷
> 3. 另外安利一下我们的wehcaty-puppet-xp项目，使用frida实现的win版微信机器人，我正在尝试将wxhelper项目里功能移植到xp https://github.com/wechaty/puppet-xp

是这个，frida的确是神器，很赞

**Comment by atorber** [comment]
期待【进入微信】】功能的call ，获取二维码的call已经集成好了

最近两天也把wxhelper中的call尽可能移植到xp，再经过一些测试发布npm，使用frida的好处是没有单独的注入操作，小白用户也可以轻松使用

puppet-xp 是基于wechaty的开源项目 https://github.com/wechaty/sidecar-demos ，它在frida基础上进行了封装

**Comment by atorber** [comment]
在3.9.2.23分支里
