### ISSUE TITLE
今天突然很多功能不报错不能使用了，数据库查询任何表都是返回空

### ISSUE THREAD

**Issue by littlezyx** [ttttupup/wxhelper#325]
我使用的版本是wxhelper3.9.2.23.dll
之前都好好的，今天突然就用不了了，hook消息可以，发送消息失败，
接口55查询微信好友名称信息接口http://127.0.0.1:19088/api/?type=55报错 "msg":"[json.exception.type_error.305] cannot use operator[] with a string argument with discarded","result":"ERROR"  
有遇到同样情况的吗？

**Comment by Endousan** [comment]
你好，关于hook消息的内容，我有个问题想请问下，我是新学习这个代码的，之前查阅其他的Issue，看到作者说 要先运行tcpserver的代码，再调用hook的接口，我尝试用运行了tcpserver，并成功监听了本地端口
![QQ截图20231116214946](https://github.com/ttttupup/wxhelper/assets/33174140/9b4e357e-aecb-400e-98ce-767eb91e8c98)
之后再运行client.py 尝试调用hook_msg，但得到的结果是
{"msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}

最初：使用url = "127.0.0.1:19088/api/?type=9"，会显示No connection adapters were found for '127.0.0.1:19088/api/?type=9'
我之后改动一下代码，变成 url = "http://127.0.0.1:19088/api/?type=9"，其他的接口，尝试了检查登录，登录用户，和发送消息，都能成功使用，但无法hook到消息，代码如下：
def hook_msg():
    """
    hook 消息
    :return:
    """
    url = "http://127.0.0.1:19088/api/?type=9"
    payload = json.dumps({
        "port": "19099",
        "ip": "127.0.0.1"
    })
    headers = {
        'Content-Type': 'application/json'
    }
    while 1:
        response = requests.request("POST", url, headers=headers, data=payload)
        if response.text != "":
            break
    print(response.text)

if __name__ == '__main__':
    hook_msg()

你能帮帮我一下，分享一下你使用的方式吗

**Comment by ttttupup** [comment]
> 你好，关于hook消息的内容，我有个问题想请问下，我是新学习这个代码的，之前查阅其他的Issue，看到作者说 要先运行tcpserver的代码，再调用hook的接口，我尝试用运行了tcpserver，并成功监听了本地端口 ![QQ截图20231116214946](https://user-images.githubusercontent.com/33174140/283470950-9b4e357e-aecb-400e-98ce-767eb91e8c98.jpg) 之后再运行client.py 尝试调用hook_msg，但得到的结果是 {"msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}
> 
> 最初：使用url = "127.0.0.1:19088/api/?type=9"，会显示No connection adapters were found for '127.0.0.1:19088/api/?type=9' 我之后改动一下代码，变成 url = "[http://127.0.0.1:19088/api/?type=9"，其他的接口，尝试了检查登录，登录用户，和发送消息，都能成功使用，但无法hook到消息，代码如下：](http://127.0.0.1:19088/api/?type=9%22%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E6%8E%A5%E5%8F%A3%EF%BC%8C%E5%B0%9D%E8%AF%95%E4%BA%86%E6%A3%80%E6%9F%A5%E7%99%BB%E5%BD%95%EF%BC%8C%E7%99%BB%E5%BD%95%E7%94%A8%E6%88%B7%EF%BC%8C%E5%92%8C%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%EF%BC%8C%E9%83%BD%E8%83%BD%E6%88%90%E5%8A%9F%E4%BD%BF%E7%94%A8%EF%BC%8C%E4%BD%86%E6%97%A0%E6%B3%95hook%E5%88%B0%E6%B6%88%E6%81%AF%EF%BC%8C%E4%BB%A3%E7%A0%81%E5%A6%82%E4%B8%8B%EF%BC%9A) def hook_msg(): """ hook 消息 :return: """ url = "http://127.0.0.1:19088/api/?type=9" payload = json.dumps({ "port": "19099", "ip": "127.0.0.1" }) headers = { 'Content-Type': 'application/json' } while 1: response = requests.request("POST", url, headers=headers, data=payload) if response.text != "": break print(response.text)
> 
> if **name** == '**main**': hook_msg()
> 
> 你能帮帮我一下，分享一下你使用的方式吗

这个是传参问题，这个接口是5个参数。看文档说明

**Comment by Endousan** [comment]
> > 你好，关于hook消息的内容，我有个问题想请问下，我是新学习这个代码的，之前查阅其他的Issue，看到作者说 要先运行tcpserver的代码，再调用hook的接口，我尝试用运行了tcpserver，并成功监听了本地端口 ![QQ截图20231116214946](https://user-images.githubusercontent.com/33174140/283470950-9b4e357e-aecb-400e-98ce-767eb91e8c98.jpg) 之后再运行client.py 尝试调用hook_msg，但得到的结果是 {"msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}
> > 最初：使用url = "127.0.0.1:19088/api/?type=9"，会显示No connection adapters were found for '127.0.0.1:19088/api/?type=9' 我之后改动一下代码，变成 url = "[http://127.0.0.1:19088/api/?type=9"，其他的接口，尝试了检查登录，登录用户，和发送消息，都能成功使用，但无法hook到消息，代码如下：](http://127.0.0.1:19088/api/?type=9%22%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E6%8E%A5%E5%8F%A3%EF%BC%8C%E5%B0%9D%E8%AF%95%E4%BA%86%E6%A3%80%E6%9F%A5%E7%99%BB%E5%BD%95%EF%BC%8C%E7%99%BB%E5%BD%95%E7%94%A8%E6%88%B7%EF%BC%8C%E5%92%8C%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%EF%BC%8C%E9%83%BD%E8%83%BD%E6%88%90%E5%8A%9F%E4%BD%BF%E7%94%A8%EF%BC%8C%E4%BD%86%E6%97%A0%E6%B3%95hook%E5%88%B0%E6%B6%88%E6%81%AF%EF%BC%8C%E4%BB%A3%E7%A0%81%E5%A6%82%E4%B8%8B%EF%BC%9A) def hook_msg(): """ hook 消息 :return: """ url = "http://127.0.0.1:19088/api/?type=9" payload = json.dumps({ "port": "19099", "ip": "127.0.0.1" }) headers = { 'Content-Type': 'application/json' } while 1: response = requests.request("POST", url, headers=headers, data=payload) if response.text != "": break print(response.text)
> > if **name** == '**main**': hook_msg()
> > 你能帮帮我一下，分享一下你使用的方式吗
> 
> 这个是传参问题，这个接口是5个参数。看文档说明

谢谢，试了下用5个参数， 成功了，3.9.2.23的原文档写的只有两个参数，看最新版 原来是5个
