### ISSUE TITLE
请问多开后，如何监听每个进程的 http 接口呢？

### ISSUE THREAD

**Issue by 157276303** [ttttupup/wxhelper#33]
多开后，如何监听每个进程的 http 接口呢？

**Comment by ttttupup** [comment]
如果多开的话，就不要在DLL_PROCESS_ATTACH 时启动http了，通过外界调用http_start函数就可以了。端口后自己定义，一般通过注入程序根据pid+port启动就行了。

**Comment by 157276303** [comment]
DLL_PROCESS_ATTACH 是需要修改dll 代码吗？

**Comment by ttttupup** [comment]
wxhelper现在时在注入的时候就启动了默认19088端口的http server。如果想多开，把这个启动http server交给其他程序，根据传入的端口启动http server就可以了，不需要监听。当然也可以采用监听的方式。不过这种更简单。

**Comment by ttttupup** [comment]
仅用于学习研究，请勿用于非法用途和商业用途

**Comment by 157276303** [comment]
是的，正在学习研究

**Comment by 157276303** [comment]
需要指导下~

**Comment by ttttupup** [comment]
tasklist | findstr "WeChat.exe"
netstat -ano | findstr "your wechat pid"  使用这两条命令，就可以看到监听的端口变化。

**Comment by 157276303** [comment]
你好，开发者！搞了两天还是不懂，想问一下，你说 “当然也可以采用监听的方式。不过这种更简单。”具体逻辑是怎样的？请原谅一个好学的小白，问题多多！

**Comment by ttttupup** [comment]
分两种情况，1.知道端口，循环访问端口，能通就说明启动了 2.不知道端口，扫描程序的所有端口，第二次比第一次增加的端口不就是启动端口

**Comment by ttttupup** [comment]
`#include "pch.h"
#include "driver.h"

BOOL isFileExists_stat(wstring name)
{
    struct _stat buffer;
    return (_wstat(name.c_str(), &buffer) == 0);
}

DWORD GetWeChatWinBase(DWORD pid)
{
    wchar_t *WeChatWin = (wchar_t *)L"WeChatWin.dll";
    WeChatProcess hp(pid);
    if (!hp.m_init)
        return 0;
    WeChatData<wchar_t *> r_dllname(hp.GetHandle(), WeChatWin, TEXTLENGTH(WeChatWin));
    if (r_dllname.GetAddr() == 0)
        return 0;
#ifdef _WIN64
    DWORD pGetModuleHandleW = (DWORD)GetSystem32ProcAddr(L"\\KnownDlls32\\kernel32.dll", "GetModuleHandleW");
#else
    DWORD pGetModuleHandleW = (DWORD)GetModuleHandleW;
#endif
    DWORD ret = CallRemoteFunction(hp.GetHandle(), pGetModuleHandleW, r_dllname.GetAddr());
    return ret;
}

BOOL CreateConsole()
{
    if (AllocConsole())
    {
        AttachConsole(GetCurrentProcessId());
        FILE *retStream;
        freopen_s(&retStream, "CONOUT$", "w", stdout);
        if (!retStream)
            throw std::runtime_error("Stdout redirection failed.");
        freopen_s(&retStream, "CONOUT$", "w", stderr);
        if (!retStream)
            throw std::runtime_error("Stderr redirection failed.");
        return TRUE;
    }
    return FALSE;
}

wstring GetWorkPath()
{
    wchar_t szFilePath[MAX_PATH + 1] = {0};
#ifdef _WIN64
    HMODULE hd = GetModuleHandle(L"wxDriver64.dll");
#else
    HMODULE hd = GetModuleHandle(L"wxDriver.dll");
#endif
    GetModuleFileName(hd, szFilePath, MAX_PATH);
    wstring wpath = szFilePath;
    int pos = (int)wpath.find_last_of(L"\\");
    wpath = wpath.substr(0, pos);
    return wpath;
}

BOOL start_listen(DWORD pid, int port)
{
    wstring dllpath = GetWorkPath() + L"\\" + DLLNAME;
    if (!isFileExists_stat(dllpath))
    {
        return FALSE;
    }
    BOOL status = InjectDll(pid, dllpath.c_str());
    if (status == false)
        return FALSE;
    WeChatProcess hp(pid);
    if (hp.m_init == false)
    {
        return FALSE;
    }
    DWORD http_start = hp.GetProcAddr((LPSTR) "http_start");
    if (http_start == 0)
        return FALSE;
    CallRemoteFunction(hp.GetHandle(), http_start, port);
    return TRUE;
}

BOOL stop_listen(DWORD pid)
{
    WeChatProcess hp(pid);
    if (hp.m_init == false)
    {
        return FALSE;
    }
    DWORD http_close = hp.GetProcAddr((LPSTR) "http_close");
    if (http_close == 0)
        return FALSE;
    CallRemoteFunction(hp.GetHandle(), http_close, NULL);
    BOOL status = RemoveDll(pid);
    return status;
}

static BOOL GetWeChatInstallInfo(TCHAR *lpValueName, VOID *Value, DWORD lpcbData)
{
    HKEY hKey = NULL;
    ZeroMemory(Value, lpcbData);
    LSTATUS lRet = RegOpenKeyEx(HKEY_CURRENT_USER, _T("SOFTWARE\\Tencent\\WeChat"), 0, KEY_QUERY_VALUE, &hKey);
    if (lRet != 0)
    {
        return false;
    }
    lRet = RegQueryValueEx(hKey, lpValueName, NULL, NULL, (LPBYTE)Value, &lpcbData);
    RegCloseKey(hKey);
    if (lRet != 0)
    {
        return false;
    }
    return true;
}

tstring GetWeChatInstallDir()
{
    TCHAR *szProductType = new TCHAR[MAX_PATH];
    GetWeChatInstallInfo((TCHAR *)TEXT("InstallPath"), (void *)szProductType, MAX_PATH);
    tstring wxdir(szProductType);
    delete[] szProductType;
    szProductType = NULL;
    return wxdir.length() == 0 ? TEXT("") : wxdir;
}

tstring GetWeChatVersion()
{
    BYTE pversion[4] = {0};
    GetWeChatInstallInfo((TCHAR *)TEXT("CrashVersion"), (void *)pversion, sizeof(DWORD));
    TCHAR *temp = new TCHAR[20];
    _stprintf_s(temp, 20, _T("%d.%d.%d.%d\0"), (int)(pversion[3] - 0x60), (int)pversion[2], (int)pversion[1], (int)pversion[0]);
    tstring verStr(temp);
    delete[] temp;
    temp = NULL;
    return verStr;
}

static bool CloseAllWxProcessMutexHandle()
{
    HANDLE hsnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (hsnapshot == INVALID_HANDLE_VALUE)
    {
        return false;
    }
    PROCESSENTRY32 pe;
    pe.dwSize = sizeof(PROCESSENTRY32);
    int flag = Process32First(hsnapshot, &pe);
    while (flag != 0)
    {
        if (lstrcmp(pe.szExeFile, L"WeChat.exe") == 0)
        {
            CloseProcessHandle(pe.th32ProcessID, (wchar_t *)L"_WeChat_App_Instance_Identity_Mutex_Name");
        }
        flag = Process32Next(hsnapshot, &pe);
    }
    CloseHandle(hsnapshot);
    return true;
}

DWORD new_wechat()
{
    CloseAllWxProcessMutexHandle();
    tstring szAppName = GetWeChatInstallDir();
    if (szAppName.length() == 0)
        return 0;
    szAppName += TEXT("\\WeChat.exe");
    STARTUPINFO StartInfo;
    ZeroMemory(&StartInfo, sizeof(StartInfo));
    PROCESS_INFORMATION procStruct;
    ZeroMemory(&procStruct, sizeof(procStruct));
    StartInfo.cb = sizeof(STARTUPINFO);
    if (CreateProcess((LPCTSTR)szAppName.c_str(), NULL, NULL, NULL, FALSE, NORMAL_PRIORITY_CLASS, NULL, NULL, &StartInfo, &procStruct))
    {
        CloseHandle(procStruct.hProcess);
        CloseHandle(procStruct.hThread);
    }
    if (procStruct.dwProcessId == 0)
        return 0;
    DWORD WeChatWinBase = 0;
    while ((WeChatWinBase = GetWeChatWinBase(procStruct.dwProcessId)) == 0)
    {
        Sleep(500);
    }
    return procStruct.dwProcessId;
}`   com那个项目里有源码直接参考就行了

**Comment by ttttupup** [comment]
https://github.com/ljc545w/ComWeChatRobot/blob/master/wxDriver/driver.cpp

**Comment by 157276303** [comment]
2.不知道端口，扫描程序的所有端口，第二次比第一次增加的端口不就是启动端口
---------------
在dll 19088端口代码那搞个随机数变量，是不是简单了！原来解决问题的思维最重要！学到了

**Comment by 157276303** [comment]
或者是每次端口值+1

**Comment by ttttupup** [comment]
哪种方便用哪种就行，不过最好要注意端口冲突
