### ISSUE TITLE
发送@文本，能支持自定义消息格式吗

### ISSUE THREAD

**Issue by yaolin123** [ttttupup/wxhelper#332]
例  @user1 早上好，@user2  中午好

**Comment by laomms** [comment]
微信本身好像不支持markdown格式消息

**Comment by ttttupup** [comment]
看了一下，微信支持，自己在拼@昵称 后面拼接上信息即可，需要自己处理一下

**Comment by lixh00** [comment]
emmm
亲测不行，版本`3.9.2.23`，还是会在消息前面自动拼接上`@用户名`
![image](https://github.com/ttttupup/wxhelper/assets/72033265/f41318df-bd66-43a9-a6fd-3b1359637733)
