### ISSUE TITLE
请问3.9.8.25-v2注入结果：0 ，是什么原因

### ISSUE THREAD

**Issue by leiyong711** [ttttupup/wxhelper#334]
用的https://github.com/ttttupup/wxhelper/releases 编译好的dll，之前用的3.9.2.23今天心血来潮试试新版发现注入不成功，请问有大佬知道是什么原因吗？

![image](https://github.com/ttttupup/wxhelper/assets/28699976/e9df6425-7bca-42ca-b822-8133e431a6c8)
![image](https://github.com/ttttupup/wxhelper/assets/28699976/b66a6408-3d04-4c9c-9c45-c42035ffba6f)

**Comment by flyfe** [comment]
x64用的注入工具不一样

**Comment by leiyong711** [comment]
> x64 使用的注入工具不一样

能麻烦给我一个吗？

**Comment by lngwu11** [comment]
> > x64 使用的注入工具不一样
> 
> 能麻烦给我一个吗？

这里
https://github.com/nefarius/Injector/releases/download/v1.3.0/Injector_x86_amd64_arm64.zip

**Comment by leiyong711** [comment]
> > > x64 使用的注入工具不一样
> > 
> > 
> > 能给我一个麻烦吗？
> 
> 这里 https://github.com/nefarius/Injector/releases/download/v1.3.0/Injector_x86_amd64_arm64.zip

大佬 请问这是什么问题？
![image](https://github.com/ttttupup/wxhelper/assets/28699976/2f69e0f6-12b2-4134-ac13-320df3a3ee1d)

**Comment by magic-flower** [comment]
@leiyong711
Injector.exe --process-name WeChat.exe --inject E:\WeChat\wxbot.dll

**Comment by leiyong711** [comment]
> @leiyong711 Injector.exe --process-name WeChat.exe --inject E:\WeChat\wxbot.dll

好的 谢谢

**Comment by douyadaydayup** [comment]
@leiyong711 解决了吗？我遇到了和你一样的问题。我怀疑是系统原因

**Comment by the-best-richer** [comment]
请问最后您是怎么解决的，我从老版本升级到开发板，换了所有issue里提到的注入器，全部注入失败
![image](https://github.com/ttttupup/wxhelper/assets/136454649/39c67a13-19ef-4db8-8ef4-bfeb5edf32ee)
![image](https://github.com/ttttupup/wxhelper/assets/136454649/eb41c6cf-f41f-418e-b6ae-3364d01d6d6b)
![image](https://github.com/ttttupup/wxhelper/assets/136454649/96a69ded-2f8b-4e03-ae59-2d2e8dd72284)
仓库提供的界面版打不开直接闪退，安装了vs2022，并且下了一堆修复工具修复系统环境
3.9.3几的老版本是可用的，新版本不管是正常版本还是非正常版本全部无法使用

**Comment by timersun** [comment]
你这个解决了吗
