### ISSUE TITLE
接口返回错误

### ISSUE THREAD

**Issue by zpj0605** [ttttupup/wxhelper#34]
通过/api/?type=0接口，返回的数据为{"msg":"not support method","result":"ERROR"}   是哪里没操作对呢？

**Comment by ttttupup** [comment]
全部是post请求

**Comment by zpj0605** [comment]
非常感谢您的回答，我使用的是e语言，get和post请求都有测试，post请求返回的是Invalid url。正确的post请求应该是怎样的？

**Comment by zpj0605** [comment]
> 全部是post请求

非常感谢您的回答，我使用的是e语言，get和post请求都有测试，post请求返回的是Invalid url。正确的post请求应该是怎样的？

**Comment by ttttupup** [comment]
curl --location --request POST '127.0.0.1:19088/api/?type=0'      可以用curl试一下
Invalid url 这个错误是url写错了

**Comment by zpj0605** [comment]
> curl --location --request POST '127.0.0.1:19088/api/?type=0'      可以用curl试一下
> Invalid url 这个错误是url写错了

非常感谢您的解答，解决了。
