### ISSUE TITLE
3.9.8.25-v2 消息转发接口bug

### ISSUE THREAD

**Issue by magic-flower** [ttttupup/wxhelper#340]
版本：3.9.8.25-v2 dll(release)
环境：win11 64位 
微信版本： 3.9.8.25
接口名称：/api/forwardMsg

文本，表情包消息能正常转发
图片消息服务端返回成功{  code: 1, data: null, msg: 'success' }
但是消息微信客户端不能收到转发的图片消息。场景是http回调收到图片消息后立即根据msgId转发图片消息。是需要等待一段时间才能转发图片，或是需要微信客户端手动接收图片后才能转发。

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/issues/296
