### ISSUE TITLE
getChatRoomDetailInfo 接口不存在

### ISSUE THREAD

**Issue by yzqzy** [ttttupup/wxhelper#344]
**Describe the bug**
3.9.8.25 最新hook，api 接口返回 the url is not supported。

**To Reproduce**
1. 下载 3.9.8.25-v2
2. 注入功能注入

**Expected behavior**
接口正常使用

**Desktop (please complete the following information):**
 - OS: window 10
 - Version 3.9.8.25

![image](https://github.com/ttttupup/wxhelper/assets/96212026/a4e125db-9f31-4484-9249-b4359c185560)

**Comment by che246** [comment]
3.9.8.25 没有这个api

**Comment by yzqzy** [comment]
> 3.9.8.25 没有这个api

好的，我还以为文档中的 api 都有。
