### ISSUE TITLE
添加一个【确认登录】能力

### ISSUE THREAD

**Issue by yibo-liang** [ttttupup/wxhelper#347]
作者你好，请问能不能添加一个自动登录的能力，在扫码以后登录，下次重启以后，是可以点击按钮直接登录的。目前我们只能用win api来按按钮，有没有添加一个这样的借口呢？ 谢谢。

**Comment by ttttupup** [comment]
确认登录是扫码，进入微信已经有了

**Comment by yibo-liang** [comment]
> 确认登录是扫码，进入微信已经有了
谢谢回答！

请问进入微信是用什么api接口呢？ 你的Example里找不到。第一次确认用扫码以后，重启微信就只剩下一个按钮“进入微信”，这个时候用什么api接口自动化这个按钮的点击呢？我是python，python的3.9.5.81示例里没有这个。

**Comment by ttttupup** [comment]
3.9.8.25版本的
