### ISSUE TITLE
发送文本消息时，中文需要如何转码？

### ISSUE THREAD

**Issue by zpj0605** [ttttupup/wxhelper#35]
如果发送中文文本消息，会返回错误，中文需要如何转码？

**Comment by zpj0605** [comment]
已解决，需要asin转utf8

**Comment by zpj0605** [comment]
e语言需要使用网页_访问_对象 方法去请求

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/221373988-ced98cef-3871-4356-ae4a-8e91d622cf05.png)
为什么就是不行

**Comment by ttttupup** [comment]
错误信息很明显了，json错了，少了}

**Comment by lovezm** [comment]
没有 只是没截到 我直接把字放到提交数据里面可以发，用参数过来就不行了

**Comment by ttttupup** [comment]
> 没有 只是没截到 我直接把字放到提交数据里面可以发，用参数过来就不行了

那就是你的编码问题
