### ISSUE TITLE
/api/hookLog 开启后,再关闭,server接收不到hook的消息. logs文件一直在增长

### ISSUE THREAD

**Issue by cynen** [ttttupup/wxhelper#360]
微信版本: 3.9.5.81
一切部署好之后.
开启 hook 消息 [/api/hookSyncMsg](https://github.com/ttttupup/wxhelper/blob/dev-3.9.5.81/api/hookSyncMsg)
然后server端正常接收到hook的消息.

--- bug发现之旅

1.之后调用了  /api/hookLog接口. 然后就发现server端没有收到hook消息.
2.再次调佣 /api/unhookLog, 不生效.Server端还是搜不到hook消息. 但是wechat安装目录下的 /logs/daily_** 一直在增长.

**Comment by zddtpy** [comment]
3.9.2.23 v9版本的hook日志，请求出错，开启不了。

**Comment by atorber** [comment]
遇到了请求hookSyncMsg success: {"code":2,"data":null,"msg":"success"}，返回的code是2，但是文档里并没有这个code，并且没有推送数据
