### ISSUE TITLE
T佬您好，我想问下如何使用浏览器打开某个指定网址

### ISSUE THREAD

**Issue by the-best-richer** [ttttupup/wxhelper#362]
**Is your feature request related to a problem? Please describe.**
T佬您好，我想问下如何使用浏览器打开某个指定网址，我在文档里以及源码里搜索没找到相关内容
Issue有其他人提的issue，以及看到了支持该功能，但是我找不到具体的相关使用文档

**Describe the solution you'd like**
希望更新下文档，感觉文档很久没更新啦

**Describe alternatives you've considered**
所有支持的api，参数，以及返回
或者一个表格列出type对应的动作

**Additional context**

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/blob/dev-3.9.8.25/doc/3.9.8.25.md     19

**Comment by the-best-richer** [comment]
谢谢t佬，感谢

**Comment by zx493734247** [comment]
3.9.8.25版本之后貌似就都不行了
