### ISSUE TITLE
数据库实例和对应数据库文件偏移获取的思路是怎样的？

### ISSUE THREAD

**Issue by lzb112** [ttttupup/wxhelper#377]
const UINT64 kGPInstance = 0x3d8b4f8;
const UINT64 kMicroMsgDB = 0xb8;
const UINT64 kChatMsgDB = 0x2c8;
const UINT64 kMiscDB = 0x5f0;
const UINT64 kEmotionDB = 0x888;
const UINT64 kMediaDB = 0xF48;
const UINT64 kBizchatMsgDB = 0x1AC0;
const UINT64 kFunctionMsgDB = 0x1b98;
const UINT64 kDBName = 0x28;
const UINT64 kStorageStart = 0x0;
const UINT64 kStorageEnd = 0x0;
const UINT64 kMultiDBMgr = 0x3e00910;
const UINT64 kPublicMsgMgr = 0x3dfe098;
const UINT64 kFavoriteStorageMgr = 0x3e01478;

这些获取的思路是什么，没想通这些都是怎么得出来的
![image](https://github.com/ttttupup/wxhelper/assets/50606627/1ec5727e-f659-48ab-8100-c8498532e717)

**Comment by ttttupup** [comment]
逆向分析和调试出来的

**Comment by lzb112** [comment]
妈呀，调了我半天。多个的和单个的还不一样。
