### ISSUE TITLE
最新Release 3.9.8.25-v2无法注入

### ISSUE THREAD

**Issue by jamesliu668** [ttttupup/wxhelper#386]
**Describe the bug**
使用main分支的*ConsoleApplication.exe*注入失败，双击*微信DLL注入器V1.0.3.exe*没有反应。

**系统版本:**
 - OS: Windows10 （64位）

**启动命令:**
`ConsoleApplication.exe -i WeChat.exe -p wxhelper39825.dll`

**显示结果:**
dll inject successdll path : w dll path : 14320  注入结果：1
使用`netstat -aon | findstr 19088`么有端口列表显示

如果使用命令`ConsoleApplication.exe -i WeChat.exe -p wxhelper39825.dll  -P 31000`，结果为` 注入结果：1`，微信直接退出。

**Comment by lzb112** [comment]
微信用管理员启动，cmd也用管理员启动，应该就行了。我也很神奇这个现象，有些系统又不用。

**Comment by jamesliu668** [comment]
还是崩了，如图

![image](https://github.com/ttttupup/wxhelper/assets/4152618/7ed08580-7487-4bdb-9202-6bbd02a8f5a7)

**Comment by jamesliu668** [comment]
搞定了，操作步骤如下：

1. 重新安装64位微信3.9.8.25版本（确认是64位）
2. ConsoleApplication.exe -h（看看有没有帮助信息）
3. wxhelper39825.dll要完整路径

![image](https://github.com/ttttupup/wxhelper/assets/4152618/bfe43537-5d0e-404e-8bb4-d59710c73ca4)
尝试卸载停服务，好像没成功，不过不重要。

**Comment by timersun** [comment]
我使用ConsoleApplication.exe注入的时候，总是打开就显示缺少各种各样的dll，使用https://github.com/nefarius/Injector/releases注册的时候，注入失败，你们是怎么解决的呀？
