### ISSUE TITLE
注入后打不开http服务器

### ISSUE THREAD

**Issue by zoutao98** [ttttupup/wxhelper#39]
[http://127.0.0.1:19088/api/?type=0](http://127.0.0.1:19088/api/?type=0%E3%80%82)
使用api post工具调试，这个个后端没开起来
版本 3.9.0.28 v9
是我的使用方法有问题吗？
1. 我把wxhelper.dll移到ConsoleInject.exe 同目录
2. 执行ConsoleInject.exe  -i D:\Program Files (x86)\Tencent\WeChat\WeChat.exe -p wxhelper.dll
3. 重新登录微信，测试http，没反应

**Comment by ttttupup** [comment]
命令错了  ConsoleInject.exe -i WeChat.exe  -p  d:\wxhelper.dll

**Comment by zoutao98** [comment]
这个路径是绝对路径吗

**Comment by zoutao98** [comment]
还是没成功

**Comment by zoutao98** [comment]
哦哦，懂意思了

**Comment by zoutao98** [comment]
但是拒绝访问是为什么
![图片](https://user-images.githubusercontent.com/46660687/222322866-34957f65-4e38-4502-b123-c5eca659a8ed.png)

**Comment by ttttupup** [comment]
//-i  注入程序名   -p 注入dll路径   
    // -u 卸载程序名   -d 卸载dll名称
    //注入  
    ConsoleInject.exe  -i demo.exe -p E:\testInject.dll
    //卸载 
    ConsoleInject.exe  -u demo.exe -d  testInject.dll

**Comment by zoutao98** [comment]
![图片](https://user-images.githubusercontent.com/46660687/222326436-51627b58-044c-4e11-833e-b6a7c872e1d3.png)

**Comment by zoutao98** [comment]
我的
可以启动了，刚刚不知道啥原因那个ConsoleInject.exe变成0Kb了，我重新下载了个就可以了
