### ISSUE TITLE
登录后获取当前登录用户信息(type=1)，微信异常退出

### ISSUE THREAD

**Issue by luochaolun** [ttttupup/wxhelper#4]
打开pc微信，未登录时，可以正常获取当前登录用户信息。

但是登录后，再获取当前登录用户信息出错，微信崩溃退出！

建议有时间了修复下！

win10 64位、两个微信版本都试了，都有同样的问题！

**Comment by ttttupup** [comment]
正常情况下，未登录是获取不到登录用户信息的，用的是win11 没有复现。这个功能是不能在未登录情况下调用。

**Comment by ttttupup** [comment]
试了一下3.8.1.26 分支的release 的dll，是会出现崩溃，可能传错了，已经重新提交了dll，可以再试下，不登录获取的信息没有用户的配置信息的。

**Comment by luochaolun** [comment]
刚更新的3.8.1.26 分支的elease 的dll，直接注入不了

**Comment by ttttupup** [comment]
用的是自己的注入工具还是tool里的，已经测试过正常的

**Comment by luochaolun** [comment]
用的MFCApplication.exe的注入，提示缺少injector.dll，百度后下了个injector.dll，注入之前的wxhelper.dll，可以打开http://127.0.0.1:19088/api/?type=0。

注入你更新后的injector.dll，提示wxhelper.dll 没有被指定在windows上运行，或者包含错误。错误状态 0xc000012f

建议你换台电脑试下，就会发现。

**Comment by ttttupup** [comment]
这个错误原因很多，最好换个能在你电脑上正常注入dll的注入器注入这个wxhelper.dll.   这个injector.dll 就是一个简单的注入器，你可以自己编译一个。我用的是win11不好复现。

**Comment by ttttupup** [comment]
win10系统以前测试过，升级之后就没有测试了

**Comment by luochaolun** [comment]
我编译了一个注入器，没更新之前的注入可以打开http://127.0.0.1:19088/api/?type=0，下载你刚更新的，连http://127.0.0.1:19088/api/?type=0这个都打不开了。

**Comment by ttttupup** [comment]
自己编译一下最好，然后检查一下端口是否被占用，其他接口是否能正常使用。或者编译一个debug版本，debug版本会有控制台窗口

**Comment by luochaolun** [comment]
用最新的3.8.1.26编译人可以，但是还是未登录时，可以正常获取当前登录用户信息。

但是登录后，再获取当前登录用户信息出错，微信崩溃退出！

还有就是设置自动保存图片，接收到图片时并没没有保存到指定的目录！

**Comment by luochaolun** [comment]
用最新的3.8.1.26编译的可以，但是还是未登录时，可以正常获取当前登录用户信息。

但是登录后，再获取当前登录用户信息出错，微信崩溃退出！

还有就是设置自动保存图片，接收到图片时并没没有保存到指定的目录！

**Comment by ttttupup** [comment]
保存图片现在是需要主动点击打开原图才会触发下载，否则的话，微信不会主动下载，而是以任务的形式下载，具体时间就不确定了。hook的方法不好用，所以增加了直接从dat获取图片的接口。登录后崩溃也可能是账号问题，某个值的偏移有问题，需要看下崩溃日志。

**Comment by lovezm** [comment]
我也是type=1就崩溃，而且监听消息返回的code是2  无法tcp链接

**Comment by ttttupup** [comment]
type=1这个接口都是静态偏移，可以先登录微信，看下具体的偏移的结果是什么。或者有微信的崩溃日志的发下日志。

**Comment by ttttupup** [comment]
#define WX_LOGIN_STATUS_OFFSET 0x2c42a10
#define WX_APP_DATA_ROOT_PATH_OFFSET 0x2c84ae0
#define WX_APP_DATA_SAVE_PATH_OFFSET 0x2c65728
#define WX_CURRENT_DATA_PATH_OFFSET 0x2c636fc

**Comment by ttttupup** [comment]
登录后会崩溃重点看下这几个偏移

**Comment by ttttupup** [comment]
> 我也是type=1就崩溃，而且监听消息返回的code是2 无法tcp链接

code==2 是已经hook了，重复hook了

**Comment by luochaolun** [comment]
视频号是不是比较难搞啊，翻遍github,也没见一个hook视频号的。

**Comment by ttttupup** [comment]
这个目前没有研究过。

**Comment by lovezm** [comment]
还是崩溃   错误模块是VCRUNTIME140.dll

**Comment by ixsword** [comment]
偏移有问题，
body: mobile:1812****391
name:娓呯伒涔嬭垶
city:Shenzhen
city:Shenzhen
province:Guangdong
country:CN
account:cjqrun
wxid:悷?
small_img:?5
big_img:?5

**Comment by lovezm** [comment]
另外问一下在hook消息里面怎么没有 群名称和发送者的昵称  是要自己查数据库吗

**Comment by ixsword** [comment]
> 另外问一下在hook消息里面怎么没有 群名称和发送者的昵称 是要自己查数据库吗

我老版本的里面是要判断是否是群消息、艾特消息，拿到发送者wxid去保存的联系人列表里面查的，Hook的消息是没有昵称，只有群wxid好像

**Comment by ixsword** [comment]
> 另外问一下在hook消息里面怎么没有 群名称和发送者的昵称 是要自己查数据库吗

f (isChatRoomMessage)receiver = L"chatroom";
		
		UserInfo user;
		if (isChatRoomMessage)
		{
			GetUserInfoByWxid(msg->sender, user);
		}
		else {
			GetUserInfoByWxid(msg->wxid, user);
		}

**Comment by ixsword** [comment]
建议改成websocket，我看到建了个http server完了还要请求hook下消息就头疼，做的不干净拖泥带水的，直接websocket双向通信，我之前的所有项目都是websocket通信，稳如老狗，根本不需要中途再hook下，注入成功就可以开始hook了

**Comment by ixsword** [comment]
![image](https://user-images.githubusercontent.com/8772044/217373472-27ad08ed-43b2-4656-a7fd-1dca3524d1a0.png)
![image](https://user-images.githubusercontent.com/8772044/217373692-6bf247dd-2c1e-4d75-8031-c034493efcfd.png)

咦，没人说话了？
