### ISSUE TITLE
dll 无法注入呢

### ISSUE THREAD

**Issue by huddhudd** [ttttupup/wxhelper#41]
dll 无法注入呢

**Comment by ttttupup** [comment]
//-i 注入程序名 -p 注入dll路径
// -u 卸载程序名 -d 卸载dll名称
//注入
ConsoleInject.exe -i demo.exe -p E:\testInject.dll
//卸载
ConsoleInject.exe -u demo.exe -d testInject.dll         或者使用图形界面的

**Comment by huddhudd** [comment]
![image](https://user-images.githubusercontent.com/8034908/222360343-eddff04c-8bb2-45a5-8fbb-ab4bd7e071cb.png)

**Comment by huddhudd** [comment]
是这样的呀

**Comment by huddhudd** [comment]
---------------------------
MFCApplication.exe - 系统错误
---------------------------
由于找不到 mfc140ud.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
确定   
---------------------------

**Comment by huddhudd** [comment]
---------------------------
MFCApplication.exe - 系统错误
---------------------------
由于找不到 mfc140ud.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
---------------------------
确定   
---------------------------

**Comment by ttttupup** [comment]
少了-p

**Comment by ttttupup** [comment]
使用3.9.0.28 分支下面的，图形界面的目录下要有injector.dll

**Comment by ttttupup** [comment]
ConsoleInject.exe  不需要mfc的那些依赖

**Comment by huddhudd** [comment]
我太傻逼了。  -p 加上就可以了
