### ISSUE TITLE
v3.9.10.19 分支编译成功，注入成功，发送消息成功，hookSyncMsg指令也成功了。但是无法收到消息，tcpserver和http_server两种方式都无法获取到文本消息。

### ISSUE THREAD

**Issue by serinder** [ttttupup/wxhelper#415]
v3.9.10.29 分支编译成功，注入成功，发送消息成功，hookSyncMsg指令也成功了。但是无法收到消息，tcpserver和http_server两种方式都无法获取到文本消息。楼主，v3.9.10.19是不是hookSyncMsg这块还没开发？

**Comment by ttttupup** [comment]
查看日志中tcp的相关配置是否一致

**Comment by serinder** [comment]
> 查看日志中tcp的相关配置是否一致

感谢楼主白忙中的回复，找到问题了，是偏移地址用的还是v3.9.9.43版本的。
const uint64_t kSyncMsg = 0xc39680;
const uint64_t kSyncMsgNext = 0xc39680;
const uint64_t kDoAddMsg = 0x1225a60;

**Comment by serinder** [comment]
> 查看日志中tcp的相关配置是否一致

感谢楼主白忙中的回复，找到问题了，是偏移地址用的还是v3.9.9.43版本的。
const uint64_t kSyncMsg = 0xc39680;
const uint64_t kSyncMsgNext = 0xc39680;
const uint64_t kDoAddMsg = 0x1225a60;

v3.9.9.43版本分支编译成功，注入成功，发送消息成功，hookSyncMsg指令也成功，也正常收到消息。

**Comment by serinder** [comment]
> 查看日志中tcp的相关配置是否一致

感谢楼主百忙中的回复，找到问题了，是偏移地址用的还是v3.9.9.43版本的。
const uint64_t kSyncMsg = 0xc39680;
const uint64_t kSyncMsgNext = 0xc39680;
const uint64_t kDoAddMsg = 0x1225a60;

v3.9.9.43版本分支编译成功，注入成功，发送消息成功，hookSyncMsg指令也成功，也正常收到消息。

**Comment by vincentlin7** [comment]
我也是无法接收消息我看3.9.9.43和3.9.8.25的kSyncMsg和kSyncMsgNext也是一样，你有3.9.10.19的偏移吗

**Comment by aihongfei** [comment]
![image](https://github.com/ttttupup/wxhelper/assets/82986195/b0c3e2a1-a68b-45f9-97a2-0463b35d2b2d)
这个报错怎么解决啊

**Comment by aoin2006** [comment]
我用v3.9.10.19 的版本也無法收到消息 ， 請問楼主后面怎么搞好的

**Comment by huzhenjie888** [comment]
> kSyncMsg和kSyncMsgNext

我看3.9版本的kSyncMsg和kSyncMsgNext这两个变量，都是这个值 没有变过 。
