### ISSUE TITLE
编译错误Detours引用

### ISSUE THREAD

**Issue by aoin2006** [ttttupup/wxhelper#422]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		CMake Error at app/3rdparty/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    D:/soft/wxhelper/wxhelper/app/3rdparty/Detours

  does not contain a CMakeLists.txt file.		D:\soft\wxhelper\wxhelper\app/3rdparty/CMakeLists.txt	14
  
  
  
  
![image](https://github.com/ttttupup/wxhelper/assets/50866417/4a484d71-4541-4a8e-b5a8-d392061394ef)

**Comment by ttttupup** [comment]
https://github.com/ttttupup/wxhelper/blob/dev-3.9.10.19/doc/3.9.9.43.md

**Comment by aoin2006** [comment]
感谢

手动复制 wxhelper/cmake目录下的 detours.cmake 文件到 wxhelper/app/3rdparty/Detours/
重命名为 CMakeLists.txt 即可
