### ISSUE TITLE
使用ConoleApplication.exe 注入3.9.10.19，注入结果为0 需要用哪个工具才能注入3.9.10.19

### ISSUE THREAD

**Issue by huzhenjie888** [ttttupup/wxhelper#424]
![image](https://github.com/ttttupup/wxhelper/assets/133071383/4aa456b3-0510-410e-aed4-fec133a38488)
使用ConoleApplication.exe 注入3.9.10.19，注入结果为0 需要用哪个工具才能注入3.9.10.19

注入成功了 hook消息也成功了，但是接收不到消息，其他功能都正常。有谁遇到过吗

**Comment by rhythm35** [comment]
想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢

**Comment by huzhenjie888** [comment]
> 想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢
如果19088端口没启动成功，基本上就是你的微信版本被升级了。把微信卸载干净 重新安装3.9.10.19版本64位版的。安装成功后 微信用管理员模式打开，注入也用管理员的方式注入。这时候基本上就会出现19088的端口了

**Comment by shark2shark** [comment]
> 想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢



> 想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢

![image](https://github.com/ttttupup/wxhelper/assets/19640682/2b0020c0-6ed5-436a-b230-23c7103b09a9)
![image](https://github.com/ttttupup/wxhelper/assets/19640682/6b78a50a-2fb4-44a4-9d96-cc96bde92c24)
![image](https://github.com/ttttupup/wxhelper/assets/19640682/4c7d8037-7c60-421e-b99d-ed2b684b0e6d)

同样的问题，层主解决了吗，我的微信版本确定是没有被升级的

**Comment by succInf** [comment]
> > 想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢
> 
> > 想问下，是怎么注入成功的呢，我这边只显示注入结果1，但是hook接口并没有19088的服务，感谢
> 
> ![image](https://private-user-images.githubusercontent.com/19640682/343202053-2b0020c0-6ed5-436a-b230-23c7103b09a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTU5NzMsIm5iZiI6MTcxOTQ1NTY3MywicGF0aCI6Ii8xOTY0MDY4Mi8zNDMyMDIwNTMtMmIwMDIwYzAtNmVkNS00MzZhLWIyMzAtMjNjNzEwM2IwOWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAyMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMTRhNjFiNTljOTI1ZDMzMTdhYTA3MzU0MDQxNmY0ZjVkOTc2NWQxZTRkMjc3ODQ2ODk2Nzk1MWNlMjgyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnQnt4YURo5hPREEXMB-psrNlmeZmb10A33_sGAWJ5k) ![image](https://private-user-images.githubusercontent.com/19640682/343202263-6b78a50a-2fb4-44a4-9d96-cc96bde92c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTU5NzMsIm5iZiI6MTcxOTQ1NTY3MywicGF0aCI6Ii8xOTY0MDY4Mi8zNDMyMDIyNjMtNmI3OGE1MGEtMmZiNC00NGE0LTlkOTYtY2M5NmJkZTkyYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAyMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZGMyMTZmYzk5ZTQ5MDRlYjFiNmU4ZTBkZjczNDlmOWVlYTU3OTIzYTNhMDAyZGU4YzE5ZmYwOTc1MGRmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o2C6zDPiraw3fQXQb1e9B1jKbsopD0dhsx1lQPUs6fs) ![image](https://private-user-images.githubusercontent.com/19640682/343202617-4c7d8037-7c60-421e-b99d-ed2b684b0e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTU5NzMsIm5iZiI6MTcxOTQ1NTY3MywicGF0aCI6Ii8xOTY0MDY4Mi8zNDMyMDI2MTctNGM3ZDgwMzctN2M2MC00MjFlLWI5OWQtZWQyYjY4NGIwZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAyMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGNlODdkNWNhMDM0ZWU2NGM5NjMxNzM5OTViYmNhMDQ2MDdkZDJmZDcxODc0YjVlODFiNGZjMDEzMWNkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKz-q4FbxPMaKf7QgPysbbTKGzzWjLGt4eT8-absAyk)
> 
> 同样的问题，层主解决了吗，我的微信版本确定是没有被升级的

路径里面不要用中文。然后采用管理命令行模式去注入。
