### ISSUE TITLE
本人经过近7天的研究总算把vsstudio2022如何编译wxhelper给搞清楚了。

### ISSUE THREAD

**Issue by huzhenjie888** [ttttupup/wxhelper#428]
### **具体思路请查看以下链接。[点我查看具体编译指南](https://mp.weixin.qq.com/s/EksEeOZkDUwZEU6javrrfw)**

(![image](https://github.com/ttttupup/wxhelper/assets/133071383/e2a371c7-9bc7-48f9-ad05-d76de58d5850))

**Comment by guodf** [comment]
环境搭建真是感人，这个项目的工程没有做好

其实没有你写的那么麻烦，安装好vcpk，cmake后就行了，cmake编译出来vs2022的工程文件，使用vs2022直接编译就行了

**Comment by huzhenjie888** [comment]
> 环境搭建真是感人，这个项目的工程没有做好
> 
> 其实没有你写的那么麻烦，安装好vcpk，cmake后就行了，cmake编译出来vs2022的工程文件，使用vs2022直接编译就行了
可能吧 ，但是不太会，之前编译一直失败。没有头脑。这个教程就是给新手小白的。 看到一堆错误 头大，没有思路。刚好经过多次踩坑 才算成功 。

**Comment by atorber** [comment]
<img width="1429" alt="image" src="https://github.com/ttttupup/wxhelper/assets/19552906/f83a8a60-5cac-424f-bd0b-bd4740b6de8e">

<img width="1425" alt="image" src="https://github.com/ttttupup/wxhelper/assets/19552906/38605df0-d1dc-45c0-aa60-f47221db8800">

还是报错啦

**Comment by atorber** [comment]
> 环境搭建真是感人，这个项目的工程没有做好
> 
> 其实没有你写的那么麻烦，安装好vcpk，cmake后就行了，cmake编译出来vs2022的工程文件，使用vs2022直接编译就行了

可以提供具体的操作方法吗，编译还是报错啦，哭晕

**Comment by atorber** [comment]
基于作者编译方法整理了简便编译方法，实测ok

https://www.yuque.com/atorber/chatflow/dax7igc31bpi949h

参考[点我查看具体编译指南](https://mp.weixin.qq.com/s/EksEeOZkDUwZEU6javrrfw)[点我查看具体编译指南](https://mp.weixin.qq.com/s/EksEeOZkDUwZEU6javrrfw)在 @huzhenjie888 指导下跑通流程后按作者提供的方法编译成功，再次感谢 @huzhenjie888

**Comment by guodf** [comment]
[https://github.com/guodf/wxhelper/tree/guodf-dev-3.9.10.19](https://github.com/guodf/wxhelper/tree/guodf-dev-3.9.10.19)
我修改了，我这里编译不过的问题

**Comment by xpwsgg** [comment]
> https://github.com/guodf/wxhelper/tree/guodf-dev-3.9.10.19 我修改了，我这里编译不过的问题 ，前提是要有cmake，和vcpkg，vs2022环境，配置VCPKG_ROOT环境变量指向vcpk的目录 1 . cmkae -B build 2 . cmake --build ./build ,也可以使用vs2022打开编译

按照一楼捣鼓了半天还是报错，按照你这个两个命令就出来了。。。

**Comment by laomms** [comment]
已经弄好了懒人包，可以直接用vs2022打开编译

https://github.com/laomms/wxhelper

**Comment by youshao** [comment]
感谢分享，按照这个方法，终于编译成功了。太感谢了

**Comment by geekyzk** [comment]
@laomms 请问这个懒人包是基于啥版本，多谢

**Comment by laomms** [comment]
3.9.10， 不过你可以修改成任何版本，架构已经弄好了。

**Comment by liudih** [comment]
> 基于作者编译方法整理了简便编译方法，实测ok
> 
> https://www.yuque.com/atorber/chatflow/dax7igc31bpi949h
> 
> 参考[点我查看具体编译指南](https://mp.weixin.qq.com/s/EksEeOZkDUwZEU6javrrfw)[点我查看具体编译指南](https://mp.weixin.qq.com/s/EksEeOZkDUwZEU6javrrfw)在 @huzhenjie888 指导下跑通流程后按作者提供的方法编译成功，再次感谢 @huzhenjie888

你的教程是用的哪个分支啊？

**Comment by fakers777** [comment]
mark
