### ISSUE TITLE
消息来时 数据库里面BytesExtra 没有下载。 有什么办法能让他下载吗？ 点开看一次就下载了

### ISSUE THREAD

**Issue by huddhudd** [ttttupup/wxhelper#43]
数据库里面BytesExtra 没有下载。 有什么办法能让他下载吗？ 点开看一次就下载了

**Comment by huddhudd** [comment]
Thumb  是有的。 但是 image 没有

**Comment by Ulysses0817** [comment]
我也是任何时段图片都不会自动下载，需要点开看一下

**Comment by huddhudd** [comment]
预览图好像是有的

**Comment by Ulysses0817** [comment]
> 预览图好像是有的

对，这个是会自动下载

**Comment by ttttupup** [comment]
图片现在不会自动下载，后台有个空闲下载的任务，不点不会主动下载

**Comment by ttttupup** [comment]
下载消息附件这个可以的

**Comment by Ulysses0817** [comment]
备注：
消息下载功能很好用，但我刚开始没找到下载的文件在哪，刚才看了源码才发现是在~/W*Ch*t Files/selfwxid/wxhelper/filetype/目录下
