### ISSUE TITLE
3.9.10.19发送@消息和删除群成员都返回-2

### ISSUE THREAD

**Issue by succInf** [ttttupup/wxhelper#436]
/api/sendAtText

{
    "wxids":"wxid_0r1cc76t51di22",
    "chatRoomId": "43589214307@chatroom",
    "msg":"你好"
  
}

{
    "code": -2,
    "data": null,
    "msg": "success"
}

无法@具体的人员

**Comment by huzhenjie888** [comment]
for (unsigned int i = 0; i < wxids.size(); i++) {
    std::wstring nickname;
    std::wstring at_all = L"notify@all";
    if (at_all.compare(wxids[i]) == 0) {
      nickname = L"\u6240\u6709\u4eba";
    } else {
      // nickname = GetContactOrChatRoomNickname(wxids[i]);
    }
    if (nickname.length() == 0) {
      continue;
    }
    prototype::WeChatString id(wxids[i]);
    wxid_list.push_back(id);
    at_msg = at_msg + L"@" + nickname + L" ";
    number++;
  }
  if (number < 1) {
    success = -2;
    return success;
  }

作者把这个昵称获取注释了。我试了下 打开注释 微信会直接崩溃。应该是这个版本的获取昵称的偏移作者还没计算出来。期待作者大大的更新

**Comment by RedRiverCN** [comment]
kNewContact	25E4430
kFreeContact	25E4AE0
kGetContact	22609B0

**Comment by succInf** [comment]
> kNewContact 25E4430 kFreeContact 25E4AE0 kGetContact 22609B0

非常感谢 可以使用

**Comment by yuanzhiwei** [comment]
我也遇到这个问题， 请问该怎么解决
