### ISSUE TITLE
3.9.0.28获取登录信息报错

### ISSUE THREAD

**Issue by jeffrey0326** [ttttupup/wxhelper#44]
3.9.0.28获取登录信息报错：
{
	"msg": "[json.exception.type_error.316] invalid UTF-8 byte at index 4: 0xD2",
	"result": "ERROR"
}

**Comment by ttttupup** [comment]
用的是哪个版本的dll，错误日志最好发一下。或者自己定位一下，就是某个值编码的问题。

**Comment by tlxfif** [comment]
我也出现这个问题了，其实是微信安装路径是中文就会出现 : )
