### ISSUE TITLE
多开wx 注入

### ISSUE THREAD

**Issue by xqsoft** [ttttupup/wxhelper#46]
多开的wx注入后 仅首次注入的有效  应该是端口占用了

不知道大佬 有没有办法解决多开问题

**Comment by xqsoft** [comment]
要是能指定pid 获取信息也可以

**Comment by ttttupup** [comment]
这里的端口是固定的，多开的话可以调整 http_start(pid,port),注入后再调用即可。

**Comment by ttttupup** [comment]
就是为了方便才这样做的。需要你自己修改后编译。现在注入工具里增加了多开功能。
