### ISSUE TITLE
注入失败。提示Call to LoadLibraryW in remote process failed

### ISSUE THREAD

**Issue by selenaluosfjs** [ttttupup/wxhelper#460]
**Describe the bug**
注入失败，换一个版本也是一样

**Screenshots**
![image](https://github.com/user-attachments/assets/db5b039f-915c-476e-b134-a86c1db105a6)

**Desktop (please complete the following information):**
 - 微信版本 [3.9.2.23]
 - vscode 2022
 - wxhelper-3.9.2.23-v9
 - wxhelper.dll [3.9.2.23-v9]
 - windows [11]
 - windows [x64]

**Comment by selenaluosfjs** [comment]
3.9.5.81可以

**Comment by robin-programmer** [comment]
3.9.5.81这个要提示升级了，更高版本的我也遇到了同样的问题

**Comment by Yantesoft** [comment]
遇到同样问题，有解决办法么

**Comment by robin-programmer** [comment]
> 遇到同样问题，有解决办法么

用Injector进行注入，powershell 和 微信都用管理员身份启动就可以了

**Comment by Yantesoft** [comment]
> > 遇到同样问题，有解决办法么
> 
> 用Injector进行注入，powershell 和 微信都用管理员身份启动就可以了

实测可用！感谢
