### ISSUE TITLE
在ghidra里执行FindCallScript.java脚本后什么也没有打印

### ISSUE THREAD

**Issue by xiaoming6617** [ttttupup/wxhelper#462]
手头没有最新的库，用之前下载好的WeChatSetup-3.9.8.25.exe加载到ghidra,然后导入3.9.11.25fid.fidb，确认导入成功
![image](https://github.com/user-attachments/assets/49d61a48-0742-44b4-a36d-623322cf9972)
然后执行脚本，什么都没有打印，请大佬帮忙看下是使用方式哪里不对吗
![image](https://github.com/user-attachments/assets/eeda37f7-c60c-49ef-8522-118dc292619f)

**Comment by ttttupup** [comment]
看wiki

**Comment by xiaoming6617** [comment]
> 看wiki

wiki看得有点懵逼，还是再请教一下，wiki上的说明是说要先依赖NamedScript.java修改名字，然后再利用FindCallScript.java查找函数符号地址吗

**Comment by ttttupup** [comment]
先进行默认分析，然后NamedScript定位常用函数，最后FindCallScript找到常用函数

**Comment by yuzifu** [comment]
> 先进行默认分析，然后NamedScript定位常用函数，最后FindCallScript找到常用函数

默认分析很慢，要10来个小时，用NamedScript脚本也要几个小时，最后FindCallScript找出来的结果不全，只有如下：
`
FindCallScript.java> Running...
FindCallScript.java> const uint64_t kSendTextMsg = 1822c6b60
FindCallScript.java> const uint64_t kSendMsg = 1822c6b60
FindCallScript.java> const uint64_t kSendImageMsg = 1822bc2f0
FindCallScript.java> const uint64_t kDoAddMsg = 18230ef30
FindCallScript.java> const uint64_t kDoModChatRoomMemberNickName = 18215eeb0
FindCallScript.java> const uint64_t kNewChatMsg = 181b5e140
FindCallScript.java> const uint64_t kFreeChatMsg = 181b55850
FindCallScript.java> const uint64_t kNewChatRoomInfo = 182509cd0
FindCallScript.java> const uint64_t kFreeChatRoomInfo = 182509eb0
FindCallScript.java> const uint64_t kNewWAUpdatableMsgInfo = 181bd27e0
FindCallScript.java> const uint64_t kFreeWAUpdatableMsgInfo = 181b97590
FindCallScript.java> const uint64_t kGetSendMessageMgr = 181b53fd0 ;
FindCallScript.java> const uint64_t kGetChatMgr = 181b876c0 ;
FindCallScript.java> const uint64_t kGetFavoriteMgr = 181b5c670 ;
FindCallScript.java> Finished!
`

另外，FindSqliteCloseScript脚本能找出sqlite3_api_routines的地址，但Sqllite3Script运行后却找不出sqlite的函数地址：
`
Sqllite3Script.java> Running...
Sqllite3Script.java> Finished!
`

**Comment by xiaoming6617** [comment]
看了下Ghidra的cookbook，已经可以正常打印。
