### ISSUE TITLE
语音文件转mp3失败

### ISSUE THREAD

**Issue by selenaluosfjs** [ttttupup/wxhelper#465]
![image](https://github.com/user-attachments/assets/a968d7e7-546a-4c48-a20d-34d548cc3d1f)
![image](https://github.com/user-attachments/assets/a5d8f0d0-9fcc-4e5e-993e-7c4c7600605a)
下载下来的文件使用ffmpeg提示转码失败
试过别的文件(mp3转wav，mp3转amr后转wav)没问题
问下这个要怎么解决

**Comment by ttttupup** [comment]
silk-v3格式参考
https://github.com/kn007/silk-v3-decoder

**Comment by selenaluosfjs** [comment]
好的，我去试试
