### ISSUE TITLE
首先感谢作者，真的太好用了。 希望能加个Q,另外想问下有办法获取群里的成员性别吗？

### ISSUE THREAD

**Issue by huddhudd** [ttttupup/wxhelper#47]
首先感谢作者，真的太好用了。 希望能加个Q,另外想问下有办法获取群里的成员性别吗？

**Comment by ttttupup** [comment]
可以用搜索联系人那个接口搜一下，返回结果是有性别。

**Comment by chuilishi** [comment]
> 可以用搜索联系人那个接口搜一下，返回结果是有性别。

请问接口文档在哪里能看到呢?找了半天找不到

**Comment by ttttupup** [comment]
> > 可以用搜索联系人那个接口搜一下，返回结果是有性别。
> 
> 请问接口文档在哪里能看到呢?找了半天找不到

对应的分支的readme里

**Comment by huddhudd** [comment]
不好意思， 我找了一圈都没发现。 你是指的这两个中的一个 ？ 

46.联系人列表  只有找到这个  55.获取联系人或者群名称**

**Comment by huddhudd** [comment]
我是指群里的成员性别

**Comment by ttttupup** [comment]
19.查找微信 这个接口

**Comment by ttttupup** [comment]
> 19.查找微信 这个接口

这个好像不能通过wxid搜，不太好用

**Comment by huddhudd** [comment]
嗯， 我也发现了。另外这个接口我输入手机好象也不能正常返回

**Comment by ttttupup** [comment]
可以自己找找群成员信息的call，或者数据库里找找

**Comment by huddhudd** [comment]
数据库里找过了。 的确没找到 。   希望以后的版本能有吧。 这个功能还是非常有用。 能查看别人的信息

**Comment by ttttupup** [comment]
查找昵称的那个方法返回的就有所有信息，那个buff里能看到的信息都有，才想起来。

**Comment by huddhudd** [comment]
嗯。 可惜我不太会代码方面的东西。 意思改动不大是吧
