### ISSUE TITLE
dll的窗口已经打开了,但是访问仍然没有反应?

### ISSUE THREAD

**Issue by chuilishi** [ttttupup/wxhelper#48]
3.9.0.28版本
请求是这样的:
data = {"wxid": "文件传输助手", "msg": "hello,world"}
response = requests.post("http://127.0.0.1:19088/api/?type=2", data=json.dumps(data))

**Comment by ttttupup** [comment]
文件助手的wxid是 filehelper，填写错误一般会返回0

**Comment by chuilishi** [comment]
> 文件助手的wxid是 filehelper，填写错误一般会返回0

不是这个问题啊,所有的东西返回的都是502😭

**Comment by ttttupup** [comment]
http 服务没起起来，查看下端口是否被占用了

**Comment by chuilishi** [comment]
> http 服务没起起来，查看下端口是否被占用了



> http 服务没起起来，查看下端口是否被占用了

刚刚排查了一下,端口是被微信占用的,而且还是listening的状态

**Comment by chuilishi** [comment]
我的电脑开了全局的代理,不知道有没有影响

**Comment by ttttupup** [comment]
退出重新注入，观察下端口监听情况

**Comment by chuilishi** [comment]
重新试了一遍,甚至把3.8的重新编译了一遍,又注入了3.8版本的微信,仍然在listening的情况下报502
(另:这次使用了json格式的请求,而不是data,各种细节都看了,仍然不行😭😭😭)
![image](https://user-images.githubusercontent.com/108377487/224269875-28bb943b-d5f8-4eec-8dec-df5e93e93e7b.png)

**Comment by chuilishi** [comment]
> 重新试了一遍,甚至把3.8的重新编译了一遍,又注入了3.8版本的微信,仍然在listening的情况下报502 (另:这次使用了json格式的请求,而不是data,各种细节都看了,仍然不行😭😭😭) ![image](https://user-images.githubusercontent.com/108377487/224269875-28bb943b-d5f8-4eec-8dec-df5e93e93e7b.png)

是不是注入顺序的问题,我先把injector.dll注入了,然后再注入了wxhelper.dll,而且都是在打开了微信但是尚未登录的情况下注入的

**Comment by ttttupup** [comment]
注入wxhelper.dll, injector.dll是用来注入wxhelper.dll的。你这个请求错了，参考下面的
`import requests
import json

url = "127.0.0.1:19088/api/?type=2"

payload = json.dumps({
  "wxid": "filehelper",
  "msg": "123"
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)`

**Comment by chuilishi** [comment]
> 注入wxhelper.dll, injector.dll是用来注入wxhelper.dll的。你这个请求错了，参考下面的 `import requests import json
> 
> url = "127.0.0.1:19088/api/?type=2"
> 
> payload = json.dumps({ "wxid": "filehelper", "msg": "123" }) headers = { 'Content-Type': 'application/json' }
> 
> response = requests.request("POST", url, headers=headers, data=payload)
> 
> print(response.text)`

感谢作者大大,折腾一天了,终于ok了

**Comment by chuilishi** [comment]
还是想问一下,将injector.dll注入到wxhelper.dll的方式和将wxhelper.dll注入到wechat的方式是一样的嘛,(或者说是将这两个dll合并?)
最后一个问题了,不能解决就放弃了😥

**Comment by ttttupup** [comment]
injector.dll是个注入工具，用来注入其他的dll的，不是用来被注入的。注入进去了也没有功能。
