### ISSUE TITLE
hook接收文本消息，图片消息，群消息.该接口将hook的消息通过tcp回传给本地的端口

### ISSUE THREAD

**Issue by estinfo** [ttttupup/wxhelper#5]
/api/?type=9

建议增加必填参数 IP.
入参：
{
     "ip":"127.0.0.1"
    "port": "19099"
}

**Comment by ttttupup** [comment]
这个接口只是考虑到了大部分hook都放在本地操作，默认的127.0.0.1。

**Comment by estinfo** [comment]
hook 在 本地wx 。dll 中 socket client ，连接TCP Server 只能在本地，如果 消息再转发又再多一个操作然后再转发，建议增加或者使用ws接口。感谢。

**Comment by ttttupup** [comment]
增加ip参数后，可以任意ip链接了。不需要ws了。

**Comment by estinfo** [comment]
恩，tcp 也可以的。感谢增加！
