### ISSUE TITLE
3.9.0.28 下载图片打不开，文件大小与原图一样，估计是转码相关的问题

### ISSUE THREAD

**Issue by tlxfif** [ttttupup/wxhelper#52]
使用winhex打开发现里面的结构完全不一样，因为我是遍历下载某个会话的图片，不知道这样是不是不行
重新打开微信只下载一个图片也会出现这种情况
400个图片中，大部分图片是有问题的，只有少数图片7-8个图片是可以的

![微信图片_20230319154135](https://user-images.githubusercontent.com/30333934/226161058-1657275e-776e-4a40-86e9-e4f78526db5b.png)

**Comment by ttttupup** [comment]
type=56 附件下载接口还是哪个接口？

**Comment by tlxfif** [comment]
附件下载的接口

**Comment by ttttupup** [comment]
附件下载的接口，图片类型的消息保存的都是png格式的，只有视频的才会保存jpg的，不过视频的预览图wxhelper那里有问题，没保存下来。

**Comment by ttttupup** [comment]
你截图的这个图片你用0x49 异或一下

**Comment by tlxfif** [comment]
稍等，昨天感冒了睡得早

**Comment by tlxfif** [comment]
异或以后可以
![image](https://user-images.githubusercontent.com/30333934/226778732-498daedb-f921-45cc-9871-a66fb8c0ce0c.png)

**Comment by ttttupup** [comment]
暂时未遇到这种情况，理论上保存的都是最终的图片。不需要解码了。看你这种情况，还需要解码。
