### ISSUE TITLE
首先感谢作者 ，我想问怎么获取自己发送的消息呢？

### ISSUE THREAD

**Issue by zgc568069476** [ttttupup/wxhelper#53]

**Comment by ttttupup** [comment]
直接查库，或者hook sendtext

**Comment by zgc568069476** [comment]
对不起 我没问清楚 ，我是想问 怎么获取自己发送的信息的 msgid，查数据库的话 我刚试了一下 ，没成功获取到 我用 的 select * from Msg，我主要想自己发送的 消息置顶 我看置顶的接口有 个参数是 msgid 所以我想知道怎么获取自己发送的消息 的msgid

**Comment by ttttupup** [comment]
调用sendText返回的就是消息的localid好像，时间长了记不清了。

**Comment by zgc568069476** [comment]
我看了您写的 sendText 的返回值里面没有 localid，只有一个成功与否的的标记 ` int success = SendText(WS2LW(wxid), WS2LW(msg));`

**Comment by zgc568069476** [comment]
谢谢作者 我知道怎么找了

**Comment by ttttupup** [comment]
返回的sucess 就是这个聊天信息结构体的地址，里面有localId
