### ISSUE TITLE
作者我想请教一个问题，关于接受信息并且发送的

### ISSUE THREAD

**Issue by lyh2606179909** [ttttupup/wxhelper#54]
dll远程注入进目标进程，为啥个人接受到信息没有徽调用到python

**Comment by lyh2606179909** [comment]
![1679293600326](https://user-images.githubusercontent.com/31297917/226263196-10517997-8c3e-4e1b-8cf3-de74f889e27f.png)
![1679293661642](https://user-images.githubusercontent.com/31297917/226263318-1fe2f66c-c923-45f1-9c0d-257c4f16e729.png)

**Comment by ttttupup** [comment]
接收消息需要先启动一个tcpserver，再调用hook message的接口，才会收到消息

**Comment by lyh2606179909** [comment]
> 接收消息需要先启动一个tcpserver，再调用hook message的接口，才会收到消息

我这边是已经开了的，只是注入工具不是用你这个。然后这边调用暴露的api接口有文档提供吗谢谢

**Comment by ttttupup** [comment]
文档在对应的分支里的readme。请先看readme

**Comment by lyh2606179909** [comment]
![1679367954821](https://user-images.githubusercontent.com/31297917/226508830-fffe7200-ddef-40ef-bc07-f0bd25269a38.png)
![1679367990635](https://user-images.githubusercontent.com/31297917/226508881-28f42138-abe6-41b5-add3-cc3f78f4e43a.png)

你好作者，我这边是注入成功了http，而且下载了你最新的dll调用出现这个情况

**Comment by ttttupup** [comment]
body里是不是穿的无效json，这个接口不需要传json

**Comment by yoin007** [comment]
> 接收消息需要先启动一个tcpserver，再调用hook message的接口，才会收到消息

`def hook_msg():
    """
    hook 消息
    :return:
    """
    url = "127.0.0.1:19088/api/?type=9"
    payload = json.dumps({
        "port": "19099",
        "ip": "127.0.0.1"
    })
    headers = {
        'Content-Type': 'application/json'
    }
    response = requests.request("POST", url, headers=headers, data=payload)
    print(response.text)`

hook_msg该如何跟tcpserver配合呢
