### ISSUE TITLE
如何用成品DLL 自定义端口

### ISSUE THREAD

**Issue by q592850** [ttttupup/wxhelper#55]
如何用成品DLL 自定义端口，我需要指定几个特定的端口来用！

**Comment by ttttupup** [comment]
修改 dllMain ->http_start(19088); 成品没法修改，需要改下代码再打包即可。

**Comment by q592850** [comment]
> 修改 dllMain ->http_start(19088); 成品没法修改，需要修改下代码再打包即可。

你好作者，现在遇到问题就是URL端口占用，可否集成个自定义端口这样的骚操作！

**Comment by ttttupup** [comment]
自定义端口需要注入后调用http_start(port);需要操作两次才能用，嫌麻烦就没有弄。可以自己在注入工具类实现一下

**Comment by q592850** [comment]
作者 您就集成下吧，我们这些没有环境的，搞不了这个，拜托拉！

**Comment by q592850** [comment]
等你哦，亲！ 比心！~
