### ISSUE TITLE
置顶的消息 是乱码

### ISSUE THREAD

**Issue by zgc568069476** [ttttupup/wxhelper#56]
![8a89e8f01b59b3aeda68485abbf028b](https://user-images.githubusercontent.com/128341521/226287160-9ac930e7-e8b8-47dd-a666-e54c0466b6e0.png)
微信版本是 3.9.0.28 
这个是bug 还是？
我看了您的将查询的 内容 用 函数 `wstring w_content = String2Wstring(content);`  进行了转换 这里或许应该用这个函数来转换，utf8_to_unicode ，我看了一下 content的内容应该是UTF-8编码的

**Comment by ttttupup** [comment]
select localId,trContent from MSG where MsgSvrID= xx ，用这个sql查一下，看一下返回的是什么

**Comment by zgc568069476** [comment]
![ee730743afe8dd404e5d660499cfe4c](https://user-images.githubusercontent.com/128341521/226341983-ae19e3f4-c469-4189-9303-b58f079a6672.png)
```
//wstring w_content = String2Wstring(content);
wstring w_content = utf8_to_unicode(content.c_str());
``` 
我这么换了一下 发出来的置顶消息就没有问题了

**Comment by ttttupup** [comment]
这个地方String2Wstring 用的ansi，系统如果不是utf8编码会乱码，这个地方要改一下
