### ISSUE TITLE
如何获取音频、图片

### ISSUE THREAD

**Issue by xapanyun** [ttttupup/wxhelper#57]
先感谢作者的无私分享，很好用！！！
想了解下怎么获取语音slk文件以及图片地址（这样可以调用图片解密接口来处理）

利用python分别打印出来的语言和图片信息：
**语音：**
{'content': '<msg><voicemsg endflag="1" cancelflag="0" forwardflag="0" voiceformat="4" voicelength="1695" length="1318" bufid="0" aeskey="6a0357ff5ac5e3XXXXd20296a" voiceurl="3052020100044b3e12e70020464186ad90424383XX2372d616637332d35636362393838326366626202040114000f0201000400" voicemd5="" clientmsgid="41613132XX0320239d64488518f104" fromusername="wxid_35y708auj68l21" /></msg>', 'fromGroup': 'wXXXX', 'fromUser': 'wxid_XXXXXXXX', 'isSendMsg': 0, 'msgId': 26785XXXXX786, 'pid': 15708, 'sign': '01cf0b8XXXX178af53b4', 'signature': '<msgsource>\n\t<signature>v1_XN/mSPSj</signature>\n</msgsource>\n', 'time': '2023-03-20 22:16:57', 'timestamp': 1679321817, 'type': 34}
**图片：**
{'content': '<?xml version="1.0"?>\n<msg>\n\t<img aeskey="2d67c989743713f4bafa3fee0fe8a43c" encryver="1" cdnthumbaeskey="XXXXX" cdnthumburl="30570201XXX0201000405004c537700" cdnthumblength="5173" cdnthumbheight="120" cdnthumbwidth="88" cdnmidheight="0" cdnmidwidth="0" cdnhdheight="0" cdnhdwidth="0" cdnmidimgurl="3057020100XXXXX0405004c537700" length="202143" md5="fbXXX90a" hevc_mid_size="202143" />\n\t<platform_signature></platform_signature>\n\t<imgdatahash></imgdatahash>\n</msg>\n', 'fromGroup': 'wxid_XXXX', 'fromUser': 'wxid_XXXX', 'isSendMsg': 0, 'msgId': 9191962484837345697, 'pid': 15708, 'sign': '8f04XXXX4b8', 'signature': '<msgsource>\n\t<alnode>\n\t\t<fr>2</fr>\n\t</alnode>\n\t<sec_msg_node>\n\t\t<uuid>4c00f7bdf475921ace17aeeb3d5fc6b2_</uuid>\n\t</sec_msg_node>\n\t<signature>v1_unhGOZzS</signature>\n</msgsource>\n', 'time': '2023-03-20 22:17:51', 'timestamp': 1679321871, 'type': 3}

**Comment by zgc568069476** [comment]
```
import os
def _postJson(url,dicts={}):
    mainurl = "http://127.0.0.1:19088"
    head={'Accept-Charset': 'utf-8', 'Content-Type': 'application/json'}
    req = requests.post(mainurl+url,json.dumps(dicts),headers=head)
    return req.json()

def get_image(msgId):    
    ret = _postJson("/api/?type=56",{"msgId":msgId})
    # 下面的代码是我自己实现的 作者的代码没有返回 save_path ，你可以通过其他方法找到 存储路径 然后跟俊 msgid 组合成  文件地址
    save_path = ret.get("save_path",None)
    cnt=0
    while not os.path.exists(save_path):
        time.sleep(0.1)
        cnt+=1
        if cnt > 100: break
    if os.path.exists(save_path):
        return save_path
    return None

```

**Comment by ttttupup** [comment]
图片消息如果没有路径，可能是图片比较大没有自动下载，可以调用 type=56 下载附件接口下载，默认在wxhelper目录下。语音消息需要hook，后面有时间补上语音的hook。

**Comment by ttttupup** [comment]
hook语音的功能已经更新

**Comment by xapanyun** [comment]
高效，感谢！ 开个捐赠吧， 这么好用希望可以长期维护下去。
