### ISSUE TITLE
消息防撤回功能是否可以通过hook实现？

### ISSUE THREAD

**Issue by I-am-not-a-dalao** [ttttupup/wxhelper#58]
虽然防撤回功能可以通过修改WeChatWin.dll实现，但这是直接修改本体文件了。
所以想问一下这个功能可以在后面的计划中加上吗

**Comment by ttttupup** [comment]
在hook_recv里自己处理一下就可以了。在收到撤回消息时做下处理，或者直接nop撤回的call。暂时没加这个功能的计划。

**Comment by I-am-not-a-dalao** [comment]
感谢大佬回复和提供的思路。期待后续的计划中能添加进来
