### ISSUE TITLE
大佬能不能出一个黑名单的检测功能

### ISSUE THREAD

**Issue by lyh2606179909** [ttttupup/wxhelper#60]

**Comment by ttttupup** [comment]
个人的黑名单列表还是什么？

**Comment by ttttupup** [comment]
你用wxid加好友那个功能全加一遍好友，没反应的就是好友，其他的就是被删了。

**Comment by lyh2606179909** [comment]
> 你用wxid加好友那个功能全加一遍好友，没反应的就是好友，其他的就是被删了。

那假如好友删除，又不想它知道吧。加出去不就被知道在测试？

**Comment by ttttupup** [comment]
研究研究Contact这个表
