### ISSUE TITLE
最新版的dll在启动hook消息直接微信卡死

### ISSUE THREAD

**Issue by Circlefork** [ttttupup/wxhelper#61]
![1679474742804](https://user-images.githubusercontent.com/121424042/226848464-bc93a088-bbdc-44b5-ab9d-90539d06d14a.png)

微信直接卡死然后崩溃了

**Comment by Circlefork** [comment]
其他的没问题 微信是3.9.0.28

**Comment by ttttupup** [comment]
本地启动了tcpserver吗

**Comment by Circlefork** [comment]
启动了

**Comment by ttttupup** [comment]
可以看下崩溃日志

**Comment by Circlefork** [comment]
![1679475112609](https://user-images.githubusercontent.com/121424042/226849889-79a11f4d-2876-4b64-a762-b36fb5d14911.png)

**Comment by Circlefork** [comment]
日志文件在哪里

**Comment by ttttupup** [comment]
微信自己的，崩溃时候会弹出来

**Comment by ttttupup** [comment]
到win事件中心里查一下应用的崩溃信息

**Comment by LeanFly** [comment]
我是修改了 ip_port 里面的 ip为 “0.0.0.0”之后用Python 运行 可以了
