### ISSUE TITLE
大佬，不是很懂启动流程

### ISSUE THREAD

**Issue by pencil1** [ttttupup/wxhelper#62]
假如我用3.9的，是不是不用编译你源代码，直接用tool里的注入工具，注入dll就行了，但是我注入了之后，启动python的监听，然后发请求，是不通的

**Comment by pencil1** [comment]
使用这条命令就可以注入了吗？ConsoleInject.exe  -i WeChat.exe -p E:\testInject.dll
用完这条命令，我启动tcp，但是请求本地结果不成功，我觉得是注入的问题

**Comment by shenhanqing** [comment]
我也是 火绒剑 看到已经注入了，tcp也服务启动，但是postman请求不到

**Comment by ttttupup** [comment]
命令里的内容要替换成自己环境下的dll，注入后，可以用listdll 查看一下是否已经注入成功了。

**Comment by ttttupup** [comment]
> 假如我用3.9的，是不是不用编译你源代码，直接用tool里的注入工具，注入dll就行了，但是我注入了之后，启动python的监听，然后发请求，是不通的

只有hook类接口才会回传消息，其他接口直接就返回结果了。

**Comment by pencil1** [comment]
> 命令里的内容要替换成自己环境下的dll，注入后，可以用listdll 查看一下是否已经注入成功了。

自己环境下的dll是啥意思，我用你3.9分支的dll不行吗

**Comment by ttttupup** [comment]
命令不是复制就能运行，把路径换成你自己的

**Comment by pencil1** [comment]
路径是自己dll的路径

**Comment by ttttupup** [comment]
注入成功的话，能看到端口监听，看不到就是没成功。

**Comment by pencil1** [comment]
好的，感谢，那我再研究一下注入

**Comment by pencil1** [comment]
> 

非常感谢大佬，下班回去试试

**Comment by pencil1** [comment]
![Uploading 1679659884676.png…]()
好像注入不成功，百度找了2个注入工具都不行

**Comment by pencil1** [comment]
![Uploading image.png…]()

**Comment by pencil1** [comment]
TCP    127.0.0.1:8680         0.0.0.0:0              LISTENING       10644
  TCP    [2409:8a55:6be:e680:ad5e:6141:b820:cf23]:54694  [2409:8c54:1040:9::1c]:80  ESTABLISHED     10644

返回结果这样子应该就是没注入成功吧，用了n个注入工具都不行，啥情况

**Comment by ttttupup** [comment]
可以自己用source下的ConsoleInjec.cpp源码调试一下，注入的dll，需要注意一下，带port后缀的是指定端口的，注入不会启动http。不带的才会再注入成功后启动http。
