### ISSUE TITLE
postman请求不到接口

### ISSUE THREAD

**Issue by shenhanqing** [ttttupup/wxhelper#63]
1.Win10专业版
2.缺少环境，但是安装完vs2022后都可以运行
3.注入成功，火绒剑可以看到
4.python3.8，运行脚本无报错

关闭clash，虽然本地端口不会转发

postman还是请求不到~

**Comment by ttttupup** [comment]
不要用 specify-port版本的dll，如果注入成功了，检查19088端口是否被正常监听。

**Comment by shenhanqing** [comment]
> 

大佬能有空的时候能在优化一下么？我看有直接把 dll 放在 WeChat 启动目录下就行的，主要环境难搞，怕放在轻量服务器上环境配不好，虽然自己也是干安全的 但是不是逆向方向确实有点难顶，跪谢~

**Comment by ttttupup** [comment]
这个dll位置无所谓，只不过注入工具是随便写的，随便找个注入工具注入进去就行了。

**Comment by shenhanqing** [comment]
> 这个dll位置无所谓，只不过注入工具是随便写的，随便找个注入工具注入进去就行了。

可以了，谢谢大佬。环境缺失的问题安装 vc15 17 19库就不会提示缺少 XXXX.DLL，注入工具后面的小伙伴可以使用https://github.com/MountCloud/InjectDllTool相对友好一点。再次感谢大佬~

**Comment by shenhanqing** [comment]
> 这个dll位置无所谓，只不过注入工具是随便写的，随便找个注入工具注入进去就行了。
大佬，遇到一个问题，hook消息接口，收到一张图片后，图片的路径是什么？我看接口文档里没有查询图片的接口，获取消息附件的接口出参里也没有。想自己扩展GPT4和人脸识别的功能 现在卡住了~跪谢大佬

**Comment by shenhanqing** [comment]
> 这个dll位置无所谓，只不过注入工具是随便写的，随便找个注入工具注入进去就行了。

我看收到图片后是一个 xml里面包含的是 cdn信息

**Comment by ttttupup** [comment]
消息里有图片地址的话就是个人信息里的保存目录 + 消息里的图片地址就是全路径。如果消息里没有地址，需要通过消息附件下载接口主动下载，大图片不点开，一般都不会主动下载。
