### ISSUE TITLE
指定端口问题？

### ISSUE THREAD

**Issue by 157276303** [ttttupup/wxhelper#66]
ConsoleInject.exe  -i demo.exe -p E:\testInject.dll  -P  1888x

-----------------------

第一次没有问题，端口通讯正常
多开后，第二个启动且更换端口后，状态也是返回1，但实际请求端口无结果返回。

----------

所以好奇，当两个一样的 demo.exe 在运行 ，注入器分得清，哪个注入了，哪个还没注入吗？

直接用 用pid 替换 demo.exe ，这个会不会好点呢？

新人新手

**Comment by ttttupup** [comment]
这个注入工具就是随便写的，注入的时候比较方便。没处理多开注入，源码在那里，稍微修改下指定pid就行了。
