### ISSUE TITLE
3.9.0.28-specify-port-V13指定端口注入后，服务并没有启动

### ISSUE THREAD

**Issue by xisuo67** [ttttupup/wxhelper#69]
版本：3.9.0.28-specify-port-V13
![image](https://user-images.githubusercontent.com/22284363/227754618-843de607-d029-4119-bc84-a7f7d10a63ca.png)

**Comment by 157276303** [comment]
重新打包的和工具原22k 那个我也试了不启动，但有个89k 那个是可以的

**Comment by xisuo67** [comment]
还有个问题，之前发送@消息的接口没记错的话应该是有的，看最新代码，这个接口好像也没了

**Comment by ttttupup** [comment]
用这个分支下的注入工具，或者自己编译一下source里代码
