### ISSUE TITLE
请问下xml转了base64以后还是乱码要怎么处理呢，感谢感谢

### ISSUE THREAD

**Issue by tlxfif** [ttttupup/wxhelper#71]
![image](https://user-images.githubusercontent.com/30333934/227789646-4737f918-9c13-4970-9f2b-7bbee6988c97.png)
消息里面的"CompressContent"字段，我想拿到引用消息里面的内容，但是使用base64解析了以后是乱码：)

**Comment by ttttupup** [comment]
这个只能不断尝试编码格式，或者使用微信的parsexml的call。转发消息的功能里一般有这个功能。

**Comment by ttttupup** [comment]
可以转成byte再用gb2312编码，应该是gb2312的。

**Comment by tlxfif** [comment]
好滴感谢
