### ISSUE TITLE
3.8.0.41和3.8.1.26 注入后都无效

### ISSUE THREAD

**Issue by acdzc** [ttttupup/wxhelper#74]
3.9.0.28  注入后 除了调用程序请求外   wechat.exe  进程也会发请求  多开的话  会很卡

尝试降版本 3.8.0.41和3.8.1.26 均无效 注入后 要么崩溃 要么 请求的时候崩溃

**Comment by ttttupup** [comment]
注入一个dll就会启动一个tcpserver

**Comment by ttttupup** [comment]
不清楚什么配置，正常2-3个不会卡
