### ISSUE TITLE
接口46  获取不到联系人备注

### ISSUE THREAD

**Issue by acdzc** [ttttupup/wxhelper#78]

**Comment by ttttupup** [comment]
这个接口只是联系人，不包含联系人标签。

**Comment by ttttupup** [comment]
这个内部就有，找到这个call就行了。

**Comment by ttttupup** [comment]
这个直接查库比较简单吧，调用34接口，
`select Remark from Contact c  where c.UserName = "wxid_123456"`

**Comment by ttttupup** [comment]
数据库没值，肯定是空白。你可以自己测试一下，看看数据库有什么变化。
