### ISSUE TITLE
ConsoleInject 注入不了

### ISSUE THREAD

**Issue by estinfo** [ttttupup/wxhelper#8]
MFCApplication.exe 
填写 
进程名：WeChat.exe
dll 文件路径： C:\xx\wxhelper.dll
确定 直接退出
可以注入上

cmd -> ConsoleInject.exe Wechat.exe wxhelper.dll 无提示，注入不了，有参数吗？

Tool 注入工具可以开源吗？

**Comment by ttttupup** [comment]
注入  ConsoleInject.exe  -i demo.exe -p E:\xx.dll
卸载   ConsoleInject.exe  -u demo.exe -d  xx.dll   这两个注入程序因为电脑摔坏了，换电脑了，源码没有了，记得还有个-h 命令行提示的，有时间了再重写一下

**Comment by ttttupup** [comment]
-i  注入程序名   -p 注入dll路径   
-u 卸载程序名   -d 卸载dll名称

**Comment by estinfo** [comment]
case 63:
        if ( v7 == 105 )
        {
          v29 = v5;
          v28 = L"Option -%i requires an argument.\n";
        }
        else if ( v7 == 112 )
        {
          v29 = v5;
          v28 = L"Option -%p requires an argument.\n";
        }
        else if ( v3 == 117 )
        {
          v29 = 117;
          v28 = L"Option -%u requires an argument.\n";
        }
        else if ( v3 == 100 )
        {
          v29 = 100;
          v28 = L"Option -%d requires an argument.\n";
        }
        else
        {
          v29 = v5;
          v28 = L"Unknown option character `\\x%x'.\n";
        }

恩，看到了~感谢！
