### ISSUE TITLE
建议hook消息加上http方式

### ISSUE THREAD

**Issue by dayerqq** [ttttupup/wxhelper#83]
httpserver还是比较常用。和hook消息的socket一样的方法。直接以json格式post请求httpserver

**Comment by ttttupup** [comment]
ws还说的过去，http实在是说不过去了。

**Comment by dayerqq** [comment]
这个毕竟是单向的，hook以后把消息传到外面，也没有双向传输，没必要soket和ws，这样浪费资源如果服务器差一点的话做个交互机器人服务器扛不住

**Comment by dayerqq** [comment]
还有就是遇到超长消息的时候。socket容易接收出现半截。还得自己做处理

**Comment by estinfo** [comment]
> httpserver还是比较常用。和hook消息的socket一样的方法。直接以json格式post请求httpserver


Http 消息你是如何获取到实时获取到消息呢？一直轮巡？

**Comment by dayerqq** [comment]
> 

你自己创建http服务器，hook信息请求，为什么要一直轮询？
