### ISSUE TITLE
3.9.0.28通过wxid新增好友，不成功。

### ISSUE THREAD

**Issue by dj714330240** [ttttupup/wxhelper#84]
接口调用提示成功，目标好友未收到好友请求。
建议再加一个msg参数可以自定义打招呼内容，方便目标好友确认发起者身份。
版本3.9.0.28

**Comment by ttttupup** [comment]
个人精力有限，新版本更新后，旧版本的bug会在新版中修复。3.9.2.23可以复现，就在3.9.2.23版本修复。

**Comment by dj714330240** [comment]
雀氏费神费力，吃力不讨好。辛苦啦

**Comment by ttttupup** [comment]
3.9.2.23 版本实现了。
