### ISSUE TITLE
我充值十元想要变强.帮我远程协助一下呗

### ISSUE THREAD

**Issue by wan-kenny** [ttttupup/wxhelper#86]
发布的3.9.2.23 可以成功注入到 3.9.2.20吗?

**Comment by wan-kenny** [comment]
我一直注入不成功

**Comment by wan-kenny** [comment]
ConsoleInject.exe  -i WeChat.exe -p G:\wechat_hook\wxhelper-3.9.2.23\tool\injector\injector.dll  -P  19088 一直提示非法参数

**Comment by wan-kenny** [comment]
应该是注入工具有问题了,我再试试其它的

**Comment by dj714330240** [comment]
对应的dll只能注入到对应的wx版本
注入不成功多看看微信版本和对应的wxhelper版本
指定port只有specify-port分支可以

**Comment by ttttupup** [comment]
不能跨版本使用。specify-port带有该后缀的release 版本，才可以使用指定端口注入

**Comment by wan-kenny** [comment]
> 不能跨版本使用。specify-port带有该后缀的release 版本，才可以使用指定端口注入

你有QQ什么的吗 我赞助10元 远程协助一下

**Comment by ttttupup** [comment]
> > 不能跨版本使用。specify-port带有该后缀的release 版本，才可以使用指定端口注入
> 
> 你有QQ什么的吗 我赞助10元 远程协助一下

这注入不进去我也没办法呀

**Comment by ttttupup** [comment]
可以查一下依赖，大部分都是缺dll导致的

**Comment by wan-kenny** [comment]
Listdlls.exe 4212    里面有injector.dll 就算注入成功吗?注入成功后,我调用接口 不成功. 127.0.0.1:19088/api/?type=3
里面的这个端口,.注入成功的话,会多一个吗

**Comment by wan-kenny** [comment]
> 可以查一下依赖，大部分都是缺dll导致的

Listdlls.exe 4212 里面有injector.dll 就算注入成功吗?注入成功后,我调用接口 不成功. 127.0.0.1:19088/api/?type=3
里面的这个端口,.注入成功的话,会多一个吗

**Comment by wan-kenny** [comment]
> 可以查一下依赖，大部分都是缺dll导致的
我的微信版本是  wxhelper-3.9.2.23.注入成功的话  多出来的端口是写死的吗?是多少呢?

**Comment by ttttupup** [comment]
tasklist | findstr "WeChat.exe"
netstat -ano | findstr "your wechat pid"   指定端口的不支持3.9.2.23

**Comment by wan-kenny** [comment]
> 指定端口的不支持3.9.2.

我使用了这命令 
![image](https://user-images.githubusercontent.com/59479203/230531103-2fd49724-c627-4a30-bac0-b96161dd3fd9.png)
![image](https://user-images.githubusercontent.com/59479203/230531306-316d5efb-07a2-4358-97d6-c820e34028f9.png)
![image](https://user-images.githubusercontent.com/59479203/230531368-18ca85da-31e8-4009-b928-686511790186.png)
![image](https://user-images.githubusercontent.com/59479203/230531410-a6cfc632-b449-48ff-aedf-fd810cc1a1a6.png)
都没有多出来接口,毫无变换

**Comment by ttttupup** [comment]
注入工具有源码，debug一下。

**Comment by wan-kenny** [comment]
> 注入工具有源码，debug一下。

是这个原因吗 好的 我重新debug一下
