### ISSUE TITLE
建议增加 获取小程序code

### ISSUE THREAD

**Issue by estinfo** [ttttupup/wxhelper#88]
建议增加 获取小程序code
如传入：
"appid": "wx91d27dbf599dff74" 

返回：
{
  "errCode": 1, 
   
  "data": {
  "appid": "wx91d27dbf599dff74", 
  "code": "04318p0w3L6zSY2Uln3w3fX8bq018p08" 

}, 

"account_wxid": "wxid_j9x86l798s2f22" 
 
}

**Comment by ttttupup** [comment]
小程序不熟悉，这个code是用来做什么的？还是授权用的那个code

**Comment by estinfo** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.login.html

**Comment by ttttupup** [comment]
这个是风险接口，和支付一样
