### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by w2q1227** [ttttupup/wxhelper#9]
readme里面的更新说明的时间搞错了应该是2023，写成了2022，能不能分享下找call的思路，我这边也在试这个，没有搞动打开微信浏览器后怎么样找call

**Comment by ttttupup** [comment]
后续会跟新找call的思路，打算把ghidra的项目共享出来。

**Comment by xiaoming6617** [comment]
ghidra找call有比较详细的教程吗，step by step的那种，最近在拜读楼主的代码，找call不知道怎么找
