### ISSUE TITLE
微信多开异常

### ISSUE THREAD

**Issue by xisuo67** [ttttupup/wxhelper#94]
微信版本
![image](https://user-images.githubusercontent.com/22284363/230840289-c80c4238-512c-4231-ac1b-f87348a69fee.png)

下载最新代码wxhelper-3.9.2.23-V4，使用微信多开，异常

![image](https://user-images.githubusercontent.com/22284363/230840252-4cb0495e-7060-4051-b889-64b983fe4fff.png)

**Comment by xisuo67** [comment]
啊，我自己的问题~

**Comment by a719724508** [comment]
是怎么解决的呢，我也遇到同样的问题，已经在-m参数后正确填写了对应的pid
![image](https://user-images.githubusercontent.com/12265045/233830697-20546b96-3844-4c87-802a-6d57933680d1.png)

**Comment by a719724508** [comment]
需要自行编译source目录下ConsoleApplication.cc，tool中的injector不是最新的
