### ISSUE TITLE
使用3.9.2.23 v4打包的dll注入后，调用hook功能微信会被关闭是什么问题呀

### ISSUE THREAD

**Issue by aihongfei** [ttttupup/wxhelper#98]

**Comment by ttttupup** [comment]
调用哪个接口崩溃

**Comment by aihongfei** [comment]
type=9

**Comment by aihongfei** [comment]
使用你的release里的dll注入不会崩溃，我自己打包后注入调用type=9微信会关闭，我没有改任何代码，不知道什么问题

**Comment by ttttupup** [comment]
只能打debug包看日志了

**Comment by aihongfei** [comment]
<img width="1069" alt="Snipaste_2023-04-13_18-15-17" src="https://user-images.githubusercontent.com/82986195/231728929-457e0801-d99f-43c9-b850-2b4a1608a74f.png">

**Comment by ttttupup** [comment]
调用了两次出现错误，还是一次就出现错误了。日志在微信的安装目录下log目录。可以在可疑的地方随意打印

**Comment by wms888** [comment]
如何打包成dll吗  装了环境一直报错 CMake Warning:
  Ignoring extra path from command line:

   "\"

**Comment by aihongfei** [comment]
> 如何打包成dll 装了环境一直报错 CMake Warning: Ignoring extra path from command line:
> 
> ""
还需要吗

**Comment by wms888** [comment]
> 如何打包成dll 装了环境一直报错 CMake Warning: Ignoring extra path from command line:
> 
> "" 还需要吗
需要 来个链接吧 感谢大佬🥹

**Comment by aihongfei** [comment]
加下我吧 wx:   a13102252106
