### ISSUE TITLE
请教下，夜间图片是否可以自动下载？

### ISSUE THREAD

**Issue by wttnb911** [ttttupup/wxhelper#99]

**Comment by ttttupup** [comment]
type=56 可以直接下载图片消息，属于主动下载。

**Comment by wttnb911** [comment]
如果是基于https://github.com/ljc545w/ComWeChatRobot项目的cdn下载，之前使用过程中发现有时候下载会阻塞。所以想直接解密本地dat文件，但是需要解决夜间自动下载的问题

**Comment by ttttupup** [comment]
![image](https://user-images.githubusercontent.com/31303661/232178228-7f0ebe12-287c-4504-adc4-9d8eb83c5a2b.png)

200M以内下载是微信自带的功能，这个功能调整一下就不是立即下载了，56接口的参数调整一下就不是实时下载了。0 1的标志，大概的意思就是立即下载和延迟下载的意思。ComWeChatRobot的这个我没研究，我猜应该差不多吧。
